'use strict';function createDate$$module$utils(a){return a instanceof Date?a:new Date(a)}function createDiv$$module$utils(...a){let b=document.createElement("div");b.classList.add(...a);return b}function showElement$$module$utils(...a){a.forEach((a)=>{a.classList.remove("d-hidden")})}function hideElement$$module$utils(...a){a.forEach((a)=>{a.classList.add("d-hidden")})}function setPixels$$module$utils(a,b,c){a.style[b]=c+"px"}var module$utils={};module$utils.createDate=createDate$$module$utils;
module$utils.createDiv=createDiv$$module$utils;module$utils.showElement=showElement$$module$utils;module$utils.hideElement=hideElement$$module$utils;module$utils.setPixels=setPixels$$module$utils;function yearText$$module$Markers(a,b){a=a.getFullYear();return{plus:!(a%b),text:a}}
const MT$$module$Markers=[function(a){a=a.getMilliseconds();return{plus:!a,text:a}},function(a){a=a.getSeconds();return{plus:!a,text:a}},function(a){var b=a.getMinutes();return{plus:!b,text:b||a.getHours()}},function(a){var b=a.getHours();return{plus:!b,text:b||a.getDate()}},function(a,b){var c=a.getDate();return{plus:1===c,text:1===c?a.toLocaleDateString(b,{month:"short"}):c}},function(a,b){return{plus:!1,text:a.toLocaleDateString(b,{month:"short",day:"numeric"})}},function(a,b){return a.getMonth()?
{plus:!1,text:a.toLocaleDateString(b,{month:"short"})}:yearText$$module$Markers(a,1)},function(a){return yearText$$module$Markers(a,10)},function(a){return yearText$$module$Markers(a,100)},function(a){return yearText$$module$Markers(a,1E3)},function(a){return yearText$$module$Markers(a,1E4)}];function Markers$$module$Markers(a){this.content=a;this.band=a.band;this.widget=a.widget;this.markerText=MT$$module$Markers[a.band.scale];this.element=createDiv$$module$utils("d-markers")}
Markers$$module$Markers.prototype={render:function(){let a=this.content.range.begin,b=this.content.range.end,c=new Date(a);var d;let e;for(;d=this.element.firstChild;)this.element.removeChild(d);for(this.band.ceilDate(c);c<b;)d=this.markerText(c,this.widget.settings.locale),e=createDiv$$module$utils("d-marker"),d.plus&&e.classList.add("d-plus"),setPixels$$module$utils(e,"left",this.band.calcPixels(c-a)),e.innerText=d.text,this.element.append(e),this.band.incrDate(c)}};var module$Markers={};
module$Markers.default=Markers$$module$Markers;function Events$$module$Events(a){this.content=a;this.band=a.band;this.widget=a.widget;this.renderEvent="overview"===a.band.layout?this.renderOverviewEvent:this.renderNormalEvent;this.element=createDiv$$module$utils("d-events");this.overflows=[]}
Events$$module$Events.prototype={render:function(){var a;let b,c=this.widget.events,d=this.content.range,e=c.binInsertPosOf({start:d.begin}),h=c.binInsertPosOf({start:d.end});for(;a=this.element.firstChild;)this.element.removeChild(a);this.nLines=Math.floor(this.element.clientHeight/this.widget.lineHeight);this.lines=[];this.busy=[];for(a=0;a<this.nLines;a++)this.lines.push(0),this.busy.push(!1);this.topMargin=(this.element.clientHeight-this.nLines*this.widget.lineHeight)/2;for(a=0;a<e;a++)b=c[a],
b.stop&&b.stop>d.begin&&this.renderEvent(b);for(a=e;a<h;a++)this.renderEvent(c[a]);this.overflows.forEach((a)=>{let b=this.widget.events.findIndex((b)=>b===a);-1<b&&this.widget.events.splice(b,1)})},renderNormalEvent:function(a){var b=this.band,c=b.index,d=this.content.range;let e=this.calcPos(a.start),h=this.widget.settings.locale,g,l;e||(e=0);e?(a.elements[c]?g=a.elements[c]:(g=document.createElement("div"),l=a.start.toLocaleString(h,this.band.helpers.loc),a.class&&(g.className=a.class),g.innerHTML=
this.widget.settings.formatter(a),g.dataset.id=a.id,a.stop?(l+=" ... "+a.stop.toLocaleString(h,this.band.helpers.loc),g.classList.add("d-tape-event"),g.prepend(createDiv$$module$utils("d-tape"))):g.classList.add("d-event"),g.title=l,this.widget.settings.url&&(["touchstart","touchend","mousedown"].forEach((a)=>{g.addEventListener(a,(a)=>{a.stopPropagation()})}),g.addEventListener("click",(b)=>{var c=this.widget.settings.url+b.target.dataset.id;this.widget.hilight(b.target);this.widget.settings.redirect?
window.location=c:(c=this.band.element.getBoundingClientRect(),this.widget.bubble.show({top:b.clientY-b.offsetY-c.y,left:b.clientX-b.offsetX-c.x}).setInfo(this.widget.settings.info(a)))})),a.elements[c]=g),setPixels$$module$utils(g,"left",e.left),setPixels$$module$utils(g,"top",e.line*this.widget.lineHeight+this.topMargin),a.stop&&(c=Math.max(a.start,d.begin),d=Math.min(a.stop,d.end),setPixels$$module$utils(g.firstChild,"width",Math.max(b.calcPixels(d-c),1)),a.post_start&&a.post_start>c&&setPixels$$module$utils(g.firstChild,
"borderLeftWidth",b.calcPixels(a.post_start-c)),a.pre_stop&&a.pre_stop<d&&setPixels$$module$utils(g.firstChild,"borderRightWidth",b.calcPixels(d-a.pre_stop))),this.element.append(g),b=window.getComputedStyle(g,":before"),b.getPropertyValue("width").startsWith("auto")||setPixels$$module$utils(g,"marginLeft",parseInt(b.getPropertyValue("width"),10)/-2),this.lines[e.line]=e.left+g.clientWidth,this.busy[e.line]=!0):(console.warn("Dateline overflow",a),this.overflows.push(a))},renderOverviewEvent:function(a){var b=
this.band.index;if(a.elements[b])var c=a.elements[b];else c=createDiv$$module$utils(a.stop?"d-tape-pin":"d-pin","did"+a.id),a.elements[b]=c;a.stop?(b=Math.max(a.start,this.content.range.begin),a=Math.min(a.stop,this.content.range.end),setPixels$$module$utils(c,"left",this.content.calcLeft(b)),setPixels$$module$utils(c,"width",Math.max(this.band.calcPixels(a-b),1))):setPixels$$module$utils(c,"left",this.content.calcLeft(a.start));this.element.append(c)},calcPos:function(a){a=this.content.calcLeft(a);
let b;for(b=0;b<this.nLines&&this.busy[b]&&!(a>=this.lines[b]);b++);return b>=this.nLines?!1:{left:a,line:b}}};var module$Events={};module$Events.default=Events$$module$Events;function Content$$module$Content(a){this.band=a;this.widget=a.widget;this.center=new Date(this.widget._cursor);this.range={begin:new Date,end:new Date};this.safe={begin:new Date,end:new Date};this.visible={begin:new Date,end:new Date};a=createDiv$$module$utils("d-content");this.markers=new Markers$$module$Markers(this);this.events=new Events$$module$Events(this);a.append(this.markers.element,this.events.element);this.element=a}
Content$$module$Content.prototype={render:function(){let a=this.widget;var b=this.range.begin;let c=this.range.end;this.markers.render();this.events.render();this.element.querySelectorAll(".d-limit").forEach((a)=>{a.remove()});if(a._begin&&a._begin>b&&a._begin<c){let b=createDiv$$module$utils("d-limit","d-begin");setPixels$$module$utils(b,"right",this.calcRight(a._begin));this.element.append(b)}a._end&&a._end>b&&a._end<c&&(b=createDiv$$module$utils("d-limit","d-end"),setPixels$$module$utils(b,"left",
this.calcLeft(a._end)),this.element.append(b))},setWidth:function(a){this.width=a;this.calcRange();setPixels$$module$utils(this.element,"width",a);this.place();this.render()},calcLeft:function(a){return this.band.calcPixels(a-this.range.begin)},calcRight:function(a){return this.band.calcPixels(this.range.end-a)},calcRange:function(){let a=this.center.getTime(),b=this.band.calcMs(this.width)/2,c=2*b/3;this.range.begin.setTime(a-b);this.range.end.setTime(a+b);this.safe.begin.setTime(a-c);this.safe.end.setTime(a+
c)},place:function(){var a=this.widget._cursor,b=this.widget.getWidth();if(a<this.safe.begin||a>this.safe.end)this.center.setTime(a.getTime()),this.calcRange(),this.render();setPixels$$module$utils(this.element,"left",this.band.calcPixels(this.center-a)-(this.width-b)/2);a=a.getTime();b=this.band.calcMs(b)/2;this.visible.begin.setTime(a-b);this.visible.end.setTime(a+b)}};var module$Content={};module$Content.default=Content$$module$Content;var defaultInstanceSettings$$module$anime_es={update:null,begin:null,loopBegin:null,changeBegin:null,change:null,changeComplete:null,loopComplete:null,complete:null,loop:1,direction:"normal",autoplay:!0,timelineOffset:0},defaultTweenSettings$$module$anime_es={duration:1E3,delay:0,endDelay:0,easing:"easeOutElastic(1, .5)",round:0},validTransforms$$module$anime_es="translateX translateY translateZ rotate rotateX rotateY rotateZ scale scaleX scaleY scaleZ skew skewX skewY perspective".split(" "),cache$$module$anime_es=
{CSS:{},springs:{}};function minMax$$module$anime_es(a,b,c){return Math.min(Math.max(a,b),c)}function stringContains$$module$anime_es(a,b){return-1<a.indexOf(b)}function applyArguments$$module$anime_es(a,b){return a.apply(null,b)}
var is$$module$anime_es={arr:function(a){return Array.isArray(a)},obj:function(a){return stringContains$$module$anime_es(Object.prototype.toString.call(a),"Object")},pth:function(a){return is$$module$anime_es.obj(a)&&a.hasOwnProperty("totalLength")},svg:function(a){return a instanceof SVGElement},inp:function(a){return a instanceof HTMLInputElement},dom:function(a){return a.nodeType||is$$module$anime_es.svg(a)},str:function(a){return"string"===typeof a},fnc:function(a){return"function"===typeof a},
und:function(a){return"undefined"===typeof a},hex:function(a){return/(^#[0-9A-F]{6}$)|(^#[0-9A-F]{3}$)/i.test(a)},rgb:function(a){return/^rgb/.test(a)},hsl:function(a){return/^hsl/.test(a)},col:function(a){return is$$module$anime_es.hex(a)||is$$module$anime_es.rgb(a)||is$$module$anime_es.hsl(a)},key:function(a){return!defaultInstanceSettings$$module$anime_es.hasOwnProperty(a)&&!defaultTweenSettings$$module$anime_es.hasOwnProperty(a)&&"targets"!==a&&"keyframes"!==a}};
function parseEasingParameters$$module$anime_es(a){return(a=/\(([^)]+)\)/.exec(a))?a[1].split(",").map(function(a){return parseFloat(a)}):[]}
function spring$$module$anime_es(a,b){function c(a){var c=b?b*a/1E3:a;c=1>k?Math.exp(-c*k*m)*(1*Math.cos(n*c)+p*Math.sin(n*c)):(1+p*c)*Math.exp(-c*m);return 0===a||1===a?a:1-c}function d(){var b=cache$$module$anime_es.springs[a];if(b)return b;b=1/6;for(var d=0,e=0;;)if(d+=b,1===c(d)){if(e++,16<=e)break}else e=0;b=d*b*1E3;return cache$$module$anime_es.springs[a]=b}var e=parseEasingParameters$$module$anime_es(a),h=minMax$$module$anime_es(is$$module$anime_es.und(e[0])?1:e[0],.1,100),g=minMax$$module$anime_es(is$$module$anime_es.und(e[1])?
100:e[1],.1,100),l=minMax$$module$anime_es(is$$module$anime_es.und(e[2])?10:e[2],.1,100);e=minMax$$module$anime_es(is$$module$anime_es.und(e[3])?0:e[3],.1,100);var m=Math.sqrt(g/h),k=l/(2*Math.sqrt(g*h)),n=1>k?m*Math.sqrt(1-k*k):0,p=1>k?(k*m+-e)/n:-e+m;return b?c:d}function steps$$module$anime_es(a){void 0===a&&(a=10);return function(b){return 1/a*Math.round(b*a)}}
var bezier$$module$anime_es=function(){function a(a,c,d){return(((1-3*d+3*c)*a+(3*d-6*c))*a+3*c)*a}return function(b,c,d,e){if(0<=b&&1>=b&&0<=d&&1>=d){var h=new Float32Array(11);if(b!==c||d!==e)for(var g=0;11>g;++g)h[g]=a(.1*g,b,d);return function(g){if(b===c&&d===e||0===g||1===g)return g;for(var l=0,k=1;10!==k&&h[k]<=g;++k)l+=.1;--k;k=l+(g-h[k])/(h[k+1]-h[k])*.1;var n=3*(1-3*d+3*b)*k*k+2*(3*d-6*b)*k+3*b;if(.001<=n){for(l=0;4>l;++l){n=3*(1-3*d+3*b)*k*k+2*(3*d-6*b)*k+3*b;if(0===n)break;var p=a(k,b,
d)-g;k-=p/n}g=k}else if(0===n)g=k;else{k=l;l+=.1;var r=0;do p=k+(l-k)/2,n=a(p,b,d)-g,0<n?l=p:k=p;while(1E-7<Math.abs(n)&&10>++r);g=p}return a(g,c,e)}}}}(),penner$$module$anime_es=function(){var a={linear:function(){return function(a){return a}}},b={Sine:function(){return function(a){return 1-Math.cos(a*Math.PI/2)}},Circ:function(){return function(a){return 1-Math.sqrt(1-a*a)}},Back:function(){return function(a){return a*a*(3*a-2)}},Bounce:function(){return function(a){for(var b,c=4;a<((b=Math.pow(2,
--c))-1)/11;);return 1/Math.pow(4,3-c)-7.5625*Math.pow((3*b-2)/22-a,2)}},Elastic:function(a,b){void 0===a&&(a=1);void 0===b&&(b=.5);var c=minMax$$module$anime_es(a,1,10),d=minMax$$module$anime_es(b,.1,2);return function(a){return 0===a||1===a?a:-c*Math.pow(2,10*(a-1))*Math.sin(2*(a-1-d/(2*Math.PI)*Math.asin(1/c))*Math.PI/d)}}};["Quad","Cubic","Quart","Quint","Expo"].forEach(function(a,d){b[a]=function(){return function(a){return Math.pow(a,d+2)}}});Object.keys(b).forEach(function(c){var d=b[c];a["easeIn"+
c]=d;a["easeOut"+c]=function(a,b){return function(c){return 1-d(a,b)(1-c)}};a["easeInOut"+c]=function(a,b){return function(c){return.5>c?d(a,b)(2*c)/2:1-d(a,b)(-2*c+2)/2}}});return a}();
function parseEasings$$module$anime_es(a,b){if(is$$module$anime_es.fnc(a))return a;var c=a.split("(")[0],d=penner$$module$anime_es[c],e=parseEasingParameters$$module$anime_es(a);switch(c){case "spring":return spring$$module$anime_es(a,b);case "cubicBezier":return applyArguments$$module$anime_es(bezier$$module$anime_es,e);case "steps":return applyArguments$$module$anime_es(steps$$module$anime_es,e);default:return applyArguments$$module$anime_es(d,e)}}
function selectString$$module$anime_es(a){try{return document.querySelectorAll(a)}catch(b){}}function filterArray$$module$anime_es(a,b){for(var c=a.length,d=2<=arguments.length?arguments[1]:void 0,e=[],h=0;h<c;h++)if(h in a){var g=a[h];b.call(d,g,h,a)&&e.push(g)}return e}function flattenArray$$module$anime_es(a){return a.reduce(function(a,c){return a.concat(is$$module$anime_es.arr(c)?flattenArray$$module$anime_es(c):c)},[])}
function toArray$$module$anime_es(a){if(is$$module$anime_es.arr(a))return a;is$$module$anime_es.str(a)&&(a=selectString$$module$anime_es(a)||a);return a instanceof NodeList||a instanceof HTMLCollection?[].slice.call(a):[a]}function arrayContains$$module$anime_es(a,b){return a.some(function(a){return a===b})}function cloneObject$$module$anime_es(a){var b={},c;for(c in a)b[c]=a[c];return b}
function replaceObjectProps$$module$anime_es(a,b){var c=cloneObject$$module$anime_es(a),d;for(d in a)c[d]=b.hasOwnProperty(d)?b[d]:a[d];return c}function mergeObjects$$module$anime_es(a,b){var c=cloneObject$$module$anime_es(a),d;for(d in b)c[d]=is$$module$anime_es.und(a[d])?b[d]:a[d];return c}function rgbToRgba$$module$anime_es(a){var b=/rgb\((\d+,\s*[\d]+,\s*[\d]+)\)/g.exec(a);return b?"rgba("+b[1]+",1)":a}
function hexToRgba$$module$anime_es(a){a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(a,b,c,g){return b+b+c+c+g+g});var b=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a);a=parseInt(b[1],16);var c=parseInt(b[2],16);b=parseInt(b[3],16);return"rgba("+a+","+c+","+b+",1)"}
function hslToRgba$$module$anime_es(a){function b(a,b,c){0>c&&(c+=1);1<c&&--c;return c<1/6?a+6*(b-a)*c:.5>c?b:c<2/3?a+(b-a)*(2/3-c)*6:a}var c=/hsl\((\d+),\s*([\d.]+)%,\s*([\d.]+)%\)/g.exec(a)||/hsla\((\d+),\s*([\d.]+)%,\s*([\d.]+)%,\s*([\d.]+)\)/g.exec(a);a=parseInt(c[1],10)/360;var d=parseInt(c[2],10)/100,e=parseInt(c[3],10)/100;c=c[4]||1;if(0==d)e=d=a=e;else{var h=.5>e?e*(1+d):e+d-e*d,g=2*e-h;e=b(g,h,a+1/3);d=b(g,h,a);a=b(g,h,a-1/3)}return"rgba("+255*e+","+255*d+","+255*a+","+c+")"}
function colorToRgb$$module$anime_es(a){if(is$$module$anime_es.rgb(a))return rgbToRgba$$module$anime_es(a);if(is$$module$anime_es.hex(a))return hexToRgba$$module$anime_es(a);if(is$$module$anime_es.hsl(a))return hslToRgba$$module$anime_es(a)}function getUnit$$module$anime_es(a){if(a=/[+-]?\d*\.?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?(%|px|pt|em|rem|in|cm|mm|ex|ch|pc|vw|vh|vmin|vmax|deg|rad|turn)?$/.exec(a))return a[1]}
function getTransformUnit$$module$anime_es(a){if(stringContains$$module$anime_es(a,"translate")||"perspective"===a)return"px";if(stringContains$$module$anime_es(a,"rotate")||stringContains$$module$anime_es(a,"skew"))return"deg"}function getFunctionValue$$module$anime_es(a,b){return is$$module$anime_es.fnc(a)?a(b.target,b.id,b.total):a}function getAttribute$$module$anime_es(a,b){return a.getAttribute(b)}
function convertPxToUnit$$module$anime_es(a,b,c){var d=getUnit$$module$anime_es(b);if(arrayContains$$module$anime_es([c,"deg","rad","turn"],d))return b;d=cache$$module$anime_es.CSS[b+c];if(!is$$module$anime_es.und(d))return d;d=document.createElement(a.tagName);a=a.parentNode&&a.parentNode!==document?a.parentNode:document.body;a.appendChild(d);d.style.position="absolute";d.style.width=100+c;var e=100/d.offsetWidth;a.removeChild(d);a=e*parseFloat(b);return cache$$module$anime_es.CSS[b+c]=a}
function getCSSValue$$module$anime_es(a,b,c){if(b in a.style){var d=b.replace(/([a-z])([A-Z])/g,"$1-$2").toLowerCase();b=a.style[b]||getComputedStyle(a).getPropertyValue(d)||"0";return c?convertPxToUnit$$module$anime_es(a,b,c):b}}
function getAnimationType$$module$anime_es(a,b){if(is$$module$anime_es.dom(a)&&!is$$module$anime_es.inp(a)&&(getAttribute$$module$anime_es(a,b)||is$$module$anime_es.svg(a)&&a[b]))return"attribute";if(is$$module$anime_es.dom(a)&&arrayContains$$module$anime_es(validTransforms$$module$anime_es,b))return"transform";if(is$$module$anime_es.dom(a)&&"transform"!==b&&getCSSValue$$module$anime_es(a,b))return"css";if(null!=a[b])return"object"}
function getElementTransforms$$module$anime_es(a){if(is$$module$anime_es.dom(a)){a=a.style.transform||"";for(var b=/(\w+)\(([^)]*)\)/g,c=new Map,d;d=b.exec(a);)c.set(d[1],d[2]);return c}}function getTransformValue$$module$anime_es(a,b,c,d){var e=stringContains$$module$anime_es(b,"scale")?1:0+getTransformUnit$$module$anime_es(b);e=getElementTransforms$$module$anime_es(a).get(b)||e;c&&(c.transforms.list.set(b,e),c.transforms.last=b);return d?convertPxToUnit$$module$anime_es(a,e,d):e}
function getOriginalTargetValue$$module$anime_es(a,b,c,d){switch(getAnimationType$$module$anime_es(a,b)){case "transform":return getTransformValue$$module$anime_es(a,b,d,c);case "css":return getCSSValue$$module$anime_es(a,b,c);case "attribute":return getAttribute$$module$anime_es(a,b);default:return a[b]||0}}
function getRelativeValue$$module$anime_es(a,b){var c=/^(\*=|\+=|-=)/.exec(a);if(!c)return a;var d=getUnit$$module$anime_es(a)||0;b=parseFloat(b);a=parseFloat(a.replace(c[0],""));switch(c[0][0]){case "+":return b+a+d;case "-":return b-a+d;case "*":return b*a+d}}function validateValue$$module$anime_es(a,b){if(is$$module$anime_es.col(a))return colorToRgb$$module$anime_es(a);if(/\s/g.test(a))return a;var c=getUnit$$module$anime_es(a);a=c?a.substr(0,a.length-c.length):a;return b?a+b:a}
function getDistance$$module$anime_es(a,b){return Math.sqrt(Math.pow(b.x-a.x,2)+Math.pow(b.y-a.y,2))}function getCircleLength$$module$anime_es(a){return 2*Math.PI*getAttribute$$module$anime_es(a,"r")}function getRectLength$$module$anime_es(a){return 2*getAttribute$$module$anime_es(a,"width")+2*getAttribute$$module$anime_es(a,"height")}
function getLineLength$$module$anime_es(a){return getDistance$$module$anime_es({x:getAttribute$$module$anime_es(a,"x1"),y:getAttribute$$module$anime_es(a,"y1")},{x:getAttribute$$module$anime_es(a,"x2"),y:getAttribute$$module$anime_es(a,"y2")})}function getPolylineLength$$module$anime_es(a){a=a.points;for(var b=0,c,d=0;d<a.numberOfItems;d++){var e=a.getItem(d);0<d&&(b+=getDistance$$module$anime_es(c,e));c=e}return b}
function getPolygonLength$$module$anime_es(a){var b=a.points;return getPolylineLength$$module$anime_es(a)+getDistance$$module$anime_es(b.getItem(b.numberOfItems-1),b.getItem(0))}
function getTotalLength$$module$anime_es(a){if(a.getTotalLength)return a.getTotalLength();switch(a.tagName.toLowerCase()){case "circle":return getCircleLength$$module$anime_es(a);case "rect":return getRectLength$$module$anime_es(a);case "line":return getLineLength$$module$anime_es(a);case "polyline":return getPolylineLength$$module$anime_es(a);case "polygon":return getPolygonLength$$module$anime_es(a)}}
function setDashoffset$$module$anime_es(a){var b=getTotalLength$$module$anime_es(a);a.setAttribute("stroke-dasharray",b);return b}function getParentSvgEl$$module$anime_es(a){for(a=a.parentNode;is$$module$anime_es.svg(a)&&is$$module$anime_es.svg(a.parentNode);)a=a.parentNode;return a}
function getParentSvg$$module$anime_es(a,b){b=b||{};a=b.el||getParentSvgEl$$module$anime_es(a);var c=a.getBoundingClientRect(),d=getAttribute$$module$anime_es(a,"viewBox"),e=c.width;c=c.height;b=b.viewBox||(d?d.split(" "):[0,0,e,c]);return{el:a,viewBox:b,x:b[0]/1,y:b[1]/1,w:e/b[2],h:c/b[3]}}
function getPath$$module$anime_es(a,b){var c=is$$module$anime_es.str(a)?selectString$$module$anime_es(a)[0]:a,d=b||100;return function(a){return{property:a,el:c,svg:getParentSvg$$module$anime_es(c),totalLength:getTotalLength$$module$anime_es(c)*(d/100)}}}
function getPathProgress$$module$anime_es(a,b){function c(c){void 0===c&&(c=0);return a.el.getPointAtLength(1<=b+c?b+c:0)}var d=getParentSvg$$module$anime_es(a.el,a.svg),e=c(),h=c(-1),g=c(1);switch(a.property){case "x":return(e.x-d.x)*d.w;case "y":return(e.y-d.y)*d.h;case "angle":return 180*Math.atan2(g.y-h.y,g.x-h.x)/Math.PI}}
function decomposeValue$$module$anime_es(a,b){var c=/[+-]?\d*\.?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?/g,d=validateValue$$module$anime_es(is$$module$anime_es.pth(a)?a.totalLength:a,b)+"";return{original:d,numbers:d.match(c)?d.match(c).map(Number):[0],strings:is$$module$anime_es.str(a)||b?d.split(c):[]}}
function parseTargets$$module$anime_es(a){a=a?flattenArray$$module$anime_es(is$$module$anime_es.arr(a)?a.map(toArray$$module$anime_es):toArray$$module$anime_es(a)):[];return filterArray$$module$anime_es(a,function(a,c,d){return d.indexOf(a)===c})}function getAnimatables$$module$anime_es(a){var b=parseTargets$$module$anime_es(a);return b.map(function(a,d){return{target:a,id:d,total:b.length,transforms:{list:getElementTransforms$$module$anime_es(a)}}})}
function normalizePropertyTweens$$module$anime_es(a,b){var c=cloneObject$$module$anime_es(b);/^spring/.test(c.easing)&&(c.duration=spring$$module$anime_es(c.easing));if(is$$module$anime_es.arr(a)){var d=a.length;2!==d||is$$module$anime_es.obj(a[0])?is$$module$anime_es.fnc(b.duration)||(c.duration=b.duration/d):a={value:a}}var e=is$$module$anime_es.arr(a)?a:[a];return e.map(function(a,c){a=is$$module$anime_es.obj(a)&&!is$$module$anime_es.pth(a)?a:{value:a};is$$module$anime_es.und(a.delay)&&(a.delay=
c?0:b.delay);is$$module$anime_es.und(a.endDelay)&&(a.endDelay=c===e.length-1?b.endDelay:0);return a}).map(function(a){return mergeObjects$$module$anime_es(a,c)})}
function flattenKeyframes$$module$anime_es(a){for(var b=filterArray$$module$anime_es(flattenArray$$module$anime_es(a.map(function(a){return Object.keys(a)})),function(a){return is$$module$anime_es.key(a)}).reduce(function(a,b){0>a.indexOf(b)&&a.push(b);return a},[]),c={},d=function(d){var e=b[d];c[e]=a.map(function(a){var b={},c;for(c in a)is$$module$anime_es.key(c)?c==e&&(b.value=a[c]):b[c]=a[c];return b})},e=0;e<b.length;e++)d(e);return c}
function getProperties$$module$anime_es(a,b){var c=[],d=b.keyframes;d&&(b=mergeObjects$$module$anime_es(flattenKeyframes$$module$anime_es(d),b));for(var e in b)is$$module$anime_es.key(e)&&c.push({name:e,tweens:normalizePropertyTweens$$module$anime_es(b[e],a)});return c}
function normalizeTweenValues$$module$anime_es(a,b){var c={},d;for(d in a){var e=getFunctionValue$$module$anime_es(a[d],b);is$$module$anime_es.arr(e)&&(e=e.map(function(a){return getFunctionValue$$module$anime_es(a,b)}),1===e.length&&(e=e[0]));c[d]=e}c.duration=parseFloat(c.duration);c.delay=parseFloat(c.delay);return c}
function normalizeTweens$$module$anime_es(a,b){var c;return a.tweens.map(function(d){d=normalizeTweenValues$$module$anime_es(d,b);var e=d.value,h=is$$module$anime_es.arr(e)?e[1]:e,g=getUnit$$module$anime_es(h),l=getOriginalTargetValue$$module$anime_es(b.target,a.name,g,b),m=c?c.to.original:l,k=is$$module$anime_es.arr(e)?e[0]:m;l=getUnit$$module$anime_es(k)||getUnit$$module$anime_es(l);g=g||l;is$$module$anime_es.und(h)&&(h=m);d.from=decomposeValue$$module$anime_es(k,g);d.to=decomposeValue$$module$anime_es(getRelativeValue$$module$anime_es(h,
k),g);d.start=c?c.end:0;d.end=d.start+d.delay+d.duration+d.endDelay;d.easing=parseEasings$$module$anime_es(d.easing,d.duration);d.isPath=is$$module$anime_es.pth(e);d.isColor=is$$module$anime_es.col(d.from.original);d.isColor&&(d.round=1);return c=d})}
var setProgressValue$$module$anime_es={css:function(a,b,c){return a.style[b]=c},attribute:function(a,b,c){return a.setAttribute(b,c)},object:function(a,b,c){return a[b]=c},transform:function(a,b,c,d,e){d.list.set(b,c);if(b===d.last||e){var h="";d.list.forEach(function(a,b){h+=b+"("+a+") "});a.style.transform=h}}};
function setTargetsValue$$module$anime_es(a,b){getAnimatables$$module$anime_es(a).forEach(function(a){for(var c in b){var e=getFunctionValue$$module$anime_es(b[c],a),h=a.target,g=getUnit$$module$anime_es(e),l=getOriginalTargetValue$$module$anime_es(h,c,g,a);g=g||getUnit$$module$anime_es(l);e=getRelativeValue$$module$anime_es(validateValue$$module$anime_es(e,g),l);l=getAnimationType$$module$anime_es(h,c);setProgressValue$$module$anime_es[l](h,c,e,a.transforms,!0)}})}
function createAnimation$$module$anime_es(a,b){var c=getAnimationType$$module$anime_es(a.target,b.name);if(c){var d=normalizeTweens$$module$anime_es(b,a),e=d[d.length-1];return{type:c,property:b.name,animatable:a,tweens:d,duration:e.end,delay:d[0].delay,endDelay:e.endDelay}}}
function getAnimations$$module$anime_es(a,b){return filterArray$$module$anime_es(flattenArray$$module$anime_es(a.map(function(a){return b.map(function(b){return createAnimation$$module$anime_es(a,b)})})),function(a){return!is$$module$anime_es.und(a)})}
function getInstanceTimings$$module$anime_es(a,b){var c=a.length,d={};d.duration=c?Math.max.apply(Math,a.map(function(a){return(a.timelineOffset?a.timelineOffset:0)+a.duration})):b.duration;d.delay=c?Math.min.apply(Math,a.map(function(a){return(a.timelineOffset?a.timelineOffset:0)+a.delay})):b.delay;d.endDelay=c?d.duration-Math.max.apply(Math,a.map(function(a){return(a.timelineOffset?a.timelineOffset:0)+a.duration-a.endDelay})):b.endDelay;return d}var instanceID$$module$anime_es=0;
function createNewInstance$$module$anime_es(a){var b=replaceObjectProps$$module$anime_es(defaultInstanceSettings$$module$anime_es,a),c=replaceObjectProps$$module$anime_es(defaultTweenSettings$$module$anime_es,a),d=getProperties$$module$anime_es(c,a);a=getAnimatables$$module$anime_es(a.targets);d=getAnimations$$module$anime_es(a,d);c=getInstanceTimings$$module$anime_es(d,c);var e=instanceID$$module$anime_es;instanceID$$module$anime_es++;return mergeObjects$$module$anime_es(b,{id:e,children:[],animatables:a,
animations:d,duration:c.duration,delay:c.delay,endDelay:c.endDelay})}
var activeInstances$$module$anime_es=[],pausedInstances$$module$anime_es=[],raf$$module$anime_es,engine$$module$anime_es=function(){function a(){raf$$module$anime_es=requestAnimationFrame(b)}function b(b){var c=activeInstances$$module$anime_es.length;if(c){for(var e=0;e<c;){var h=activeInstances$$module$anime_es[e];h.paused?(h=activeInstances$$module$anime_es.indexOf(h),-1<h&&(activeInstances$$module$anime_es.splice(h,1),c=activeInstances$$module$anime_es.length)):h.tick(b);e++}a()}else raf$$module$anime_es=
cancelAnimationFrame(raf$$module$anime_es)}return a}();function handleVisibilityChange$$module$anime_es(){document.hidden?(activeInstances$$module$anime_es.forEach(function(a){return a.pause()}),pausedInstances$$module$anime_es=activeInstances$$module$anime_es.slice(0),anime$$module$anime_es.running=activeInstances$$module$anime_es=[]):pausedInstances$$module$anime_es.forEach(function(a){return a.play()})}"undefined"!==typeof document&&document.addEventListener("visibilitychange",handleVisibilityChange$$module$anime_es);
function anime$$module$anime_es(a){function b(a){var b=window.Promise&&new Promise(function(a){return w=a});return a.finished=b}function c(){var a=f.direction;"alternate"!==a&&(f.direction="normal"!==a?"normal":"reverse");f.reversed=!f.reversed;p.forEach(function(a){return a.reversed=f.reversed})}function d(a){return f.reversed?f.duration-a:a}function e(){m=0;k=d(f.currentTime)*(1/anime$$module$anime_es.speed)}function h(a){for(var b=0,c=f.animations,d=c.length;b<d;){var e=c[b],g=e.animatable,h=e.tweens,
l=h.length-1,k=h[l];l&&(k=filterArray$$module$anime_es(h,function(b){return a<b.end})[0]||k);h=minMax$$module$anime_es(a-k.start-k.delay,0,k.duration)/k.duration;var q=isNaN(h)?1:k.easing(h);h=k.to.strings;var n=k.round;l=[];var p=k.to.numbers.length,m=void 0;for(m=0;m<p;m++){var r=void 0;r=k.to.numbers[m];var w=k.from.numbers[m]||0;r=k.isPath?getPathProgress$$module$anime_es(k.value,q*r):w+q*(r-w);n&&(k.isColor&&2<m||(r=Math.round(r*n)/n));l.push(r)}if(k=h.length)for(m=h[0],q=0;q<k;q++)n=h[q+1],
p=l[q],isNaN(p)||(m=n?m+(p+n):m+(p+" "));else m=l[0];setProgressValue$$module$anime_es[e.type](g.target,e.property,m,g.transforms);e.currentValue=m;b++}}function g(a){if(f[a]&&!f.passThrough)f[a](f)}function l(a){var e=f.duration,l=f.delay,q=e-f.endDelay,t=d(a);f.progress=minMax$$module$anime_es(t/e*100,0,100);f.reversePlayback=t<f.currentTime;if(p)if(f.reversePlayback)for(var u=r;u--;){var v=p[u];v&&v.seek(t-v.timelineOffset)}else for(u=0;u<r;u++)(v=p[u])&&v.seek(t-v.timelineOffset);!f.began&&0<
f.currentTime&&(f.began=!0,g("begin"));!f.loopBegan&&0<f.currentTime&&(f.loopBegan=!0,g("loopBegin"));t<=l&&0!==f.currentTime&&h(0);(t>=q&&f.currentTime!==e||!e)&&h(e);t>l&&t<q?(f.changeBegan||(f.changeBegan=!0,f.changeCompleted=!1,g("changeBegin")),g("change"),h(t)):f.changeBegan&&(f.changeCompleted=!0,f.changeBegan=!1,g("changeComplete"));f.currentTime=minMax$$module$anime_es(t,0,e);f.began&&g("update");a>=e&&(k=0,f.remaining&&!0!==f.remaining&&f.remaining--,f.remaining?(m=n,g("loopComplete"),f.loopBegan=
!1,"alternate"===f.direction&&c()):(f.paused=!0,f.completed||(f.completed=!0,g("loopComplete"),g("complete"),!f.passThrough&&"Promise"in window&&(w(),b(f)))))}void 0===a&&(a={});var m=0,k=0,n=0,p,r=0,w=null,f=createNewInstance$$module$anime_es(a);b(f);f.reset=function(){var a=f.direction;f.passThrough=!1;f.currentTime=0;f.progress=0;f.paused=!0;f.began=!1;f.loopBegan=!1;f.changeBegan=!1;f.completed=!1;f.changeCompleted=!1;f.reversePlayback=!1;f.reversed="reverse"===a;f.remaining=f.loop;p=f.children;
for(var b=r=p.length;b--;)f.children[b].reset();(f.reversed&&!0!==f.loop||"alternate"===a&&1===f.loop)&&f.remaining++;h(f.reversed?f.duration:0)};f.set=function(a,b){setTargetsValue$$module$anime_es(a,b);return f};f.tick=function(a){n=a;m||(m=n);l((n+(k-m))*anime$$module$anime_es.speed)};f.seek=function(a){l(d(a))};f.pause=function(){f.paused=!0;e()};f.play=function(){f.paused&&(f.completed&&f.reset(),f.paused=!1,activeInstances$$module$anime_es.push(f),e(),raf$$module$anime_es||engine$$module$anime_es())};
f.reverse=function(){c();e()};f.restart=function(){f.reset();f.play()};f.reset();f.autoplay&&f.play();return f}function removeTargetsFromAnimations$$module$anime_es(a,b){for(var c=b.length;c--;)arrayContains$$module$anime_es(a,b[c].animatable.target)&&b.splice(c,1)}
function removeTargets$$module$anime_es(a){a=parseTargets$$module$anime_es(a);for(var b=activeInstances$$module$anime_es.length;b--;){var c=activeInstances$$module$anime_es[b],d=c.animations,e=c.children;removeTargetsFromAnimations$$module$anime_es(a,d);for(var h=e.length;h--;){var g=e[h],l=g.animations;removeTargetsFromAnimations$$module$anime_es(a,l);l.length||g.children.length||e.splice(h,1)}d.length||e.length||c.pause()}}
function stagger$$module$anime_es(a,b){void 0===b&&(b={});var c=b.direction||"normal",d=b.easing?parseEasings$$module$anime_es(b.easing):null,e=b.grid,h=b.axis,g=b.from||0,l="first"===g,m="center"===g,k="last"===g,n=is$$module$anime_es.arr(a),p=n?parseFloat(a[0]):parseFloat(a),r=n?parseFloat(a[1]):0,w=getUnit$$module$anime_es(n?a[1]:a)||0,f=b.start||0+(n?p:0),q=[],x=0;return function(a,b,t){l&&(g=0);m&&(g=(t-1)/2);k&&(g=t-1);if(!q.length){for(a=0;a<t;a++){if(e){var u=(m?(e[0]-1)/2:g%e[0])-a%e[0],
v=(m?(e[1]-1)/2:Math.floor(g/e[0]))-Math.floor(a/e[0]),y=Math.sqrt(u*u+v*v);"x"===h&&(y=-u);"y"===h&&(y=-v);q.push(y)}else q.push(Math.abs(g-a));x=Math.max.apply(Math,q)}d&&(q=q.map(function(a){return d(a/x)*x}));"reverse"===c&&(q=q.map(function(a){return h?0>a?-1*a:-a:Math.abs(x-a)}))}return f+Math.round(100*q[b])/100*(n?(r-p)/x:p)+w}}
function timeline$$module$anime_es(a){void 0===a&&(a={});var b=anime$$module$anime_es(a);b.duration=0;b.add=function(c,d){var e=activeInstances$$module$anime_es.indexOf(b),h=b.children;-1<e&&activeInstances$$module$anime_es.splice(e,1);for(e=0;e<h.length;e++)h[e].passThrough=!0;c=mergeObjects$$module$anime_es(c,replaceObjectProps$$module$anime_es(defaultTweenSettings$$module$anime_es,a));c.targets=c.targets||a.targets;e=b.duration;c.autoplay=!1;c.direction=b.direction;c.timelineOffset=is$$module$anime_es.und(d)?
e:getRelativeValue$$module$anime_es(d,e);b.passThrough=!0;b.seek(c.timelineOffset);d=anime$$module$anime_es(c);d.passThrough=!0;h.push(d);h=getInstanceTimings$$module$anime_es(h,a);b.delay=h.delay;b.endDelay=h.endDelay;b.duration=h.duration;b.seek(0);b.reset();b.autoplay&&b.play();return b};return b}anime$$module$anime_es.version="3.1.0";anime$$module$anime_es.speed=1;anime$$module$anime_es.running=activeInstances$$module$anime_es;anime$$module$anime_es.remove=removeTargets$$module$anime_es;
anime$$module$anime_es.get=getOriginalTargetValue$$module$anime_es;anime$$module$anime_es.set=setTargetsValue$$module$anime_es;anime$$module$anime_es.convertPx=convertPxToUnit$$module$anime_es;anime$$module$anime_es.path=getPath$$module$anime_es;anime$$module$anime_es.setDashoffset=setDashoffset$$module$anime_es;anime$$module$anime_es.stagger=stagger$$module$anime_es;anime$$module$anime_es.timeline=timeline$$module$anime_es;anime$$module$anime_es.easing=parseEasings$$module$anime_es;
anime$$module$anime_es.penner=penner$$module$anime_es;anime$$module$anime_es.random=function(a,b){return Math.floor(Math.random()*(b-a+1))+a};var $jscompDefaultExport$$module$anime_es=anime$$module$anime_es,module$anime_es={};module$anime_es.default=$jscompDefaultExport$$module$anime_es;const hlprs$$module$Band=[{ms:1,big:10,loc:{hour:"2-digit",minute:"2-digit",second:"2-digit"},floor:function(a,b){let c=a.getMilliseconds();a.setMilliseconds(c-c%b)},incr:function(a,b){a.setMilliseconds(a.getMilliseconds()+b)}},{ms:1E3,big:10,loc:{hour:"2-digit",minute:"2-digit",second:"2-digit"},floor:function(a,b){let c=a.getSeconds();a.setSeconds(c-c%b,0)},incr:function(a,b){a.setSeconds(a.getSeconds()+b,0)}},{ms:6E4,big:10,loc:{hour:"2-digit",minute:"2-digit",second:"2-digit"},floor:function(a,
b){let c=a.getMinutes();a.setMinutes(c-c%b,0,0)},incr:function(a,b){a.setMinutes(a.getMinutes()+b,0,0)}},{ms:36E5,big:10,loc:{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"},floor:function(a,b){let c=a.getHours();a.setHours(c-c%b,0,0,0)},incr:function(a,b){a.setHours(a.getHours()+b,0,0,0)}},{ms:864E5,big:7,loc:{year:"numeric",month:"numeric",day:"numeric",hour:"2-digit"},floor:function(a,b){let c=a.getTime()/864E5;a.setTime(864E5*(c-c%b));a.setHours(0,0,0,0)},incr:function(a,b){a.setDate(a.getDate()+
b)}},{ms:6048E5,big:10,loc:{year:"numeric",month:"long",day:"numeric"},floor:function(a,b){let c=a.getTime();c=(c-3456E5)/6048E5;a.setTime(6048E5*(c-c%b));a.setHours(0,0,0,0)},incr:function(a,b){a.setDate(a.getDate()+7*b)}},{ms:2629743750,big:12,loc:{year:"numeric",month:"long",day:"numeric"},floor:function(a,b){let c=a.getMonth();a.setMonth(c-c%b,1);a.setHours(0,0,0,0)},incr:function(a,b){a.setMonth(a.getMonth()+b,1)}},{ms:31556925E3,big:10,loc:{year:"numeric",month:"long",day:"numeric"},floor:function(a,
b){let c=a.getFullYear();a.setFullYear(c-c%b,0,1);a.setHours(0,0,0,0)},incr:function(a,b){a.setFullYear(a.getFullYear()+b,0,1)}},{ms:31556925E4,big:10,loc:{year:"numeric",month:"long",day:"numeric"},floor:function(a,b){let c=a.getFullYear();a.setFullYear(c-c%(10*b),0,1);a.setHours(0,0,0,0)},incr:function(a,b){a.setFullYear(a.getFullYear()+10*b,0,1)}},{ms:31556925E5,big:10,loc:{year:"numeric",month:"numeric"},floor:function(a,b){let c=a.getFullYear();a.setFullYear(c-c%(100*b),0,1);a.setHours(0,0,0,
0)},incr:function(a,b){a.setFullYear(a.getFullYear()+100*b,0,1)}},{ms:31556925E6,big:10,loc:{year:"numeric",month:"numeric"},floor:function(a,b){let c=a.getFullYear();a.setFullYear(c-c%(1E3*b),0,1);a.setHours(0,0,0,0)},incr:function(a,b){a.setFullYear(a.getFullYear()+1E3*b,0,1)}}];let scope$$module$Band,clientX$$module$Band,clientY$$module$Band,touchId$$module$Band,posX$$module$Band,velo$$module$Band,timeStamp$$module$Band,animation$$module$Band=0;
const inertia$$module$Band=500,slow$$module$Band=.1,duration$$module$Band=1500,nervous$$module$Band=.6;function getTouch$$module$Band(a){for(let b=0;b<a.changedTouches.length;b++)if(a.changedTouches[b].identifier===touchId$$module$Band)return a.changedTouches[b];return null}
function onTouchMove$$module$Band(a){a.preventDefault();var b=getTouch$$module$Band(a);b&&(b=b.clientX,scope$$module$Band.move(b-posX$$module$Band),velo$$module$Band*=1-nervous$$module$Band,velo$$module$Band+=(b-posX$$module$Band)/(a.timeStamp-timeStamp$$module$Band)*nervous$$module$Band,posX$$module$Band=b,timeStamp$$module$Band=a.timeStamp)}function onTouchCancel$$module$Band(a){a.preventDefault();touchId$$module$Band=void 0}
function onTouchEnd$$module$Band(a){a.preventDefault();a=getTouch$$module$Band(a);touchId$$module$Band=void 0;a&&(Math.abs(velo$$module$Band)>slow$$module$Band?(posX$$module$Band=0,animation$$module$Band=$jscompDefaultExport$$module$anime_es({targets:{x:0},x:velo$$module$Band*inertia$$module$Band,duration:duration$$module$Band,easing:"easeOutExpo",update:(a)=>{a=a.animations[0].currentValue;scope$$module$Band.move(a-posX$$module$Band);posX$$module$Band=a},complete:(a)=>{animation$$module$Band=0;scope$$module$Band.endDrag()}})):
4>Math.abs(a.clientX-clientX$$module$Band)&&4>Math.abs(a.clientY-clientY$$module$Band)?scope$$module$Band.click(a.clientX):scope$$module$Band.endDrag())}
function onTouchStart$$module$Band(a){a.preventDefault();void 0===touchId$$module$Band&&(animation$$module$Band&&(animation$$module$Band.pause(),animation$$module$Band=0),touchId$$module$Band=a.changedTouches[0].identifier,posX$$module$Band=clientX$$module$Band=a.changedTouches[0].clientX,clientY$$module$Band=a.changedTouches[0].clientY,timeStamp$$module$Band=a.timeStamp,velo$$module$Band=0)}function onMouseMove$$module$Band(a){a.preventDefault();scope$$module$Band.move(a.movementX)}
function onMouseUp$$module$Band(a){4>Math.abs(a.clientX-clientX$$module$Band)&&4>Math.abs(a.clientY-clientY$$module$Band)?scope$$module$Band.click(a.clientX):scope$$module$Band.endDrag();document.removeEventListener("mousemove",onMouseMove$$module$Band,!1);document.removeEventListener("mouseup",onMouseUp$$module$Band,!1)}
function onMouseDown$$module$Band(a){clientX$$module$Band=a.clientX;clientY$$module$Band=a.clientY;document.addEventListener("mousemove",onMouseMove$$module$Band,!1);document.addEventListener("mouseup",onMouseUp$$module$Band,!1)}
function Band$$module$Band(a,b,c){this.widget=a;this.index=c;Object.assign(this,{multiple:1},b);this.helpers=hlprs$$module$Band[this.scale];this.before=createDiv$$module$utils("d-range","d-before");this.after=createDiv$$module$utils("d-range","d-after");this.leftIndicator=createDiv$$module$utils("d-indicator","d-left","d-hidden");this.leftIndicator.addEventListener("mousedown",(a)=>{this.stepLeft(a.shiftKey);a.preventDefault()});this.rightIndicator=createDiv$$module$utils("d-indicator","d-right",
"d-hidden");this.rightIndicator.addEventListener("mousedown",(a)=>{this.stepRight(a.shiftKey);a.preventDefault()});this.content=new Content$$module$Content(this);a=createDiv$$module$utils("d-band","d-band-"+c,"d-scale-"+this.scale);a.setAttribute("tabindex","0");a.style.height=this.size;a.append(this.before,this.after,this.content.element,this.leftIndicator,this.rightIndicator);a.addEventListener("touchstart",(a)=>{this.focus();onTouchStart$$module$Band(a)},!1);a.addEventListener("touchmove",onTouchMove$$module$Band,
!1);a.addEventListener("touchend",onTouchEnd$$module$Band,!1);a.addEventListener("touchcancel",onTouchCancel$$module$Band,!1);a.addEventListener("mousedown",onMouseDown$$module$Band,!1);a.addEventListener("focus",(a)=>{showElement$$module$utils(this.leftIndicator,this.rightIndicator);this.widget.focus=this.index;this.focus()});a.addEventListener("blur",(a)=>{hideElement$$module$utils(this.leftIndicator,this.rightIndicator)});a.addEventListener("keydown",(a)=>{var b=this.widget;let c=!0;switch(a.key){case "Tab":let d=
b.events,e;a.shiftKey?(e=d.binInsertPosOf({start:b.getMs()-1}),b=0<e?d[e-1].start:b._begin):(e=d.binInsertPosOf({start:b.getMs()+1}),b=e<d.length?d[e].start:b._end);b&&this.animateTo(b.getTime());break;case "PageUp":this.stepRight(!0);break;case "PageDown":this.stepLeft(!0);break;case "End":b._end&&this.animateTo(b._end.getTime());break;case "Home":b._begin&&this.animateTo(b._begin.getTime());break;case "ArrowLeft":this.stepLeft(a.shiftKey);break;case "ArrowUp":b.cycleFocus(-1);break;case "ArrowRight":this.stepRight(a.shiftKey);
break;case "ArrowDown":b.cycleFocus(1);break;default:c=!1}c&&(a.preventDefault(),a.stopPropagation())});this.element=a}
Band$$module$Band.prototype={setWidth:function(a){this.content.setWidth(a)},place:function(){this.content.place()},setFocus:function(){this.element.focus()},setRange:function(a){let b=this.widget._cursor;a?(setPixels$$module$utils(this.before,"width",this.calcPixels(b-a.begin)),setPixels$$module$utils(this.after,"width",this.calcPixels(a.end-b))):(this.before.style.width=null,this.after.style.width=null)},setRangeFrom:function(a){this.setRange(a.content.visible)},calcPixels:function(a){return+(Math.round(a*
this.interval/this.helpers.ms+"e+3")+"e-3")},calcMs:function(a){return a*this.helpers.ms/this.interval},stepLeft:function(a){this.animateTo(this.widget.getMs()-(a?this.helpers.big:1)*this.helpers.ms)},stepRight:function(a){this.animateTo(this.widget.getMs()+(a?this.helpers.big:1)*this.helpers.ms)},floorDate:function(a){this.helpers.floor(a,this.multiple)},ceilDate:function(a){this.helpers.floor(a,this.multiple);this.helpers.incr(a,this.multiple)},incrDate:function(a){this.helpers.incr(a,this.multiple)},
animateTo:function(a){let b=this.calcPixels(Math.abs(this.widget.getMs()-a));this.widget.animateTo(a,100*Math.log(b))},focus:function(){scope$$module$Band=this},move(a){this.widget.place(this.widget.getMs()-this.calcMs(a))},endDrag:function(){this.widget.triggerChange()},click:function(a){let b=this.element.getBoundingClientRect();this.animateTo(this.content.visible.begin.getTime()+this.calcMs(a-b.x))}};var module$Band={};module$Band.default=Band$$module$Band;function Bubble$$module$Bubble(a){this.widget=a;this.info=createDiv$$module$utils("d-info");a=createDiv$$module$utils("d-bubble","d-hidden");let b=createDiv$$module$utils("d-close");b.innerHTML="&times;";b.addEventListener("click",(a)=>{this.hide()});a.append(b,this.info);this.element=a}
Bubble$$module$Bubble.prototype={show:function(a){showElement$$module$utils(this.element);setPixels$$module$utils(this.element,"left",a.left);setPixels$$module$utils(this.element,"top",a.top);return this},hide:function(){hideElement$$module$utils(this.element);this.widget.clearHilight();return this},setInfo:function(a){this.info.innerHTML=a;return this}};var module$Bubble={};module$Bubble.default=Bubble$$module$Bubble;class SortedArray$$module$SortedArray extends Array{constructor(a,...b){super();Object.defineProperty(this,"compare",{value:a});this.insert(...b)}_binarySearch(a){let b=-1,c=this.length;for(;1+b<c;){const d=b+(c-b>>1);a(this[d])?c=d:b=d}return c}binIndexOf(a){let b=this._binarySearch((b)=>0>=this.compare(a,b));return b>=this.length||this.compare(a,this[b])?-1:b}binInsertPosOf(a){return this._binarySearch((b)=>0>=this.compare(a,b))}binFind(a){let b=this._binarySearch((b)=>0>=this.compare(a,b)),c=this[b];
return b>=this.length||this.compare(a,c)?void 0:c}insert(...a){a.forEach((a)=>{let b=this._binarySearch((b)=>0>=this.compare(a,b));this.splice(b,0,a)})}}var module$SortedArray={};module$SortedArray.default=SortedArray$$module$SortedArray;const MILLISECOND$$module$index=0,SECOND$$module$index=1,MINUTE$$module$index=2,HOUR$$module$index=3,DAY$$module$index=4,WEEK$$module$index=5,MONTH$$module$index=6,YEAR$$module$index=7,DECADE$$module$index=8,CENTURY$$module$index=9,MILLENNIUM$$module$index=10,defaults$$module$index={size:"320px",bands:[{size:"100%",scale:MONTH$$module$index,interval:60}],cursor:new Date,rememberCursor:!0,begin:null,end:null,events:[],redirect:!1,url:!1,loading:"Loading&hellip;",scrollFactor:5,locale:"default"};
function Widget$$module$index(a,b){this.id=a;this.settings=Object.assign({},defaults$$module$index,b);["begin","end","cursor"].forEach((a)=>{this.settings[a]&&(this["_"+a]=createDate$$module$utils(this.settings[a]))});a=document.getElementById(a);a.classList.add("d-dateline");a.setAttribute("tabindex","0");a.style.height=this.settings.size;b=window.getComputedStyle(a);this.lineHeight=
parseInt(b.getPropertyValue("line-height"),10);this.inner=createDiv$$module$utils("d-inner");this.bubble=(new Bubble$$module$Bubble(this)).setInfo("Bubble");a.append(this.inner,this.bubble.element);this.element=a;this.focus=0;this.prepareBands();this.prepareEvents();this.setWidth();this._intval=this._hilight=null;this._busy=!1;Object.defineProperty(this,"cursor",{get(){return new Date(this._cursor)},set(a){this.animateTo(createDate$$module$utils(a).getTime())},enumerable:!0,configurable:!0})}
Widget$$module$index.prototype={prepareBands:function(){var a=this.settings.bands;a.length||(this.inner.innerHTML="No bands defined.");this.bands=a.map(function(a,c,d){a=new Band$$module$Band(this,a,c);this.inner.append(a.element);return a},this)},prepareEvents:function(){this.events=new SortedArray$$module$SortedArray((a,b)=>a.start>b.start);this.settings.events.forEach((a)=>{["start","stop","post_start","pre_stop"].forEach((b)=>{a[b]&&(a[b]=createDate$$module$utils(a[b]))});a.elements=[];this.events.insert(a)})},
getWidth:function(){return this.element.clientWidth},setWidth:function(){let a=this.element.clientWidth*this.settings.scrollFactor;this.bands.forEach(function(b){b.setWidth(a)});this.sync()},place:function(a){let b;this.bubble.hide();this._begin&&a<(b=this._begin.getTime())&&(a=b);this._end&&a>(b=this._end.getTime())&&(a=b);this._cursor.setTime(a);this.bands.forEach((a)=>{a.content.place()});this.sync()},animateTo:function(a,b){if(!this._busy){this._busy=!0;let c={cursor:this.getMs()},d;this._begin&&
a<(d=this._begin.getTime())&&(a=d);this._end&&a>(d=this._end.getTime())&&(a=d);$jscompDefaultExport$$module$anime_es({targets:c,cursor:a,duration:b||800,easing:"easeInOutCubic",update:(a)=>{this.place(c.cursor)},complete:(a)=>{this._busy=!1;this.triggerChange()}})}},getMs:function(){return this._cursor.getTime()},sync:function(){let a;this.bands.forEach((b)=>{a&&b.setRangeFrom(a);a=b})},cycleFocus:function(a){var b=this.bands.length,c=this.focus;this.bands[(c+(b+a))%b].setFocus()},hilight:function(a){this.clearHilight();
this._hilight=a;a.classList.add("d-hilight");this._intval=window.setInterval((a)=>{a._hilight.classList.toggle("d-hilight")},500,this)},clearHilight:function(){this._intval&&(window.clearInterval(this._intval),this._intval=null);this._hilight&&(this._hilight.classList.remove("d-hilight"),this._hilight=null)},triggerChange:function(){this.element.dispatchEvent(new CustomEvent("datelinechange",{bubbles:!0,detail:new Date(this._cursor)}));},
find:function(a){let b=this.events.find((b)=>b.id==a);b&&this.animateTo(b.start.getTime());return b}};window.dateline=function(a,b){return new Widget$$module$index(a,b)};var module$index={};module$index.MILLISECOND=MILLISECOND$$module$index;module$index.SECOND=SECOND$$module$index;module$index.MINUTE=MINUTE$$module$index;module$index.HOUR=HOUR$$module$index;module$index.DAY=DAY$$module$index;module$index.WEEK=WEEK$$module$index;module$index.MONTH=MONTH$$module$index;module$index.YEAR=YEAR$$module$index;
module$index.DECADE=DECADE$$module$index;module$index.CENTURY=CENTURY$$module$index;module$index.MILLENNIUM=MILLENNIUM$$module$index;module$index.Widget=Widget$$module$index;
