const BATAILLE=0,SIEGE=1,CHEVAUCHEE=2,TRAITE=3,CROISADE=4,REVOLTE=5;
const COULEUR_BATAILLES=["col-blue","col-yellow","col-red","col-green","col-red","col-black"];

class Evenement {
    static el() {
        return [{start:"1297-09-11",etext:"Battle of Stirling Bridge",text:"Bataille du Pont de Stirling", victoire:ECOSSAIS,desc:"La bataille du pont de Stirling constitua une des batailles des guerres d’indépendance de l’Écosse. Le 11 septembre 1297, les armées d'Andrew de Moray et de William Wallace affrontèrent celles de John de Warenne, 6e comte de Surrey, leur infligeant une défaite.",edesc:"The Battle of Stirling Bridge was one of the battles of the Scottish Wars of Independence. On September 11, 1297, the armies of Andrew de Moray and William Wallace faced and defeated the armies of John de Warenne, 6th Earl of Surrey.",flag:[ECOSSAIS,ANGLAIS],commandants:["Wallace"],wiki:"Bataille_du_pont_de_Stirling",campagne:"Guerre d'indépendance de l'Ecosse"},
                {start:"1298-07",text:"Bataille de Falkirk", flag:[ECOSSAIS,ANGLAIS],desc:"La bataille de Falkirk, qui eut lieu en juillet 1298, marqua la fin de l'épopée de William Wallace lors de la Première Guerre d'indépendance de l'Écosse.",victoire:ANGLAIS,commandants:["Wallace"],edesc:"The Battle of Falkirk, which took place in July 1298, marked the end of William Wallace's saga in the First Scottish War of Independence.",campagne:"Guerre d'indépendance de l'Ecosse",wiki:"Bataille_de_Falkirk_(1298)"},
                {start:"1327-01-25",etext:"Edward III reigns",text:"Début du règne d'Edouard III",flag:[ANGLAIS]},
                {start:"1339-10",stop:"1339-11",etext:"Siege of Cambrai",text:"Siège de Cambrai",flag:[FRANCAIS,ANGLAIS],commandants:["Edouard III","Magnanime"],desc:"Cambrai résista à tous les assauts des Anglais pendant 2 semaines. Les forces anglaises se retirèrent quand l'armée de soutien de Philippe VI arriva.",wiki:"Si%C3%A8ge_de_Cambrai_(1339)",campagne:"Chevauchée d'Edouard III",edesc:"Cambrai withstood all English assaults for 2 weeks. The English forces withdrew when the support army of Philippe VI arrived."},
                {start:"1340-05-24",etext:"Battle of Sluys",text:"Bataille de l'Ecluse",flag:[FRANCAIS,ANGLAIS],desc:"Une bataille navale où la flotte anglaise écrasa la flotte française.",edesc:"A naval battle in which the English fleet crushed the French fleet.",victoire:ANGLAIS,wiki:"Bataille_de_L%27%C3%89cluse_(1340)",campagne:"Chevauchée d'Edouard III"},
                {start:"1340-07-23",stop:"1340-09-25",etext:"Siege of Tournai",text:"Siège de Tournai", edesc:"Edward III laid siege to Tournai, Philippe VI approached with a powerful army. Jeanne de Valois, Edward's mother-in-law and Philip's sister-in-law, negotiated a truce and everyone returned home.",flag:[FRANCAIS,ANGLAIS],commandants:["Edouard III","Philippe VI de Valois","Charles II"],desc:"Edouard III assiègeait Tournai, Philippe VI approcha avec une puissante armée. Jeanne de Valois, la belle-mère d'Edouard et soeur de Philippe, négocia une trève et chacun retourna en son pays.",wiki:"Si%C3%A8ge_de_Tournai_(1340)",campagne:"Chevauchée d'Edouard III"},
                {start:"1340-07-26",text:"Bataille de Saint-Omer",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,desc:"The rearguard and baggage of the Anglo-Flemish army were massacred by the French in front of Saint-Omer.",campagne:"Chevauchée d'Edouard III",desc:"L'arrière garde et les bagages de l'armée anglo-flamande furent massacrés devant Saint-Omer par les Français.",wiki:"Bataille_de_Saint-Omer_(1340)"},
                {start:"1341-10-14",text:"Bataille de Champtoceaux", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:FRANCAIS,desc:"La bataille inaugura le conflit dynastique en Bretagne, opposant Charles de Blois à Jean de Montfort, soutenu par les Anglais. Les deux rivaux s'opposèrent pendant 2 jours près d'une ferme et finalement Jean de Montfort s'enfuit à Nantes.",commandants:["Brienne"],wiki:"Bataille_de_Champtoceaux",edesc:"The battle inaugurated the dynastic conflict in Brittany between Charles de Blois and Jean de Montfort, supported by the English. The two rivals opposed each other for two days near a farm and finally Jean de Montfort fled to Nantes."},
                {start:"1342-04",text:"Bataille de Quimperlé", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:ANGLAIS,desc:"Louis de la Cerda , commandant de l'armée de Charles de Blois de 6000 hommes, rencontra 3000 archers anglais. Les premiers finirent par fuir.",wiki:"Bataille_de_Quimperl%C3%A9",edesc:"Louis de la Cerda, commander of Charles de Blois' army of 6000 men, met 3000 English archers. The first ones eventually fled."},
                {start:"1342-05",start:"1342-06",text:"Siège d'Hennebont", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:ANGLAIS,wiki:"Si%C3%A8ge_d%27Hennebont",desc:"Les troupes montfortistes firet le siège d'Hennebont, dans laquelle était Jeanne de Flandre, mère de Jean de Montfort. Grace à des ruses, Jeanne parvint à sortir de la ville et revint avec des renforts. Le siège fut levé par la suite.",edesc:"Montfortist troops laid siege to Hennebont, where Jeanne de Flandre, mother of Jean de Montfort. Through trickery, Jeanne managed to get out of the city and returned with reinforcements. The siege was later lifted."},
                {start:"1342-12-05",stop:"1343-01-19",text:"Siège de Vannes",flag:[FRANCAIS,ANGLAIS,BIEN],victoire:BIEN,campagne:"Guerre de succession de Bretagne",commandants:["Edouard III","Salisbury"],desc:"Quatre sièges successifs et la ville fut remise aux légats du pape, après intervention du pape Clément VI",wiki:"Si%C3%A8ges_de_Vannes_(1342)",edesc:"Four successive sieges and the city was handed over to the Pope's legates, after the intervention of Pope Clement VI."},
                {start:"1342-09-19",text:"Bataille de Morlaix", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:FRANCAIS,commandants:["Northampton"],wiki:"Bataille_de_Morlaix",desc:"Northampton, assiegeant Morlaix, intercepta l'armée Francaise-Bretonne de Charles de Blois qui venait libérer la ville. La victoire fut française.",edesc:"Northampton, laying siege to Morlaix, intercepted the French-Bretonne army of Charles de Blois who was coming to liberate the city. The victory was French."},
                {start:"1345-06-17",text:"Bataille de Cadoret", campagne:"Guerre de succession de Bretagne",wiki:"Bataille_de_Cadoret",flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,desc:"Charles de Blois combattit Thomas Dagworth toute une après-midi. Pris sous une pluie de flèches, l'armée de Charles de Blois subit de nombreuses pertes.",edesc:"Charles de Blois fought Thomas Dagworth all afternoon. Caught in a rain of arrows, the army of Charles de Blois suffered many casualties."},
                {start:"1345-08",text:"Bataille de Bergerac", flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,desc:"Les armées anglo-gasconnes commandées par le comte de Derby combattirent les Français autour du pont de Bergerac qui était sur la frontière de la Gascogne (anglaise) et devant les murs, avant la prise de la ville.",wiki:"Bataille_de_Bergerac",edesc:"The Anglo-Gascon armies commanded by the Count of Derby fought the French around the Bergerac bridge on the border of Gascony and in front of the walls before the city was taken."},
                {start:"1345-10-21",text:"Bataille d'Auberoche", flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,desc:"Les anglo-gascons commandés par le comte de Derby, en infériorité numérique attaquèrent les Français pendant le déjeuner. Déroute totale des Français.",victoire:ANGLAIS,wiki:"Bataille_d%27Auberoche",edesc:"The Anglo-Gascons under the command of the Earl of Derby, outnumbered, attacked the French during lunch. Total rout of the French."},
                {start:"1346-06-09",text:"Bataille de Saint-Pol-de-Léon", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:ANGLAIS,desc:"Charles de Blois lança des multiples assauts frontaux de fantassins contre des archers anglais retranchés. Il ne put remporter la victoire et dû retourner dans ses bastions.",wiki:"Bataille_de_Saint-Pol-de-L%C3%A9on",edesc:"Charles de Blois launched multiple frontal attacks by infantrymen against entrenched English archers. He could not win the victory and had to return to his strongholds."},
                {start:"1346-07-02",stop:"1347-10-12",text:"Chevauchée d'Édouard III", etext:"Crecy Campaign",flag:[FRANCAIS,ANGLAIS],wiki:"Chevauch%C3%A9e_d%27%C3%89douard_III_(1346)",campagne:"Chevauchée d'Edouard III (1346)",commandants:["Edouard III","Prince Noir","Warwick","Northampton","Chandos","Jean 1er de Luxembourg","Arundel"]},
                {start:"1346-07-26",text:"Siège de Caen", flag:[FRANCAIS,ANGLAIS],campagne:"Chevauchée d'Edouard III (1346)",victoire:ANGLAIS,commandants:["Edouard III","Le Prince Noir","Warwick","Northampton"],wiki:"Si%C3%A8ge_de_Caen_(1346)",desc:"Prise de la ville française, peu défendue et pillage.",edesc:"Capture of the poorly defended French city and looting."},
                {start:"1346-08-24",text:"Bataille du gué de Blanquetaque",etext:"Battle of Blanchetaque",campagne:"Chevauchée d'Edouard III (1346)",victoire:ANGLAIS,commandants:["Edouard III","Le Prince Noir","Warwick","Northampton"], flag:[FRANCAIS,ANGLAIS],wiki:"Bataille_du_gu%C3%A9_de_Blanquetaque",desc:"L'armée anglaise se retrouva sur un gué devant la Somme, avec une armée française sur la rive opposée. Quelques Anglais traversèrent et les Français se précipitèrent à leur rencontre dans le fleuve. La bataille se déroula au milieu du gué de la Somme.",edesc:"The English army found itself on a ford in front of the Somme, with a French army on the opposite bank. Some English crossed and the French rushed to meet them in the river. The battle took place in the middle of the ford of the Somme."},
                {start:"1346-08-26",type:BATAILLE,scenario:true,campagne:"Chevauchée d'Edouard III (1346)",victoire:ANGLAIS,commandants:["Edouard III","Le Prince Noir","Northampton","Philippe VI de Valois","Chandos","Jean 1er de Luxembourg","Arundel","Charles II"],text:"Bataille de Crécy",joueurs:[2],stars:2,flag:[FRANCAIS,ANGLAIS],desc:"Sur le chemin de retour de sa chevauchée, Edouard III obtint une victoire écrasante face à l'armée de Philippe VI, pourtant supérieure numériquement. Charles II y mourut",wiki:"Bataille_de_Crécy",edesc:"On the way back from his cavalcade, Edward III obtained a crushing victory over the numerically superior army of Philip VI. Charles II died there"},
                {start:"1346-09-04",stop:"1347-08-03",type:SIEGE,scenario:true,text:"Siège de Calais",campagne:"Chevauchée d'Edouard III (1346)",joueurs:[2],stars:2,flag:[FRANCAIS,ANGLAIS],commandants:["Jean de Vienne","Edouard III"],victoire:ANGLAIS,desc:"6 bourgeois de Calais, la corde au cou, pieds nus et en chemise, se rendirent à Edouard III pour épargner la ville. Ce Jean de Vienne était l'oncle de l'amiral Jean de Vienne.",wiki:"Si%C3%A8ge_de_Calais_(1346-1347)",wiki:"Siège_de_Calais_(1346-1347)",edesc:"6 bourgeois of Calais, with a rope around their necks, barefoot and in shirt, went to Edward III to spare the city. This Jean de Vienne was the uncle of the Admiral Jean de Vienne."},
                {start:"1346-10-17",text:"Bataille de Neville's Cross",victoire:ANGLAIS,flag:[ECOSSAIS,ANGLAIS],wiki:"Bataille_de_Neville%27s_Cross",desc:"Espérant vaincre les Anglais alors concentrés en France, les Ecossais avec le roi David II envahirent le nord de l'Angleterre. Ils se heurtèrent à une force bien retranchée qui les battit et captura le roi.",edesc:"Hoping to defeat the English then concentrated in France, the Scots with King David II invaded the north of England. They encountered a well-entrenched force that defeated them and captured the king."},
                {start:"1347-06-18",text:"Bataille de La Roche-Derrien",flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,campagne:"Guerre de succession de Bretagne",wiki:"Bataille_de_La_Roche-Derrien",desc:"Les anglo-monfortistes commandés par Thomas Dagworth gagnèrent contre les Bretons de Charles de Blois. Celui-ci fut fait prisonnier.",edesc:"The Anglo-Monfortists led by Thomas Dagworth won against the Bretons of Charles de Blois. Charles de Blois was taken prisoner."},
                {start:"1348-02",type:BATAILLE,scenario:true,etext:"The Plague",text:"La Peste",flag:[BIEN,MAL],joueurs:[2],stars:3,edesc:"The plague spreads mercilessly through cities: Messina, Genoa, Marseille... Everywhere, people fall. They leave their homes to find refuge away from the sickness, but in doing so they bring the scourge with them. St Roch, who learnt about the plague with Dominican priests, decided to go back to his hometown to try and save its inhabitants from the relentless march of the people fleeing death... and bringing it with them."},
                {start:"1348-02-02",text:"Bataille de la Strėva",etext:"Battle of the Streva",flag:[TEUTONIQUE,LITUANIEN],victoire:TEUTONIQUE,wiki:"Bataille_de_la_Strėva",commandants:["Kniprod","Narimantas","Manvydas"]},
                {start:"1349-07",text:"Bataille de Lunalonge",commandants:["Captal","Boucicaut"],flag:[FRANCAIS,ANGLAIS],desc:"Un raid des Français contre les Anglais. La bataille eu lieu sur une colline occupée par les Anglais, combattant avec des lances. Boucicaut fut capturé.",wiki:"Bataille_de_Lunalonge",edesc:"A raid by the French against the English. The battle took place on a hill occupied by the English, fighting with spears. Boucicaut was captured."},
                {start:"1349-12-31",stop:"1350-01-01",text:"Siège de Calais",flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,commandants:["Edouard III","Salisbury","Suffolk"],desc:"Le gouverneur de Calais s'apprêtait à livrer Calais aux Français. Edouard III l'apprit et embusqua les Français.",wiki:"Siège_de_Calais_(1349-1350)",edesc:"The governor of Calais was preparing to hand Calais over to the French. Edward III learned of this and ambushed the French."},
                {start:"1350-06",text:"Combat de Fougeray",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Guesclin"],campagne:"Guerre de succession de Bretagne",desc:"Du Guesclin prit par ruse ce faubourg de Rennes. Se faisant passer pour des paysans, transportant du bois dans des chariots pour couvrir leurs armes, Du Guesclin et un petit groupe de soldats s'introduisirent dans la ville après le départ d'une troupe. Ils bloquèrent la herse et le pont levis avec le bois et les chariots et les 31 hommes du commando massacrèrent les 100 hommes de la garnison. Le diner préparé par les Anglais fut mangé par les Français",book:"185",edesc:"Du Guesclin ruse this suburb of Rennes. Posing as peasants, carrying wood in wagons to cover their weapons, Du Guesclin and a small group of soldiers entered the town after a troop had left. They blocked the portcullis and drawbridge with wood and wagons and the 31 men of the commando massacred the 100 men of the garrison. The dinner prepared by the English was eaten by the French."},
                {start:"1351-06",text:"Bataille de Saintes",flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,desc:"Les Français, assiégeant Saintes, furent mis en déroute par une armée de secours anglaise.",wiki:"Bataille_de_Saintes",edesc:"The French laid siege to Saintes and were routed by an English relief army."},
                {start:"1351-03",stop:"1351-08-07",text:"Siège de Saint-Jean-d'Angély",flag:[FRANCAIS,ANGLAIS],commandants:["Jean II","Amanieu"],victoire:FRANCAIS,desc:"Un siège Français sur une petite ville non stratégique. La ville se rendit sans combat.",wiki:"Si%C3%A8ge_de_Saint-Jean-d%27Ang%C3%A9ly_(1351)",edesc:"A French siege on a small non-strategic town. The town surrendered without a fight."},
                {start:"1351-03-26",type:BATAILLE,text:"Combat des Trente", etext:"Combat of the Thirty",flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",commandants:["Knolles"],victoire:FRANCAIS,wiki:"Combat_des_Trente",desc:"À la suite d'un défi lancé par Jean IV de Beaumanoir, un combat fut organisé entre trente partisans de Charles de Blois et trente partisans de Jean de Montfort",edesc:"Following a challenge by Jean IV de Beaumanoir, a fight was organised between thirty supporters of Charles de Blois and thirty supporters of Jean de Montfort."},
                {start:"1351-06-06",text:"Bataille d'Ardres",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,desc:"Les Anglais furent vaincus après être surpris par une armée Française alors qu'ils se retiraient d'un raid.",wiki:"Bataille_d%27Ardres",edesc:"The English were defeated after being surprised by a French army as they withdrew from a raid."},
                {start:"1352-08-14",text:"Bataille de Mauron",flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:ANGLAIS,wiki:"Bataille_de_Mauron",desc:"Les Français attaquèrent les Anglais sur une colline, forcèrent les archers à combattre comme des fantassins mais finirent par se faire battre puis massacrer. Les pertes furent importantes des deux cotés.",edesc:"The French attacked the English on a hill, forcing the archers to fight like infantrymen, but were eventually defeated and massacred. Casualties were heavy on both sides."},
                {start:"1354-04-10",text:"Bataille de Montmuran",campagne:"Guerre de succession de Bretagne",commandants:["Guesclin"],victoire:FRANCAIS,flag:[FRANCAIS,ANGLAIS],desc:"Les Franco-Bretons dirigés par Du Guesclin se vengèrent de la bataille de Mauron.",wiki:"Bataille_de_Montmuran",edesc:"The Franco-Bretons led by Du Guesclin took revenge for the battle of Mauron."},
                {start:"1355-10-10",stop:"1355-12-09",text:"Chevauchée du Prince noir", etext:"Black Prince's Ride",commandants:["Prince Noir"],flag:[FRANCAIS,ANGLAIS]},
                {start:"1356-08-04",stop:"1356-09-19",scenario:true,type:CHEVAUCHEE,type:CHEVAUCHEE,etext:"Black Prince's Ride",text:"La Chevauchée du Prince Noir",flag:[FRANCAIS,ANGLAIS],commandants:["Prince Noir"],joueurs:[2,4],stars:3,campagne:"Chevauchée du Prince Noir"}, /* TODO: Boucicaut n'est pas la */
                {start:"1356-09-01",type:BATAILLE,text:"Bataille de Romorantin",flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,commandants:["Clermont","Romorantin","Boucicaut","Craon"],book:"329",desc:"Avant la bataille de Poitiers, l'avant-garde française embusqua les éclaireurs Anglais. La stratégie anglaise a consisté à esquiver le choc de la charge des Français et à se retourner pour les attaquer immédiatement dans le dos.",campagne:"Chevauchée du Prince Noir",edesc:"Before the Battle of Poitiers, the French vanguard ambushed English scouts. The English strategy was to dodge the shock of the French charge and turn around to immediately attack them in the back."},
                {start:"1356-09-19",scenario:true,type:BATAILLE,text:"Bataille de Poitiers", joueurs:[2,6],stars:3,flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,commandants:["Jean II","Le Prince Noir","Salisbury","Philippe d'Orléans","Audrehem","Gautier VI","Clermont","Chandos","Warwick","Captal"],wiki:"Bataille_de_Poitiers_(1356)",desc:"Déroute francaise décisive, le roi Jean II fut capturé.",campagne:"Chevauchée du Prince Noir",edesc:"A decisive French rout, King John II was captured."},
                {start:"1356-10-03",stop:"1357-06-30",text:"Siège de Rennes",flag:[ANGLAIS,FRANCAIS],wiki:"Si%C3%A8ge_de_Rennes_(1356-1357)",victoire:ANGLAIS,campagne:"Guerre de succession de Bretagne",commandants:["Guesclin"],desc:"Les Anglais eurent pour stratégie d'affamer la ville mais les défenseurs usèrent de ruse. Les Anglais firent paitre devant les portes des troupeaux de porc, pour attirer les Rennais hors de la ville. En réponse, le capitaine de la ville fit suspendre une truie qui par ses cris attira les cochons dans la ville! Enfin Du Gueslin entra dans la ville avec des charettes de vivre par ruse, en se faisant passer pour des mercenaires allemands. La ville s'en sorti en payant une rançon aux Anglais finalement.",edesc:"The strategy of the English was to starve the city but the defenders used cunning. The English grazed the gates with herds of pigs to lure the Rennes inhabitants out of the city. In response, the captain of the city had a sow hung up, and her cries drew the pigs into the city! Finally Du Gueslin entered the town with some cunning living carts, posing as German mercenaries. The town got away with paying a ransom to the English at last."},
                {start:"1356-12",type:BATAILLE,scenario:true,etext:"Du Guesclin at the Siege of Rennes", text:"Du Guesclin au siège de Rennes",joueurs:[2],stars:1,flag:[ANGLAIS,FRANCAIS],commandants:["Guesclin"],campagne:"Guerre de succession de Bretagne"}, /* TODO: Un an plus tot que le scenario*/
                {start:"1358-04-18",stop:"1358-08-02",text:"Siège de Paris", flag:[FRANCAIS,AUTRE],desc:"Charles le Dauphin reprit Paris à Etienne Marcel et Charles le Mauvais",victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Paris_(1358)",campagne:"Grande Jacquerie",edesc:"Charles the Dauphin took back Paris from Etienne Marcel and Charles the Evil One."},
                {start:"1358-06-09",text:"Siège de Meaux",flag:[FRANCAIS,AUTRE],wiki:"Si%C3%A8ge_de_Meaux_(1358)",campagne:"Grande Jacquerie",victoire:FRANCAIS,commandants:["Buch"],desc:"Des paysans révoltés par les ravages de la guerre, la peste, firent le siège du marché de Meaux, où étaient les princesses dont la femme du Dauphin. Le comte de Foix et Captal de Buch (pour les français) délivrèrent les princesses",edesc:"Peasants, revolted by the ravages of war and plague, laid siege to the market of Meaux, where the princesses were, including the wife of the Dauphin. The Count of Foix and Captal de Buch (for the French) freed the princesses."},
                {start:"1358-06-01",text:"Bataille de Longeuil Sainte Marie",flag:[FRANCAIS,AUTRE],wiki:"Si%C3%A8ge_de_Meaux_(1358)",campagne:"Grande Jacquerie",victoire:AUTRE,desc:"Des paysans révoltés par les ravages de la guerre, la peste, s'en prirent aux troupes d'occupation anglaises. Guillaume d'Aloue puis le Grand Ferré commandaient les paysans. La bataille eu lieu autour d'un corps de ferme et de l'église du village.",edesc:"Peasants, revolted by the ravages of war and the plague, attacked the English occupation troops. Guillaume d'Aloue and then Grand Ferré commanded the peasants. The battle took place around a farmhouse and the village church."},
                {start:"1358-08-01",stop:"1359-04-29",text:"Siège de Saint-Valery",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Saint-Valery",desc:"Les Français assiégèrent et prirent la ville des mains du roi de Navarre, Charles le Mauvais",edesc:"The French laid siege to the town and took it from the King of Navarre, Charles the Bad."},
                {start:"1358-09-16",text:"Bataille d'Amiens",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,wiki:"Bataille_d%27Amiens_(1358)",desc:"Les partisans de Charles le Mauvais tentèrent de prendre Amiens alors qu'une nouvelle enceinte était en construction. Sans succès.",edesc:"The partisans of Charles the Bad tried to take Amiens while a new enceinte was under construction. Unsuccessfully."},
                {start:"1359-10-28",stop:"1360-05-08",text:"Chevauchée d'Edouard III", etext:"Edward III's Chevauchée",flag:[FRANCAIS,ANGLAIS],campagne:"Chevauchée d'Edouard III (1359)"},
                {start:"1359-12-20",stop:"1360-01-11",text:"Siège de Reims",commandants:["Edouard III"],campagne:"Chevauchée d'Edouard III (1359)",flag:[FRANCAIS,ANGLAIS],desc:"Le siège fut abandonné, faute de matériel de siège.",wiki:"Si%C3%A8ge_de_Reims",victoire:FRANCAIS,edesc:"The siege was abandoned for lack of siege equipment."},
                {start:"1360-03-12",text:"Attaque de Winchelsea",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,desc:"Un raid francais en Angleterre pour libérer Jean II, supposé être à Winchelsea.",book:365,edesc:"A French raid in England to free John II, who was supposed to be at Winchelsea."},
                {start:"1360-03-31",stop:"1360-04-12",text:"Siège de Paris",flag:[FRANCAIS,ANGLAIS],commandants:["Edouard III"],campagne:"Chevauchée d'Edouard III (1359)",victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Paris_(1360)",desc:"Les Anglais campaient dans les faubourgs. Charles le Dauphin refusa le combat. Les Anglais durent lever le siège, sans résultat.",edesc:"The English camped in the suburbs. Charles the Dauphin refused to fight. The English had to lift the siege, but to no avail."},
                {start:"1360-03-31",text:"Siège de l'église fortifiée de Chastres",etext:"Siege of the fortified church of Chastres",flag:[FRANCAIS,ANGLAIS],commandants:["Edouard III"],campagne:"Chevauchée d'Edouard III (1359)",victoire:ANGLAIS,desc:"Les Anglais s'arrêtent près d'une église fortifiée, et un combat a lieu avec les locaux. L'église finit brûlée.",book:"125",edesc:"The English stop near a fortified church, and a fight ensues with the locals. The church ends up being burned."},
                {start:"1360-04-13",text:"Lundi noir", etext:"Black Sunday",victoire:BIEN,flag:[ANGLAIS,BIEN],commandants:["Edouard III","Le Prince Noir","Warwick"],campagne:"Chevauchée d'Edouard III (1359)",victoire:FRANCAIS,desc:"Un orage terrible décima les troupes anglaises, et conclua la chevauchée d'Edouard III.",wiki:"Lundi_noir_(1360)",edesc:"A terrible storm decimated the English troops, and concluded Edward III's ride."},
                {start:"1360-05",text:"Traité de Brétigny",etext:"Treaty of Bretigny",flag:[FRANCAIS,ANGLAIS],wiki:"Trait%C3%A9_de_Br%C3%A9tigny"},
                {start:"1361-04",text:"Bataille de Briouze",flag:[FRANCAIS,MERCENAIRE],commandants:["Guesclin"],victoire:FRANCAIS,campagne:"Campagne contre les grandes compagnies",desc:"A force de flatterie, les Anglais convainquirent Du Guesclin de les laisser se déployer en rase campagne afin qu'ils puissent utiliser toutes leurs forces. Ils furent battus quand même.",book:"99",edesc:"With flattery, the English convinced Du Guesclin to let them deploy in open country so that they could use all their forces. They were defeated anyway."},
                {start:"1362-04",text:"Bataille de Mortain",flag:[FRANCAIS,MERCENAIRE],commandants:["Guesclin"],victoire:FRANCAIS,campagne:"Campagne contre les grandes compagnies",book:267},
                {start:"1362-04",text:"Bataille de Livarot",flag:[FRANCAIS,ANGLAIS,MERCENAIRE],commandants:["Jouel","Guesclin"],victoire:FRANCAIS,campagne:"Campagne contre les grandes compagnies",book:"223"},
                {start:"1362-04-06",scenario:true,type:BATAILLE,text:"Bataille de Brignais",joueurs:[2,3,4],stars:3,flag:[FRANCAIS,MERCENAIRE],victoire:MERCENAIRE,commandants:["Seguin","Meschin","Jacques de Bourbon"],campagne:"Campagne contre les grandes compagnies",wiki:"Bataille_de_Brignais"},
                {start:"1362-04",text:"Bataille de Saint-Martin-de-Seez",flag:[FRANCAIS,MERCENAIRE],victoire:FRANCAIS,commandants:["Guesclin"],campagne:"Campagne contre les grandes compagnies",book:"342",desc:"Du Guesclin força 3 Grandes Compagnies anglaises à capituler",edesc:"Du Guesclin forced 3 large English companies to surrender."},
                {start:"1364-03",stop:"1364-04-09",text:"Siège de Rolleboise",flag:[FRANCAIS,MERCENAIRE],commandants:["Guesclin","Auxerre"],victoire:FRANCAIS,campagne:"Campagne contre les grandes compagnies",wiki:"Si%C3%A8ge_de_Rolleboise"},
                {start:"1364-04-07",text:"Siège de Mantes",flag:[FRANCAIS,ANGLAIS],campagne:"Reconquête contre Charles le Mauvais",victoire:FRANCAIS,commandants:["Guesclin","Boucicaut"],wiki:"Si%C3%A8ge_de_Mantes",desc:"Boucicaut et Du Guesclin reprirent la ville à Charles le Mauvais par ruse, afin de ne pas lever le siège de Rolleboise: Boucicaut se présenta avec 100 chevaux et fit semblant d'être poursuivi par des brigands. Les gardiens ouvrirent et Du Guesclin en profita pour entrer et piller la ville",edesc:"Boucicaut and Du Guesclin took back the city from Charles le Mauvais by cunning, in order not to lift the siege of Rolleboise: Boucicaut presented himself with 100 horses and pretended to be pursued by brigands. The guards opened and Du Guesclin took the opportunity to enter and plunder the city."},
                {start:"1364-04-10",text:"Siège de Meulan",flag:[FRANCAIS,ANGLAIS],commandants:["Guesclin","Boucicaut"],victoire:FRANCAIS,campagne:"Reconquête contre Charles le Mauvais",wiki:"Si%C3%A8ge_de_Meulan",desc:"Boucicaut et Du Guesclin reprirent la ville à Charles le Mauvais par ruse, afin de ne pas lever le siège de Rolleboise: Du Guesclin se fit passer pour un envoyé du roi de Navarre. On lui ouvre les portes et la ville fut pillée et massacrée",edesc:"Boucicaut and Du Guesclin took back the city from Charles the Bad by cunning, in order not to lift the siege of Rolleboise: Du Guesclin pretended to be an envoy of the king of Navarre. The gates were opened to him and the town was plundered and massacred."},
                {start:"1364-05-16",text:"Bataille de Cocherel",flag:[FRANCAIS,ANGLAIS,MERCENAIRE],stars:3,joueurs:[2,3],commandants:["Guesclin","Auxerre","Captal","Amanieu","Cervole","Jouel","Lens"],campagne:"Reconquête contre Charles le Mauvais",victoire:FRANCAIS,wiki:"Bataille_de_Cocherel",desc:"Les troupes du roi de France s'opposèrent à Cocherel à celles de Charles le Mauvais et ses soutiens anglais.",edesc:"The troops of the King of France opposed Cocherel to those of Charles the Bad and his English supporters."},
                {start:"1365-09-29",text:"Bataille d'Auray",flag:[FRANCAIS,ANGLAIS],wiki:"Bataille_d%27Auray",victoire:ANGLAIS,commandants:["Guesclin","Chandos","Knolles","Auxerre"],desc:"Bataille décisive qui mit fin à la guerre de succession de Bretagne. Charles de Blois y fut tué et Jean IV de Bretagne en sortit victorieux. Du Guesclin fut fait prisonnier.",campagne:"Guerre de succession de Bretagne",edesc:"Decisive battle that ended the War of Succession of Brittany. Charles de Blois was killed there and John IV of Brittany emerged victorious. Du Guesclin was taken prisoner."},
                {start:"1367-04-03",text:"Bataille de Nájera",flag:[FRANCAIS,ANGLAIS],wiki:"Bataille_de_N%C3%A1jera",victoire:ANGLAIS,commandants:["Guesclin","Prince Noir","Chandos","Buch","Charles d'Albret","Audrehem"]/*TODO: Albret est avec les anglais*/,desc:"Les Anglais commandés par le Prince Noir, en soutien à Pierre le Cruel, combattirent les troupes françaises menées par Du Guesclin, soutenant Henri II de Castille. Du Guesclin fut capturé.", campagne:"Guerre civile de Castille",edesc:"The English under the command of the Black Prince, in support of Peter the Cruel, fought the French troops led by Du Guesclin, supporting Henry II of Castile. Du Guesclin was captured."},
                {start:"1369-03-14",text:"Bataille de Montiel",flag:[FRANCAIS],campagne:"Guerre civile de Castille",victoire:FRANCAIS,commandants:["Guesclin"],wiki:"Bataille_de_Montiel",desc:"Bataille décisive pour Henri II de Castille grâce à ses soutiens français. Pierre le Cruel fut tué quelques jours plus tard.",edesc:"Decisive battle for Henri II of Castile thanks to his French support. Peter the Cruel was killed a few days later."},
                {start:"1369-06",text:"Bataille de Lusignan", flag:[FRANCAIS,ANGLAIS],book:"342",victoire:FRANCAIS},
                {start:"1369-07-01",stop:"1369-07-30",text:"Siège de La Roche-Posay",etext:"Siege of La Roche-Posay",victoire:FRANCAIS,flag:[FRANCAIS,ANGLAIS],book:"327",desc:"Siège de la ville par les Français pour faire respecter le traité de Brétigny",edesc:"Siege of the city by the French to enforce the Treaty of Brétigny."},
                {start:"1369-12-31",text:"Siège de Saint-Savin-sur-Gartempe", flag:[FRANCAIS,ANGLAIS],book:"343",victoire:FRANCAIS,commandants:["Chandos"],desc:"Les Anglais commandés par Chandos tentèrent de prendre la ville par surprise, mais furent surpris par hasard par les Francais.",edesc:"The English under the command of Chandos tried to take the city by surprise, but were surprised by the French."},
                {start:"1370-01-01",type:BATAILLE,text:"Combat du Pont de Lussac",etext:"Combat of Lussac Bridge",book:"342", victoire:FRANCAIS,commandants:["Chandos"],desc:"Les Français faisant une chevauchée dans le Poitou anglais, furent rattrappés par 2 armées anglaises au pont de Lussac. La bataille eu notamment lieu sur le pont, étroit et bombé. Les Français furent vaincus mais la mort du grand capitaine anglais John Chandos fut une catastrophe pour l'Angleterre.",flag:[FRANCAIS,ANGLAIS],edesc:"The French, riding in the English Poitou, were caught by 2 English armies at the Pont de Lussac. The battle was fought on the narrow, domed bridge. The French were defeated but the death of the great English captain John Chandos was a disaster for England."},
                {start:"1370-09-19",text:"Sac de Limoges", flag:[FRANCAIS,ANGLAIS],wiki:"Sac_de_Limoges",victoire:ANGLAIS,desc:"Les Anglais après un court siège pillèrent Limoges en représailles, après que celle ci eut ouvert ses portes aux armées françaises. Le Prince Noir était venu en personne, bien que malade. Cet événement a contribué à la réputation négative du Prince Noir chez les Français",commandants:["fils du Roi","Prince Noir","Jean de Lancastre"],edesc:"After a short siege the English plundered Limoges in reprisal, after it had been opened to the French armies. The Black Prince came in person, although ill. This event contributed to the Black Prince's negative reputation among the French."},
                {start:"1370-09-23",text:"Siège de Paris", flag:[FRANCAIS,ANGLAIS],wiki:"Si%C3%A8ge_de_Paris_(1370)",desc:"Robert Knolles partit de Calais et avec une armée anglaise, pilla la campagne et se présenta à Paris en incendiant les villages alentours. Charles V refusa de miser sa couronne sur une bataille et refusa le combat. Après 2 jours d'incendies et de pillage des faubourgs, Knolles se retira.",commandants:["Knolles"],edesc:"Robert Knolles left Calais and, with an English army, plundered the countryside and came to Paris, setting fire to the surrounding villages. Charles V refused to bet his crown on a battle and refused to fight. After 2 days of burning and pillaging the suburbs, Knolles withdrew."},
                {start:"1370-12-04",text:"Bataille de Pontvallain", flag:[FRANCAIS,ANGLAIS],wiki:"Bataille_de_Pontvallain",commandants:["Vienne","Guesclin","Knolles","Audrehem"],desc:"Du Guesclin partit à la poursuite de Knolles après le siège de Paris et le harcela. Il combatit l'arrière garde de l'armée anglaise à Pontvallain. Toute l'arrière garde fut massacrée.",victoire:FRANCAIS,edesc:"Du Guesclin went after Knolles after the siege of Paris and harassed him. He defeated the English rearguard at Pontvallain. The whole rearguard was massacred."},
        {start:"1372-06",text:"Siège de Guernesey", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Guernesey",desc:"Sous les ordres de Owain le Gallois, prétendant à la principauté de Galles, les troupes françaises débarquèrent à Guernesey. Ce fut une diversion pour le siège de la Rochelle. L'expédition dut être abandonnée quand Owain fut rappelé par Charles V pour La Rochelle",edesc:"Under the command of Owain the Welshman, pretender to the principality of Wales, French troops landed in Guernsey. It was a diversion for the siege of La Rochelle. The expedition had to be abandoned when Owain was recalled by Charles V to La Rochelle."},
                {start:"1372-06-22",stop:"1372-08-23",text:"Siège de La Rochelle", flag:[FRANCAIS,ANGLAIS],wiki:"Si%C3%A8ge_de_La_Rochelle_(1372)",commandants:["Guesclin"],victoire:FRANCAIS,desc:"Les Rochelais chassèrent la garnison anglaise à l'aide d'une ruse du maire. Le maire invita le commandant anglais à diner et lui fit passer un document avec un sceau d'Edouard III pour un ordre de revue des troupes. Le commandant ne sachant pas lire, il rassembla ses troupes sur la place. Les Rochelais armés les attendaient et laissèrent entrer Du Guesclin après avoir négocié des avantages pour la  ville.",edesc:"The inhabitants of La Rochelle drove out the English garrison with the help of a trick from the mayor. The mayor invited the English commander to dinner and passed him a document with a seal of Edward III for an order to review the troops. The commander could not read, so he gathered his troops in the square. The armed La Rochelais waited for them and let Du Guesclin in after negotiating advantages for the town."},
                {start:"1372-08-22",text:"Siège de Soubise", flag:[FRANCAIS,ANGLAIS],commandants:["Buch"],victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Soubise",desc:"Ce siège mit fin à l'emprise anglaise sur la Saintonge. Owain le Gallois attaqua par surprise l'armée anglaise de Jean de Grailly, captal de Buch, qui fut capturé. Il resta emprisonné à Paris jusqu'à sa mort.",edesc:"This siege put an end to the English hold on the Saintonge. Owain the Welshman attacked by surprise the English army of Jean de Grailly, captured de Buch. He remained imprisoned in Paris until his death."},
                {start:"1373-03-21",text:"Bataille de Chizé",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Guesclin"],book:"135",desc:"La bataille eu lieu autour du chateau de Chizé que Du Guesclin assiègeait. Quand l'armée de secours anglaise arriva, Du Guesclin mit sur son chemin un convoi de barriques de vin. Une fois l'armée de secours très éméchée, Du Guesclin l'attaqua. Les assiégés sortirent alors pour aider l'armée de secours et ils se firent massacrer.",edesc:"The battle took place around the castle of Chizé which Du Guesclin was besieging. When the English relief army arrived, Du Guesclin put a convoy of wine barrels on its way. Once the relief army was very drunk, Du Guesclin attacked it. The besieged then went out to help the relief army and were massacred."},
                {start:"1373-06-12",stop:"1373-12",text:"Chevauchée de Lancastre", flag:[FRANCAIS,ANGLAIS],commandants:["Jean de Lancastre"],wiki:"Chevauchée_de_Lancastre_(1373)",desc:"Chevauchée de Jean de Lancastre avec au final un maigre butin et une armée qui fut l'ombre de celle qui avait commencé la chevauchée, Charles V et Du Guesclin ayant refusé de la combattre et firent la politique de la terre brulée.",edesc:"Ride of John of Lancaster with a meagre booty and an army that was the shadow of the one that had started the ride, Charles V and Du Guesclin having refused to fight it and made the politics of the burnt land."},
                {start:"1373-06-16",stop:"1373-06-28",text:"Siège de Mauvezin", flag:[FRANCAIS,ANGLAIS],book:"245",desc:"La garnison anglaise de Mauvezin pillait les environs. Le duc d'Anjou décida de reprendre le chateau aux Anglais. Sans réserve d'eau (mais pas sans vin), les Anglais capitulèrent.",edesc:"The English garrison of Mauvezin plundered the surroundings. The Duke of Anjou decided to take back the castle from the English. Without water (but not without wine), the English surrendered.",victoire:FRANCAIS},
                {start:"1374-06",text:"Siège de Bayonne", flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,desc:"Henri II de Castille chercha à reprendre la ville aux Anglais, avec l'aide des Français notamment Louis d'Anjou. Ce dernier resta à Toulouse, Henri II finit par lever le siège",wiki:"Si%C3%A8ge_de_Bayonne_(1374)",edesc:"Henri II of Castile sought to retake the city from the English, with the help of the French, especially Louis d'Anjou. Louis d'Anjou stayed in Toulouse, and Henri II finally lifted the siege."},
                {start:"1376-09",scenario:true,type:BATAILLE,text:"L'offensive contre Plymouth",joueurs:[4],stars:3, flag:[FRANCAIS]},
    {start:"1377-06-21",text:"Début du règne de Richard II",flag:[ANGLAIS]},
                {start:"1377-06-29",type:CHEVAUCHEE,text:"Raid sur Rye", flag:[FRANCAIS,ANGLAIS],commandants:["Vienne"],desc:"Une expédition de pillage suite à la mort d'Edouard III et la fin de la trève de Bruges entre France et Angleterre. Les paysans n'opposèrent qu'une défense molle, la ville fut brulée. Les Anglais pendirent des paysans, outrés par la faible défense.",victoire:FRANCAIS,book:"339",edesc:"A plundering expedition following the death of Edward III and the end of the Bruges truce between France and England. The peasants only put up a weak defence, the city was burnt down. The English hanged some peasants, outraged by the weak defence."},
                {start:"1377-07",text:"Bataille de Lewes", flag:[FRANCAIS,ANGLAIS],commandants:["Vienne"],book:"221",desc:"Un coup de force contre la ville de Rottingdean. Le prieur du monastère de Lewes défendit la ville farouchement avec ses habitants et des paysans. Pas de garnison dans cette ville",edesc:"A coup de force against the city of Rottingdean. The prior of the monastery of Lewes defended the town fiercely with its inhabitants and peasants. No garrison in this town",victoire:FRANCAIS},
                {start:"1377-08-21",text:"Bataille de l'île de Wight", etext:"Battle of the Isle of Wight",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Vienne"],book:"206",desc:"Bataille sur la plage. Les Français s'emparèrent de toute l'île sauf du chateau, et repartirent avec une somme d'argent payée par les habitants pour préserver leurs maisons",edesc:"Battle on the beach. The French seized the whole island except the castle, and left with a sum of money paid by the inhabitants to preserve their houses."},
                {start:"1377-08-22",text:"Bataille de Yarmouth", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Vienne"],book:"372",desc:"La ville fut prise d'assaut à l'aide d'échelle et détruite par les Français",edesc:"The town was stormed with ladders and destroyed by the French."},
                {start:"1377-07-01",stop:"1377-09",text:"Siège de Bergerac", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Guesclin"],desc:"Le duc d'Anjou fit le siège et fut rejoint par Du Guesclin en août. Il fit chercher une tour de siège qui permit de gagner la ville",source:"http://riviereesperance.canalblog.com/archives/2016/05/10/33697129.html",edesc:"The Duke of Anjou made the siege and was joined by Du Guesclin in August. He had a siege tower searched for which allowed him to reach the town."},
                {start:"1377-09-01",text:"Bataille d'Eymet", victoire:FRANCAIS,flag:[FRANCAIS,ANGLAIS],book:"175",desc:"Pour sortir le siège de Bergerac de son enlisement, Du Guesclin envoya chercher une tour de siège à la Réole. Le sénéchal de Guyenne Sir Thomas Felton en eu vent et décida de tendre une embuscade à Eymet. L'embuscade se fit déborder et les Anglais paniquèrent et se firent massacrer. La tour parvint à Bergerac.",edesc:"To lift the siege of Bergerac from its bogging down, Du Guesclin sent for a siege tower at La Réole. Guyenne's seneschal Sir Thomas Felton got wind of it and decided to ambush Eymet. The ambush was overrun and the English panicked and were massacred. The tower reached Bergerac."},
                {start:"1378-08-14",stop:"1378-09",text:"Siège de Saint-Malo", flag:[FRANCAIS,ANGLAIS],wiki:"Si%C3%A8ge_de_Saint-Malo",victoire:FRANCAIS,commandants:["Lancastre","Guesclin"],desc:"Les Anglais voulaient reprendre ce port stratégique. Lancastre fit bombarder la ville jusqu'à l'arrivée d'une armée de renfort commandée par Du Guesclin. Il essaya ensuite de saper les murailles, mais un miracle fit découvrir la sape aux malouins. Lancastre abandonna alors le siège",edesc:"The English wanted to retake this strategic port. Lancastre had the city bombed until the arrival of a reinforcement army commanded by Du Guesclin. He then tried to undermine the walls, but a miracle revealed the undermining to the malouins. Lancaster then abandoned the siege"},
                {start:"1380-06-20",stop:"1380-06-26",text:"Siège de Chaliers", flag:[FRANCAIS,MERCENAIRE],book:"123",campagne:"Contre les grandes compagnies anglo-gasconnes",commandants:["Guesclin","Badefol"],desc:"Le Languedoc et le Massif Central étant continuellement troublés par des incursions des grandes compagnies, le roi y envoya Du Guesclin. Les Français bombardèrent pendant une semaine le chateau, ouvrant une brèche dans le mur. Les assiégés capitulèrent",victoire:FRANCAIS,edesc:"The Languedoc and the Massif Central being continually troubled by incursions of the great companies, the king sent Du Guesclin there. The French bombarded the castle for a week, breaching the wall. The besieged surrendered"},
                {start:"1380-02-28",stop:"1380-07-14",text:"Siège de Châteauneuf-de-Randon", flag:[FRANCAIS,ANGLAIS,MERCENAIRE],campagne:"Contre les grandes compagnies anglo-gasconnes",commandants:["Guesclin","Badefol"],book:"129",desc:"Le Languedoc et le Massif Central étant continuellement troublés par des incursions des grandes compagnies, le roi y envoya Du Guesclin. Comme pour Chaliers, un siège en règle fut établi. Du Guesclin mourut de maladie pendant le siège, à 60 ans, le jour de la capitulation de la ville.",edesc:"The Languedoc and the Massif Central being continually troubled by incursions of large companies, the king sent Du Guesclin there. As with Chaliers, a proper siege was established. Du Guesclin died of illness during the siege, at the age of 60, on the day the city surrendered."},
                {start:"1380-11-08",stop:"1381-01-14",text:"Siège de Nantes", flag:[FRANCAIS,ANGLAIS],commandants:["Knolles"],victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Nantes_(1380-1381)",desc:"Les Anglais assiégèrent Nantes avec une force de 6000 hommes comme 2000 hommes de garnison. Après 2 mois de siège, les Anglais, malades de dysenterie et famine, décidèrent de lever le siège",edesc:"The English laid siege to Nantes with a force of 6,000 men as well as 2,000 garrison men. After 2 months of siege, the English, sick with dysentery and famine, decided to lift the siege."},
                {start:"1381-03",text:"Tournoi de Vannes",etext:"Tournament of Vannes", flag:[FRANCAIS,ANGLAIS],wiki:"Tournoi_de_Vannes",desc:"Un tournoi affrontant 5 chevaliers anglais contre 5 chevaliers français, en hommage au combat des Trente, 30 ans plus tôt. Les adversaires devaient se donner 5 coups de lance, 5 coups d'épée, 5 coups de hache puis 5 coups de dague. Les Français ne perdirent aucun combat",victoire:FRANCAIS,edesc:"A tournament between 5 English knights against 5 French knights, in tribute to the fight of the Thirty, 30 years earlier. The opponents had to give each other 5 strokes of lance, 5 strokes of sword, 5 strokes of axe and then 5 strokes of dagger. The French did not lose a single fight."},
                {start:"1382-06-29",type:BATAILLE,scenario:true,text:"La revanche de la Tarasque",etext:"The Tarasque's Revenge",stars:3,joueurs:[3],flag:[FRANCAIS,MAL,BIEN]},
                {start:"1382-07-29",type:BATAILLE,scenario:true,text:"L'Enfant",etext:"The Child",joueurs:[2],stars:3,flag:[MAL,BIEN],edesc:"The people and the Church have rallied behind a commoner, pregnant even though she is still a virgin. Chased by an enormous Beast, she must reach a safe place to give birth to the Saviour, envoy of God. Blessed by the Heavens, angels accompany her through her ordeal."},
                {start:"1382-11-27",text:"Bataille de Roosebeke", flag:[FRANCAIS,AUTRE],wiki:"Bataille_de_Roosebeke",commandants:["Hardi","Boucicaut","Vienne"],campagne:"Révolte des Tisserands de Gand",desc:"Lors de la révolte des tisserands gantois, le comte de Flandres fit appel à son gendre Philippe le Hardi. Philippe van Artevelde commandait les troupes flamandes. Il mourut dans la bataille. Boucicaut fut armé chevalier à cette bataille",victoire:FRANCAIS,wiki:"Bataille_de_Roosebeke",edesc:"During the revolt of the Ghent weavers, the Count of Flanders called on his son-in-law Philip the Bold. Philippe van Artevelde commanded the Flemish troops. He died in battle. Boucicaut was knighted at this battle."},
                {start:"1382-12-21",stop:"1383-09-17",text:"Croisade d'Henri le Despenser", etext:"Despenser's Crusade",flag:[FRANCAIS,ANGLAIS],commandants:["Hardi"],wiki:"Croisade_d'Henri_le_Despenser"},
                {start:"1383-06-08",stop:"1383-08-08",text:"Siège d'Ypres", flag:[FRANCAIS,ANGLAIS],wiki:"Siège_d'Ypres_(1383)",desc:"Le siège finit par être levé par les Anglais.",campange:"Croisade d'Henri le Despenser",edesc:"The siege is eventually lifted by the English."},
                {start:"1383-12-25",type:BATAILLE,text:"La Croix du Loup-Pendu",etext:"The Hanged Wolf's Cross",scenario:true,joueurs:[2],stars:2,flag:[FRANCAIS,MAL],commandants:["Loup-garou"]},
                {start:"1385-07",text:"Siège de Wark", flag:[FRANCAIS,ANGLAIS,ECOSSAIS],commandants:["Vienne"],wiki:"Siège_de_Wark",victoire:FRANCAIS,desc:"L'amiral Jean de Vienne débarqua en Ecosse afin de prendre à revers les Anglais. Les Français, avec leurs alliés écossais, menèrent un siège efficace de la forteresse de Wark, un poste frontalier, et la prirent.",edesc:"Admiral Jean de Vienne landed in Scotland to take the English by surprise. The French, with their Scottish allies, laid an effective siege of the fortress of Wark, a border post, and took it."},
                {start:"1385-08-14",text:"Bataille d'Aljubarrota", commandants:["Lancastre"],flag:[FRANCAIS,ANGLAIS]/* Boulangere tueuse */,desc:"Le roi Jean Ier de Castille envahit le Portugal à l'occasion de la crise de succession du Portugal. Il fut soutenu par les Français, les Portugais par les Anglais. La défaite fut sévère pour les Espagnols. Selon une légende portugaise, une femme dénommée la boulangère d'Aljubarrota élimina plusieurs soldats castillans ayant déserté le combat, en les enfermant tour à tour dans son fourneau de pain, prétendument pour les cacher des Portugais et en les tuant de sa pelle quand ils essayaient d'en sortir.",wiki:"Bataille_d'Aljubarrota",edesc:"King John I of Castile invaded Portugal during the crisis of the Portuguese succession. He was supported by the French, the Portuguese by the English. The defeat was severe for the Spaniards. According to a Portuguese legend, a woman called the baker of Aljubarrota eliminated several Castilian soldiers who had deserted the battle, locking them in turn in her bread oven, supposedly to hide them from the Portuguese and killing them with her shovel when they tried to get out." },
                {start:"1388-08-19",text:"Bataille d'Otterburn",flag:[ANGLAIS,ECOSSAIS],victoire:ECOSSAIS,wiki:"Bataille_d'Otterburn",desc:"Une victoire décisive des Ecossais. Inquiet des mouvements écossais, le roi d'Angleterre Richard II signa un traité de paix avec Charles VI",edesc:"A decisive victory for the Scots. Worried about Scottish movements, the King of England Richard II signed a peace treaty with Charles VI."},
                {start:"1395-05-17",text:"Bataille de Rovines", flag:[VALAQUE,OTTOMAN],victoire:VALAQUE,wiki:"Bataille_de_Rovine",campagne:"Campagne du Danube"},
                {start:"1396-09-25",text:"Bataille de Nicopolis", flag:[OTTOMAN,FRANCAIS,ANGLAIS,VALAQUE],campagne:"Campagne du Danube",victoire:OTTOMAN,commandants:["Boucicaut","Jacques de Bourbon","Vienne","Bayezid"],desc:"L'armée chrétienne assiègea Nicopolis. Le sultan Bajazet Ier vint au secours de la ville et défit les croisés. L'amiral Jean de Vienne y mourut.",wiki:"Bataille_de_Nicopolis",edesc:"The Christian army laid siege to Nicopolis. Sultan Bajazet I rescued the city and defeated the Crusaders. Admiral Jean de Vienne died there."},
    {start:"1399-09-30",text:"Début du règne de Henry IV",flag:[ANGLAIS]},
                {start:"1402-05-19",type:BATAILLE,text:"Combat des Sept", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,wiki:"Combat_des_Sept",desc:"7 chevaliers français combattirent 7 chevaliers anglais lors d'un défi",edesc:"7 French knights fought 7 English knights in a challenge to the French army."},
                {start:"1404-04",text:"Bataille de Blackpool Sands", wiki:"Bataille_de_Blackpool_Sands", victoire:ANGLAIS, desc:"Un raid français sur la cote anglaise qui tourna à la défaite",flag:[ANGLAIS,FRANCAIS],edesc:"A French raid on the English coast turned to defeat"},
                {start:"1404-04",text:"Siège de Harlech", flag:[FRANCAIS,ANGLAIS],wiki:"Siège_de_Harlech",victoire:FRANCAIS,desc:"Owain Glyndŵr commandait l'insurection galloise contre les Anglais. Les Français envoyèrent un corps expéditionnaire pour aider à prendre la forteresse de Harlech, avec des engins de siège. Celle-ci était très mal équipée mais résista fortement. Affamés, les défenseurs finirent par capituler.",campagne:"Insurection du pays de Galles",edesc:"Owain Glyndŵr commanded the Welsh insurection against the English. The French sent an expeditionary force to help take the fortress of Harlech with siege engines. The fortress was very poorly equipped but held up well. Starving, the defenders eventually surrendered."},
                {start:"1404-04",text:"Siège de Caernarfon", flag:[FRANCAIS,ANGLAIS],campagne:"Insurection du pays de Galles",wiki:"Siège_de_Caernarvon",victoire:FRANCAIS,desc:"Owain Glyndŵr commandait l'insurection galloise contre les Anglais. Les Français escaladèrent les murs et la ville capitula.",book:"110",edesc:"Owain Glyndŵr commanded the Welsh insurection against the English. The French climbed the walls and the city capitulated."},
                {start:"1404-11-16",stop:"1404-11-19",text:"Siège de Falmouth", flag:[FRANCAIS,ANGLAIS,MAL],book:"178",commandants:["Jacques de Bourbon"],desc:"Cette expédition française vainquit la ville, défendue par des paysans anglais. Mais le 19, un raz de marée coula 12 navires français.",edesc:"This French expedition defeated the town, which was defended by English peasants. But on the 19th, a tidal wave sank 12 French ships."},
                {start:"1405-06-2",stop:"1405-07-04",type:CHEVAUCHEE,text:"Raid contre Saint-Vaast-la-Hougue", flag:[FRANCAIS,ANGLAIS],book:"345",desc:"Pour mettre fin à l'aide aux Gallois, l'amiral Thomas de Lancastre essaya de prendre, sans succès la citadelle de l'Ecluse. En compensation, il pilla Saint-Vaast-la-Hougue",campagne:"Insurection du pays de Galles",edesc:"To stop the Welsh from helping the Welsh, Admiral Thomas of Lancaster tried to take the citadel of L'Ecluse without success. As compensation, he plundered St. Vaast-la-Hougue."},
                {start:"1405-08",text:"Siège de Haverford", flag:[FRANCAIS,ANGLAIS],campagne:"Insurection du pays de Galles",desc:"L'armée française prit probablement la ville par escalade",victoire:FRANCAIS,book:"205",edesc:"The French army probably took the town by escalation."},
                {start:"1405-08",text:"Siège de Carmarthen", flag:[FRANCAIS,FRANCAIS],campagne:"Insurection du pays de Galles",victoire:FRANCAIS,desc:"La ville de Merlin l'enchanteur fut prise par escalade, grâce au corps expéditionnaire français, en soutien aux insurgés gallois commandés par Owen Glyndŵr",book:"115",edesc:"The town of Merlin the Enchanter was captured by the French Expeditionary Force in support of the Welsh insurgents led by Owen Glyndŵr."},
                {start:"1405-09",text:"Bataille de Worcester", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,campagne:"Insurection du pays de Galles",desc:"En se dirigant vers Worcester, l'armée franco-galloise se heurta à une armée anglaise. Pendant une semaine, il n'y eut que des escarmouches. Les fourageurs gallois finirent par voler les bagages des Anglais lors d'une nuit, l'armée anglaise retraitant alors. Cela mis fin à cette campagne franco-galloise.",book:"369",edesc:"On the way to Worcester, the Welsh-French army came up against an English army. For a week there were nothing but skirmishes. The Welsh raiders finally stole the English luggage one night, as the English army retreated. That ended the Welsh-French campaign."},
                {start:"1406-01-01",stop:"1407-10-12",text:"Siège de Lourdes", flag:[FRANCAIS,ANGLAIS],book:"229",commandants:["Jean de Bourbon"],victoire:FRANCAIS,desc:"Seul nid d'aigle restant aux mains des Anglais, il fut assiégé, bombardé, affamé avant une reddition négociée",edesc:"The only eagle's nest remaining in English hands, it was besieged, bombed, starved and then surrendered by negotiation."},
                {start:"1406-09",type:CHEVAUCHEE,text:"Raid sur Jersey", flag:[FRANCAIS,ANGLAIS],book:"213",desc:"Une troupe franco-castillane débarqua sur Jersey et combattit la garnison anglaise. Les Anglais furent vaincus et le butin du pillage fut rapporté à Brest",victoire:FRANCAIS,edesc:"A French-Castilian troop landed on Jersey and fought the English garrison. The English were defeated and the spoils of the plunder were brought back to Brest."},
                {start:"1409-08",type:BATAILLE,text:"Saint Michel et le Dragon",etext:"Saint Michael and the Dragon",scenario:true,joueurs:[2],stars:2,flag:[MAL,BIEN],
                 commandants:["Dragon","saint Michel"],desc:"Sur le mont Tombe, Satan est venu chercher vengeance. Sept siècles auparavant, il a été misérablement défait par saint Michel et sa cohorte d’anges. Satan veut effacer ce douloureux souvenir, et revient sous la forme d’un dragon encore plus puissant. Il a décidé de détruire l’église construite par l’évêque Aubert en 709, en l’honneur de la victoire de saint Michel. Aujourd’hui, en pleine guerre de Cent ans, les moines bénédictins sont prêts à défendre la sainte chapelle du mont Saint-Michel."},
                {start:"1410-07-14",type:BATAILLE,text:"Bataille de Grunwald",flag:[FRANCAIS,LITUANIEN,TEUTONIQUE,POLONAIS,ANGLAIS],commandants:["Boucicaut"],wiki:"Bataille_de_Grunwald"},
                {start:"1411-04",text:"Siège de Rethel", flag:[FRANCAIS,BOURGUIGNON],campagne:"Armagnacs contre Bourguignons",victoire:BOURGUIGNON,desc:"La ville défendue par les Bourguignons resta close et ne fut pas prise. Les Armagnacs mirent le feu à ses faubourgs",wiki:"Siège_de_Rethel_(1411)",edesc:"The city defended by the Burgundians remained closed and was not taken. The Armagnacs set fire to its suburbs."},
                {start:"1412-05-09",text:"Bataille de Saint-Rémy-du-Plain",campagne:"Armagnacs contre Bourguignons", flag:[FRANCAIS,BOURGUIGNON],wiki:"Bataille_de_Saint-Rémy-du-Plain",victoire:BOURGUIGNON,desc:"Les Bourguignons attendirent les Armagnacs qui chargèrent et furent défaits par les arbalétriers et archers bourguignons. Jean II de Luxembourg, combattant pour les bourguignons, fut fait chevalier en début de bataille.",commandants:["Jean II de Luxembourg"],edesc:"The Burgundians waited for the Armagnacs who charged and were defeated by Burgundian crossbowmen and archers. John II of Luxembourg, fighting for the Burgundians, was knighted at the beginning of the battle."},
                {start:"1412-06-11",stop:"1412-07-12",text:"Siège de Bourges",campagne:"Armagnacs contre Bourguignons", flag:[FRANCAIS,BOURGUIGNON],commandants:["fils du Roi","de Croy"],victoire:FRANCAIS,wiki:"Siège_de_Bourges_(1412)"},
                {start:"1412-07-10",stop:"1412-07-15",text:"Siège de Dreux", flag:[FRANCAIS,BOURGUIGNON],campagne:"Armagnacs contre Bourguignons",wiki:"Siège_de_Dreux_(1412)",desc:"La ville aux mains des Armagnacs, notamment Charles d'Albret, comte de Dreux, capitula à force de bombardements",commandants:["Charles d'Albret"],victoire:BOURGUIGNON,edesc:"The city in the hands of the Armagnacs, notably Charles d'Albret, Count of Dreux, capitulated by bombardment."},
    {start:"1413-03-20",text:"Début du règne de Henry V",flag:[ANGLAIS]},
                {start:"1413-04-27",stop:"1413-09-05",text:"Révolte des Cabochiens", flag:[FRANCAIS,BOURGUIGNON],campagne:"Armagnacs contre Bourguignons",wiki:"Révolte_des_Cabochiens",victoire:FRANCAIS,desc:"La corporation des Bouchers, avec Simon Caboche, à Paris controlée par les Bourguignons, refusa les impôts pour financer la guerre. Ils forcèrent le roi à signer une ordonnance en leur faveur, mais leurs exactions poussèrent les Parisiens à demander un retour des Armagnacs. La révolte fut matée dans le sang. La Boucherie du Parvis Notre-Dame fut rasée. Jean sans peur s'enfuit de Paris", wiki:"Révolte_des_Cabochiens",edesc:"The corporation of the Butchers, with Simon Caboche, in Paris controlled by the Burgundians, refused to pay taxes to finance the war. They forced the king to sign an ordinance in their favor, but their exactions pushed the Parisians to demand the return of the Armagnacs. The revolt was crushed in blood. The butcher's shop in the Parvis Notre-Dame was razed to the ground. John the Fearless fled from Paris."},
                {start:"1415-08-18",text:"Siège d'Harfleur", flag:[FRANCAIS,ANGLAIS],commandants:["Henry V","Charles d'Albret"],desc:"Henry V envahit la France et revendiqua la couronne, rallumant la guerre après 35 ans de trêve. Harfleur fut assiégée, bombardée et après un délai pour attendre une armée de secours de Charles d'Albert qui n'arriva pas à casser le siège, la ville capitula.",wiki:"Siège_d'Harfleur",victoire:ANGLAIS,edesc:"Henry V invaded France and claimed the crown, reigniting the war after 35 years of truce. Harfleur was besieged, bombed and after a delay in waiting for a relief army from Charles d'Albert who was unable to break the siege, the town capitulated."},
                {start:"1415-10-25",type:BATAILLE,scenario:true,text:"La bataille d'Azincourt", etext:"Battle of Agincourt",joueurs:[2,4],stars:3,flag:[FRANCAIS,ANGLAIS],commandants:["Richemont","Charles d'Albret","Henry V","Oxford","York","Brimeu","de Croy","Boucicaut","Buch"],desc:"Les Français chargèrent sans organisation, et se firent massacrer. Cette bataille décisive fut un tournant dans l'art de la guerre du Moyen âge. Les armées plus disciplinées, plus maniables et les armes de jet/d'artillerie se développèrent alors. d'Albret, Brimeu, de Croy, les comtes d'Oxford et d'York moururent à Azincourt",victoire:ANGLAIS,book:"35",wiki:"Bataille_d'Azincourt",edesc:"The French charged without organization, and were massacred. This decisive battle was a turning point in the art of warfare in the Middle Ages. The armies became more disciplined, more maneuverable, and jet/artillery weapons developed. d'Albret, Brimeu, de Croy, the Earls of Oxford and York died at Azincourt."},
                {start:"1416-03-09",text:"Bataille de Valmont", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,wiki:"Bataille_de_Valmont",desc:"Un raid anglais commandé par Thomas de Beaufort fut intercepté par une armée française commandée par Bernard d'Armagnac, qui tourna à l'avantage des Français. 2 jours plus tards, cette armée française fut battue près de Harfleur",wiki:"Bataille_de_Valmont",edesc:"An English raid commanded by Thomas de Beaufort was intercepted by a French army commanded by Bernard d'Armagnac, which turned to the advantage of the French. 2 days later, this French army was defeated near Harfleur."},
                {start:"1417-08-18",text:"Siège de Caen", flag:[FRANCAIS,ANGLAIS],commandants:["Henry V"],desc:"Henry V décida de faire sauter Caen, bloquant la Normandie et qu'il considérait sienne. La ville n'avait pas de garnison, mais après une forte résistance des milices bourgeoises, des échanges d'artillerie, la ville se rendit",victoire:ANGLAIS,wiki:"Siège_de_Caen_(1417)",edesc:"Henry V decided to blow up Caen, blocking Normandy, which he considered his own. The city had no garrison, but after strong resistance from the bourgeois militia and artillery exchanges, the city surrendered."},
                {start:"1418-07-29",stop:"1419-01-19",type:SIEGE,text:"Siège de Rouen", joueurs:[2],stars:2,scenario:true,flag:[FRANCAIS,ANGLAIS],commandants:["Blanchard","Bouteiller","Henry V"],victoire:ANGLAIS,desc:"Un long siège de Rouen mena les habitants à la famine. Les habitants négocient la réddition. Blanchard, commandant les canons et les arbalétriers, fut executé, car trop pauvre pour acheter sa grâce",victoire:ANGLAIS,wiki:"Siège_de_Rouen_(1418-1419)",edesc:"A long siege of Rouen led the inhabitants to famine. The inhabitants negotiate surrender. Blanchard, commander of the cannons and crossbowmen, was executed, for he was too poor to buy his grace."},
                {start:"1420-06-16",stop:"1420-07-01",text:"Siège de Montereau-Fault-Yonne", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON],commandants:["Henry V"],victoire:ANGLAIS,desc:"La ville fut rapidement prise, mais le chateau résista. La garnison obtint un laissez passer et se rendit",wiki:"Siège_de_Montereau-Fault-Yonne",edesc:"The town was quickly taken, but the castle held out. The garrison obtained a pass and surrendered."},
                {start:"1420-07-07",stop:"1420-11-17",text:"Siège de Melun", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON] ,commandants:["Henry V"],victoire:ANGLAIS,desc:"La ville tomba pour cause de famine",wiki:"Siège_de_Melun_(1420)",edesc:"The city fell due to famine."},
                {start:"1420-04",text:"Prise de Paris", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON],wiki:"Prise_de_Paris_(1420)",commandants:["Henry V"],victoire:ANGLAIS,desc:"Entrée des Anglais dans Paris. Les Armagnacs en furent chassés depuis l'assassinat du Duc de Bourgogne, Jean sans Peur l'année d'avant.",edesc:"The English entered Paris. The Armagnacs were driven out since the assassination of the Duke of Burgundy, John the Fearless the year before."},
                {start:"1421-03-22",text:"Bataille de Baugé", flag:[FRANCAIS,ANGLAIS,ECOSSAIS],victoire:ECOSSAIS,commandants:["Buchan","Salisbury","Derneley"],wiki:"Bataille_de_Baugé",desc:"Le duc de Clarence, impulsif, lança l'armée anglaise à l'assaut d'une colline défendue par l'armée franco-écossaise menée par Jean Stuart de Buchan. Ce fut un massacre pour les Anglais.",edesc:"The impulsive Duke of Clarence launched the English army on a hill defended by the Franco-Scottish army led by Jean Stuart de Buchan. It was a massacre for the English."},
                {start:"1421-08-30",text:"Bataille de Mons-en-Vimeu", flag:[FRANCAIS,BOURGUIGNON],commandants:["Xaintrailles","Hire","II de Luxembourg"],victoire:BOURGUIGNON,campagne:"Armagnacs contre Bourguignons",wiki:"Bataille_de_Mons-en-Vimeu",desc:"Les Bourguignons battirent les Armagnacs, et permirent aux Bourguignons de controler la Picardie. Il y eut beaucoup de prisonniers",edesc:"The Burgundians defeated the Armagnacs, and allowed the Burgundians to control Picardy. There were many prisoners"},
                {start:"1421-10-06",stop:"1422-05-10",text:"Siège de Meaux", flag:[FRANCAIS,ANGLAIS],wiki:"Siège_de_Meaux_(1421-1422)",victoire:ANGLAIS,commandants:["Henry V"],desc:"Meaux était une place forte proche de Paris encore tenue par les partisans du Dauphin. Après la défaite à Baugé, Henry V mena une campagne éclair, avec Dreux, Chartres, puis Meaux. Malgré une défense vaillante, la ville se rendit. La conséquence fut qu'un grand nombre de villes se livrèrent à Henry V",edesc:"Meaux was a stronghold near Paris still held by supporters of the Dauphin. After the defeat at Baugé, Henry V led a lightning campaign, with Dreux, Chartres, then Meaux. Despite a valiant defense, the city surrendered. The consequence was that a large number of towns surrendered to Henry V"},
                {start:"1421-10-31",type:BATAILLE,scenario:true,text:"Plus de place en Enfer",etext:"No More Room in Hell", joueurs:[1],stars:3,flag:[FRANCAIS,MAL],edesc:"The Dead are rising from their graves and marching towards Rouen! Nobody knows why they’re coming, though some suspect the coming of the Apocalypse... Heroes decide to band together and face the hordes of impish creatures, serving as Rouen’s final hope against the Undead armies."},
                {start:"1421-10",text:"Traité de Troyes",flag:[FRANCAIS,ANGLAIS],wiki:"Traité_de_Troyes"},
                {start:"1422-08",text:"Bataille de Bernay", flag:[FRANCAIS,ANGLAIS],commandants:["Loré"],victoire:FRANCAIS,wiki:"Bataille_de_Bernay",desc:"Ayant appris que la riche ville de Bernay était peu défendue, l'armée française la captura.",edesc:"Having learned that the rich town of Bernay was poorly defended, the French army captured it."},
                    {start:"1422-08-31",text:"Début du règne de Henry VI",flag:[ANGLAIS]},
                {start:"1423-07-31",scenario:true,type:BATAILLE,text:"Bataille de Cravant", joueurs:[2,3,4],stars:3,flag:[FRANCAIS,ANGLAIS,BOURGUIGNON,ECOSSAIS],victoire:ANGLAIS,wiki:"Bataille_de_Cravant",commandants:["Buchan","Derneley","Toulongeon","Salisbury","Chastellux","Sévérac","Suffolk"]},
                {start:"1423-09-26",type:BATAILLE,text:"La Brossinière",etext:"Battle of La Brossinière",scenario:true,joueurs:[2],stars:1,flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["John de la Pôle","Loré"],desc:"De la Pôle, à l'issue d'une chevauchée en Maine et Anjou, revenait avec son butin et ses otages. Yolande d'Aragon, la belle-mère du dauphin, monta une interception. Ce fut un massacre pour les Anglais",wiki:"Bataille_de_la_Brossinière",edesc:"de la Pôle, at the end of a ride in Maine and Anjou, came back with its booty and hostages. Yolande d'Aragon, the Dauphin's mother-in-law, mounted an interception. It was a massacre for the English"},
    /*{start:"1424-08-15",text:"Siège de Verneuil", flag:[FRANCAIS,ECOSSAIS,ANGLAIS]},*/
                {start:"1424-08-17",text:"Bataille de Verneuil", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON,ECOSSAIS],wiki:"Bataille_de_Verneuil_(1424)",victoire:ANGLAIS,commandants:["Buchan","Salisbury","Lancastre"],desc:"Après la prise de Verneuil par les Franco-écossais, les Anglais virent l'assiéger. Les deux parties convinrent de régler ça par une bataille plutôt que par un long siège. John Stuart de Buchan y trouva la mort.",edesc:"After Verneuil was captured by the Franco-Scottish, the English laid siege to it. Both sides agreed to settle it with a battle rather than a long siege. John Stuart de Buchan was killed."},
                {start:"1426-03-06",text:"Bataille de Saint-James", flag:[FRANCAIS,ANGLAIS],commandants:["Richemont","Lancastre"],victoire:ANGLAIS,wiki:"Bataille_de_Saint-James_(1426)",desc:"Richemont assièga les Anglais à Saint-James, avec de nombreuses pièces d'artillerie. Les Anglais tentèrent une dernière action: ils sortirent de la ville et prirent en tenaille les Français, en criant 'Saint Georges et Salisbury!'. Croyant que le redoutable comte étaitt à la maneuvre, les Français fuirent",edesc:"Richemont laid siege to the English at Saint-James with many pieces of artillery. The English tried one last action: they went out of the town and took the French in pincers, shouting 'Saint Georges and Salisbury! Believing that the fearsome count was up to no good, the French fled the town." },
                {start:"1427-07-15",stop:"1427-09-05",text:"Siège de Montargis", flag:[FRANCAIS,ANGLAIS],commandants:["William de la Pôle","Xaintrailles","Hire","Dunois","Warwick"],victoire:FRANCAIS,wiki:"Siège_de_Montargis",desc:"Les Anglais voulaient la ville de Montargis comme quartier général pour la région. Ils en firent le siège mais le Dauphin envoya une armée de secours, commandée par le jeune Dunois. Pris entre 2 feux, les Anglais fuirent",edesc:"The English wanted the city of Montargis as headquarters for the region. They laid siege to it, but the Dauphin sent a relief army, commanded by the young Dunois. Caught in the crossfire, the English fled."},
                {start:"1428-02-13",type:BATAILLE,text:"L'Epée de Fierbois",etext:"Sword of Fierbois", scenario:true,joueurs:[2],stars:1,flag:[FRANCAIS,ANGLAIS]},
                {start:"1428-03-13",text:"Siège de Laval", flag:[FRANCAIS,ANGLAIS],commandants:["Talbot"],victoire:ANGLAIS,wiki:"Siège_de_Laval_(1428)",desc:"Talbot parvint par manque de gué à prendre la ville et la mit à sac",edesc:"Talbot managed to take the city for lack of a ford and sacked it."},
                {start:"1428-10-12",stop:"1429-05-08",text:"Siège d'Orléans", flag:[FRANCAIS,ANGLAIS,ECOSSAIS],campagne:"Campagne de la vallée de la Loire",wiki:"Siège_d'Orléans_(1428-1429)"},
                {start:"1429-02-12",text:"La bataille des Harengs",etext:"The battle of the Herrings", scenario:true,joueurs:[2,3],stars:2,type:BATAILLE, flag:[FRANCAIS,ANGLAIS,ECOSSAIS],commandants:["Derneley","Dunois","Fastolf","Charles de Bourbon","Morhier"],victoire:ANGLAIS,wiki:"Journée_des_Harengs",desc:"Le convoi transportant du poisson pour la Carême fut attaqué par les Français sortant d'Orléans. Les Anglais, retranchés derrière les chariots, gagnèrent la bataille. De Derneley y perdit la vie",campagne:"Campagne de la vallée de la Loire",edesc:"The convoy carrying fish for Lent was attacked by the French coming out of Orleans. The English, entrenched behind the wagons, won the battle. De Derneley lost his life"}, /* Jean Stuart de Buchan est mort avant cette date, 1424!! C'est bien Derneley qui est aux harengs */
                {start:"1429-02-25",text:"La cour de Chinon",etext:"Visiting Chinon",scenario:true,type:BATAILLE,flag:[FRANCAIS,ANGLAIS],joueurs:[2,4],stars:3,edesc:"Joan of Arc arrives in Chinon to meet up with the king. The Maid of Orleans doesn’t suspect that King Charles VII, wary of imminent danger, is hiding among his people to try and thwart an abduction attempt that has been planned out by the English."},
                {start:"1429-05-05",type:BATAILLE,text:"La bastille Saint-Loup",etext:"The Garrison of Saint Loup",joueurs:[2],stars:2,scenario:true,flag:[FRANCAIS,ANGLAIS],commandants:["Jeanne","Xaintrailles","Hire","Dunois","Salisbury","Talbot","Scales"],victoire:FRANCAIS,wiki:"Siège_d'Orléans_(1428-1429)",campagne:"Campagne de la vallée de la Loire"},
                {start:"1429-05-06",type:BATAILLE,text:"L'attaque des Tourelles",etext:"Assault on the Tourelles",scenario:true,joueurs:[2],stars:2,flag:[FRANCAIS,ANGLAIS],commandants:["Jeanne","Xaintrailles","Hire","Dunois","Salisbury","Talbot","Scales"],victoire:FRANCAIS,wiki:"Siège_d'Orléans_(1428-1429)",campagne:"Campagne de la vallée de la Loire"},
                {start:"1429-06-10",text:"Bataille de Jargeau", flag:[FRANCAIS,ANGLAIS],campagne:"Campagne de la vallée de la Loire",commandants:["d'Arc","William de la Pôle","Dunois","Xaintrailles","Hire","Rais"],victoire:FRANCAIS,wiki:"Bataille_de_Jargeau",desc:"Les Français s'emparèrent de Jargeau et capturèrent Suffolk (William de la Pôle)",edesc:"The French took Jargeau and captured Suffolk (William de la Pôle)."},
                {start:"1429-06-15",text:"Bataille de Meung-sur-Loire", scenario:true,type:BATAILLE,joueurs:[2,4],stars:1,flag:[FRANCAIS,ANGLAIS],wiki:"Bataille_de_Meung-sur-Loire",campagne:"Campagne de la vallée de la Loire",commandants:["Rais","d'Arc","Talbot","Scales","Dunois","Xaintrailles","Hire"],victoire:FRANCAIS,desc:"Meung-sur-Loire controlait un pont d'importance stratégique. Les Francais s'en emparèrent mais laissèrent la ville.",edesc:"fter taking back Meung-sur-Loire and its castle, Joan of Arc and Jean II d’Alençon march out to reclaim the bridge, an important strategical landmark to the south.The routed English army led by John Talbot and Thomas de Scales will do everything to defend their position."},
                {start:"1429-06-16",text:"Bataille de Beaugency", flag:[FRANCAIS,ANGLAIS],campagne:"Campagne de la vallée de la Loire",commandants:["d'Arc","Talbot","Fastolf","Dunois","Xaintrailles","Hire","Rais"],victoire:FRANCAIS,desc:"Beaugency controlait un passage stratégique sur la Loire et fut attaqué dès le pont de Meung sur Loire conquis",wiki:"Bataille_de_Beaugency",edesc:"Beaugency controlled a strategic passage on the Loire and was attacked as soon as the Meung sur Loire bridge was conquered."},
                {start:"1429-06-18",type:BATAILLE,scenario:true,text:"Bataille de Patay",joueurs:[2],stars:1, flag:[FRANCAIS,ANGLAIS],campagne:"Campagne de la vallée de la Loire",commandants:["Rais","Hire","Xaintrailles","Loré","Talbot","Scales","Fastolf","Richemont"],wiki:"Bataille_de_Patay",desc:"Bataille rangée mettant fin à la campagne de la vallée de la Loire. Les chevaliers prirent le dessus sur les archers mal préparés et les massacrèrent.",victoire:FRANCAIS,edesc:"Rowed battle putting an end to the Loire Valley campaign. The knights overcame the ill-prepared archers and massacred them"},
                {start:"1429-07-04",stop:"1429-07-16",text:"Prendre Troyes par la foi", etext:"Troyes by Faith", joueurs:[2],stars:3,scenario:true, type:BATAILLE,flag:[FRANCAIS,BOURGUIGNON],victoire:FRANCAIS,commandants:["Jeanne"],wiki:"Siège_de_Troyes"},/* Brimeu et de Croy sont morts a Azincourt */
                {start:"1429-08-15",text:"Bataille de Montépilloy", flag:[FRANCAIS,BOURGUIGNON,ANGLAIS],wiki:"Bataille_de_Montépilloy",commandants:["Jeanne","Charles d'Albret","Hire","Dunois","Rais","Lancastre"],desc:"La prudence prévalut et les armées se provoquèrent mais ne bougèrent pas, le roi Charles VII ne voulant pas reproduire les défaites précédentes. Seules quelques escarmouches eurent lieu.",edesc:"Caution prevailed and the armies provoked each other but did not move, as King Charles VII did not want to repeat the previous defeats. Only a few skirmishes took place."},
                {start:"1429-09-03",text:"Siège de Paris", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON],wiki:"Siège_de_Paris_(1429)",commandants:["d'Arc","Rais","Morhier"],victoire:ANGLAIS,desc:"La ville n'étant défendue que par 2000 Anglais, c'est le prévôt de Paris, Simon Morhier et les Parisiens qui font échouer la prise de la ville.",edesc:"As the city was defended by only 2000 Englishmen, it was the Provost of Paris, Simon Morhier and the Parisians who failed to take the city."},
                {start:"1429-09-25",text:"Siège de Laval", flag:[FRANCAIS,ANGLAIS],wiki:"Siège_de_Laval_(1429)",desc:"Un meunier, dont le moulin à eau était proche de la ville, cacha des hommes d'armes francais, les autres étaient embusqués dans un bois proche. Lorsque la garnison sortit, ils se précipitèrent dans la ville et tuèrent la garnison.",victoire:FRANCAIS,edesc:"A miller, whose watermill was close to the city, hid French men-at-arms, the others were ambushed in a nearby wood. When the garrison came out, they rushed into the city and killed the garrison."},
                {start:"1429-11",text:"Siège de Saint-Pierre-le-Moûtier", wiki:"Siège_de_Saint-Pierre-le-Moûtier",flag:[FRANCAIS,BOURGUIGNON],commandants:["d'Arc","Charles d'Albret"],desc:"Jeanne décida d'assiéger cette ville proche de Bourges. Après plusieurs assault, la ville capitula.",victoire:FRANCAIS,edesc:" Jeanne decided to lay siege to this town near Bourges. After several assaults, the town capitulated."},
                {start:"1429-11-24",stop:"1429-12-25",text:"Siège de La Charité-sur-Loire", flag:[FRANCAIS,BOURGUIGNON],wiki:"Siège_de_La_Charité-sur-Loire",commandants:["d'Arc","Charles d'Albret"],desc:"Jeanne tente de reprendre la ville. La place n'était pas très fortifiée mais bien ravitaillée. Le siège fut levé dès les prémices de l'hiver rigoureux",edesc:"Jeanne tries to retake the city. The place was not very fortified but well supplied. The siege was lifted at the beginning of the harsh winter."},
                {start:"1430-05-20",stop:"1430-10-28",text:"Siège de Compiègne", wiki:"Siège_de_Compiègne",flag:[FRANCAIS,ANGLAIS,BOURGUIGNON],commandants:["d'Arc","II de Luxembourg","Arundel"],victoire:FRANCAIS,desc:"Le siège fut effectué par l'armée bourguignonne. Jeanne d'Arc la défendit et se fit capturer et fut vendue aux Anglais pour 10000 livres. Les Français finirent par reprendre tous les quartiers de la ville.",edesc:"The siege was carried out by the Burgundian army. Joan of Arc defended it and was captured and sold to the English for 10,000 pounds. The French eventually retook all the districts of the city."},
                {start:"1430-05-23",type:BATAILLE,text:"La capture de Jeanne d'Arc",etext:"Joan of Arc's Capture in Compiègne",scenario:true,joueurs:[2,4],stars:2,flag:[FRANCAIS,ANGLAIS,BOURGUIGNON],commandants:["d'Arc","II de Luxembourg","Dunois","Xaintrailles","Hire"],victoire:BOURGUIGNON,desc:"Jeanne fit une sortie qui tourna à son désavantage.",edesc:"Joan of Arc, having just arrived in town through the woods, marches out while leading the local militia. She crosses the bridge and reaches the western shore, where the battle tilts heavily against her. She is captured with her back against the doors of the barbican leading to the bridge."},
                {start:"1431-02-19",text:"La libération de Jeanne d'Arc",etext:"Joan of Arc's Liberation",scenario:true,joueurs:[2,4],stars:3,commandants:["Lancastre","Inquisiteur","Rais","Dunois","Xaintrailles","Hire"],flag:[FRANCAIS,ANGLAIS],edesc:"Joan of Arc, captured during the siege in Compiègne, is held captive in Rouen’s prisons. Her closest friends organise an offensive to try and free her before her trial..."},
                {start:"1431-07-02",text:"Bataille de Bulgnéville", flag:[BOURGUIGNON,FRANCAIS],commandants:["Toulongeon"],wiki:"Bataille_de_Bulgnéville",campagne:"Succession du duché de Lorraine",victoire:BOURGUIGNON,desc:"Les Lorrains, en supériorité numérique, attaquent les Bourguignons sur une butte. Ceux ci, grâce à leurs archers, mettent en déroute les Lorrains.",edesc:"The Lorraine army, on a numerical superiority, attacked the Burgundians on a hill. The latter, thanks to their archers, routed the Lorraine troop."},
                {start:"1432-07",stop:"1432-08-20",text:"Siège de Lagny-sur-Marne", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON,ECOSSAIS],wiki:"Siège_de_Lagny-sur-Marne",commandants:["Xaintrailles","Hire","Rais","Dunois","Lancastre","Arundel"],victoire:FRANCAIS,desc:"Lagny était une gène pour l'approvisionnement de Paris. Une armée commandée par Jean de Lancastre l'assiégea. Le roi de France envoya une troupe de secours, et une mélée générale s'ensuivit dans une chaleur accablante. ",edesc:"Lagny was a hindrance for the supply of Paris. An army commanded by Jean de Lancastre laid siege to it. The King of France sent a relief troop, and a general meltdown ensued in the scorching heat."},
                {start:"1435-05-09",text:"Bataille de Gerberoy", flag:[FRANCAIS,ANGLAIS],wiki:"Bataille_de_Gerberoy",commandants:["Hire","Xaintrailles","Arundel"],desc:"Les Anglais vinrent assiéger Gerberoy, défendue par Xaintrailles. La Hire prit l'avant-garde anglaise par l'envers puis combattit les assiégeants. Le comte d'Arundel, blessé au pied par une couleuvrine, mourut quelques jours plus tard.",victoire:FRANCAIS,edesc:"The English came to lay siege to Gerberoy, defended by Xaintrailles. La Hire took the English vanguard in reverse and then fought the besiegers. The Count d'Arundel, wounded at the foot by a couleuvrine, died a few days later."},
                {start:"1435-09-20",text:"Traité d'Arras",flag:[FRANCAIS,BOURGUIGNON],desc:"La fin de la guerre entre Armagnacs et Bourguignons. Les Bourguignons passent du coté Français",wiki:"Traité_d'Arras_(1435)",edesc:"The end of the war between Armagnacs and Burgundians. The Burgundians pass to the French side"},
                {start:"1435-04",stop:"1436-04-17",text:"Siège de Paris", flag:[FRANCAIS,ANGLAIS],wiki:"Siège_de_Paris_(1435-1436)",commandants:["Loré","Richemont","Dunois"],desc:"Richemont surprit la garnison anglaise à Saint Denis et s'y installa en 1435. En 1436, avec le renfort des Bourguignons, les Français encerclent Paris. Les Parisiens font diversion pour obliger les Anglais à aller à une porte pendant que les Français entrent par une autre. La garnison anglaise se réfugie à la Bastille, avant d'être autorisée à s'en aller.",victoire:FRANCAIS,edesc:"Richemont surprised the English garrison at Saint Denis and settled there in 1435. In 1436, with the reinforcement of the Burgundians, the French surrounded Paris. The Parisians created a diversion to force the English to go to one gate while the French entered through another. The English garrison took refuge in the Bastille before being allowed to leave."},
                {start:"1436-07-09",stop:"1436-07-29",text:"Siège de Calais", flag:[BOURGUIGNON,ANGLAIS],commandants:["Croy","Sommerset"],victoire:ANGLAIS,desc:"Le duc de Bourgogne fit le siège de Calais, aidé par les milices flamandes. Il dut lever le siège quand celles-ci désertèrent.",wiki:"Siège_de_Calais_(1436)",edesc:"The Duke of Burgundy laid siege to Calais, with the help of the Flemish militia. He had to lift the siege when they deserted."},
                {start:"1441-08-31",stop:"1442-06-24",text:"Siège de Tartas", flag:[FRANCAIS,ANGLAIS],wiki:"Siège_de_Tartas",commandants:["Richemont","Charles d'Albret","Sommerset","Buch","Coétivy","Hire","Xaintrailles"],desc:"Repère de Charles II d'Albret en pleine Gascogne anglaise, Tartas fut assiégée par les Anglais. Une armée de secours fut alors envoyée, avec tous les grands noms français. Devant cette démonstration de force, les Anglais se rendent. C'est la dernière campagne de la Hire.",edesc:"Tartas was a stronghold of Charles II d'Albret in the middle of English Gascony and was besieged by the English. A relief army was then sent, with all the great French names. In the face of this show of strength, the English surrendered. This is the last campaign of the Hire.",victoire:FRANCAIS},
                {start:"1442-11-02",stop:"1443-08-15",text:"Siège de Dieppe", wiki:"Siège_de_Dieppe",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Talbot","Dunois"],desc:"Talbot it Dieppe en siège. Le Dauphin Louis XI parvint à faire lever le siège.",edesc:"Talbot it Dieppe under siege. The Dauphin Louis XI managed to lift the siege."},
                {start:"1449-03-23",stop:"1449-11-04",text:"Siège de Fougères", wiki:"Siège_de_Fougères_(1449)",flag:[FRANCAIS,ANGLAIS],commandants:["Richemont"],desc:"En représailles de l'emprisonnement de Gilles de Bretagne, les Anglais firent prendre Fougères par un mercenaire, François de Surienne. François 1er de Bretagne et Richemont, après d'infructueuses négociations, reprennent la ville par la force, après un siège violent, rompant une trève de 4 ans.",victoire:FRANCAIS,edesc:"In retaliation for the imprisonment of Gilles de Bretagne, the English had Fougères taken by a mercenary, François de Surienne. François I of Brittany and Richemont, after unsuccessful negotiations, took back the town by force, after a violent siege, breaking a 4-year truce."},
                {start:"1449-07-19",stop:"1449-08",type:BATAILLE,text:"Prise de Verneuil", flag:[FRANCAIS,ANGLAIS],wiki:"Prise_de_Verneuil_(1449)",victoire:FRANCAIS,desc:"La ville est prise par les Français avec la complicité d'un meunier qui laisse entrer les troupes",edesc:"The town is taken by the French with the complicity of a miller who lets the troops in."},
                {start:"1450-04-15",type:BATAILLE,scenario:true,text:"Bataille de Formigny", stars:3,joueurs:[2,6],flag:[FRANCAIS,ANGLAIS],wiki:"Bataille_de_Formigny",victoire:FRANCAIS,commandants:["Richemont","Kyriel","Goth","Jean de Bourbon"],desc:"Bataille décisive pour les Français, grâce à l'arrivée du connétable de Richemont, les Anglais sont battus. La Normandie est rapidement libérée, terminant la Guerre de cent ans au nord de la France.",edesc:"Decisive battle for the French, thanks to the arrival of Richemont, the English are defeated. Normandy is quickly liberated, ending the Hundred Years War in the north of France."},
                {start:"1450-10-19",stop:"1450-07-01",text:"Siège de Caen", wiki:"Siège_de_Caen_(1450)", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Richemont","Sommerset"],desc:"Les Anglais capitulent rapidement et rejoignent Calais",victoire:FRANCAIS,edesc:"The English surrender quickly and reach Calais."},
        {start:"1450-11-01",text:"Bataille de la Male Jornade", wiki:"Bataille_de_la_Male_Jornade",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Amanieu"],desc:"Les Français, assistés d'une compagnie d'Ecossais, tendent un piège aux Anglais. Les chevaliers anglais poursuivent une troupe qui semble faire retraite, jusqu'à un bois où ils sont massacrés par des archers. Puis les Français prennent les Anglais en tenaille et causent de lourdes pertes.",edesc:"The French, assisted by a company of Scots, set a trap for the English. The English knights pursue a troop that seems to be retreating to a wood where they are massacred by archers. Then the French take the English in pincers and cause heavy losses."},
                {start:"1453-06-25",text:"Bataille de Martignas", wiki:"Bataille_de_Martignas", commandants:["Talbot","Jean de Bourbon"],victoire:FRANCAIS,desc:"Les Français taillent en pièce l'arrière garde anglaise d'archers aux alentours de Bordeaux",flag:[FRANCAIS,ANGLAIS],edesc:"The French cut the English rearguard of archers to pieces around Bordeaux."},
                {start:"1453-07-17",text:"Bataille de Castillon", wiki:"Bataille_de_Castillon", commandants:["Talbot"],flag:[FRANCAIS,ANGLAIS],desc:"Grâce à l'artillerie, les Français gagnèrent la bataille. John Talbot y trouva la mort. Cette bataille marque la fin de la Guerre de cent ans, la Guyenne entière redevenant française peu après.",edesc:"Thanks to artillery, the French won the battle. John Talbot was killed. This battle marked the end of the Hundred Years' War, with all of Guyenne becoming French again soon after."},
                    {start:"1461-03-04",text:"Début du règne d'Edouard IV",flag:[ANGLAIS]},

                {start:"1462-06-17",scenario:true,type:BATAILLE,text:"Vlad Tepes à Targoviste",etext:"Vlad Tepes in Targoviste",joueurs:[2],stars:2,flag:[VALAQUE,OTTOMAN],commandants:["Vlad Tepes","Radu III le Beau","Mehmet II"],wiki:"Attaque_de_nuit_à_Târgoviște",desc:"Un combat de nuit entre les Valaques et les Ottomans. Vlad mena une tactique guérilla avec des escarmouches, dont la plus célèbre est cette bataille. Ils attaquèrent le camp de Mehmet II mais n'arrivèrent pas à le tuer, et se retirèrent. Démoralisé, le sultan se retira et chargea Radu de poursuivre le combat",edesc:"A night fight between the Wallachians and the Ottomans. Vlad led a guerrilla tactic with skirmishes, the most famous of which is this battle. They attacked the camp of Mehmet II but failed to kill him, and withdrew. Demoralized, the sultan withdrew and ordered Radu to continue the fight." },
                {start:"1462-06-18",scenario:true,type:BATAILLE,text:"Soif de sang",etext:"Bloodthirst",stars:2,joueurs:[2,3],flag:[VALAQUE,OTTOMAN,MAL],commandants:["Dracula","Mehmet le Conquérant"],edesc:"Led by the gigantic Mehmed the Conqueror, who is carried by his favorite djinni, the Ottoman forces destroy Vlad Tepes’ lands and reduce its people to slavery. Even Radu the Handsome, Vlad’s step brother, has allied with the Turkish invaders! Driven into a corner, Vlad Tepes reveals his darker side and becomes Dracula, the Prince of Darkness. After impaling innocents and having gorged on their blood, he summons hellish creatures to overthrow the invaders."},
                {start:"1463-04-06",text:"La chute de Constantinople", etext:"The fall of Constantinople",wiki:"Chute_de_Constantinople#Les_Byzantins",flag:[OTTOMAN],commandants:["Mehmet II"]},
                {start:"1475-08",text:"Traité de Picquigny",flag:[FRANCAIS,ANGLAIS],desc:"Ce traité signe la fin de la Guerre de cent ans",wiki:"Traité_de_Picquigny",edesc:"This treaty signs the end of the Hundred Years' War"},
               ];
    }
    constructor(e) {
        Object.assign(this,e);
        if (this.text.startsWith("Bataille")) this.type=BATAILLE;
        if (this.text.startsWith("Siège")) this.type=SIEGE;
        if (this.text.startsWith("Chevauchée")) this.type=CHEVAUCHEE;
        if (this.text.startsWith("Croisade")) this.type=CROISADE;
        if (this.text.startsWith("Début")) this.type=TRAITE;
        if (this.text.startsWith("Traité")) this.type=TRAITE;
        if (this.text.startsWith("Révolte")) this.type=REVOLTE;
        if (typeof this.type!="undefined"&&this.type!=BATAILLE)
            this.class=COULEUR_BATAILLES[this.type];
        if (this.scenario) this.text=this.text+"*";
        this.start=new Date(this.start);
    }
    static liste() {
        let i,l=[];
        let liste=Evenement.el();
        for (i=0;i<liste.length;i++) {
            let e=liste[i];
            e.id=i;
            l[i]=new Evenement(e);
            if (typeof l[i].etext=="undefined") {
                let t=l[i].text;
                t=t.replace("Bataille de","Battle of").replace("Bataille du","Battle of").replace("Bataille d'","Battle of ");
                t=t.replace("Attaque de","Attack on");
                t=t.replace("Siège de","Siege of").replace("Siège d'","Siege of ");
                t=t.replace("Combat de","Combat of");
                t=t.replace("Traité de","Treaty of");
                t=t.replace("Traité d'","Treaty of ");
                t=t.replace("Prise de","Capture of");
                if (t.startsWith("Début du règne de")) t=t.replace("Début du règne de","")+" reigns";
                if (t.startsWith("Début du règne d'")) t=t.replace("Début du règne d'","")+" reigns";
                //if (t!=l[i].text)
                    l[i].etext=t;
            }
            /*if (l[i].desc) 
                $(".fin").html($(".fin").html()+l[i].text+": "+l[i].desc+"<br>");

            if (typeof l[i].etext=="undefined") {
                console.log(l[i].text);
            }

            if (typeof l[i].flag=="undefined") {
                console.log(l[i].text);
            }*/
        }
        return l;
    }
    format(withdate) {
        let t="<span class='fr'>"+this.text+"</span><span class='en'>"+this.etext+"</span>",j;
        if (this.scenario&&withdate) {
            if (this.stars>=2) t+="*";
            if (this.stars==3) t+="*";
        }
        if (this.start&&withdate) {
            t=this.start.getFullYear()+" "+t;
        }
        if (this.flag) {
            t+=" ";
            for (j=0;j<this.flag.length;j++)
                t+="<span class='blason"+NOM_FACTION[this.flag[j]]+"'/>";
        }
        if (!withdate) return t;
        if (this.joueurs) t+=" [p"+this.joueurs.join(", p")+"]";
        return $("<span>"+t+"</span>");
    }
    info(persolist) {
        let i,s=[],ss=[],ss0=[],p="",j;

        if (typeof this.commandants!="undefined") {
            for (j=0;j<this.commandants.length;j++)  {
                let c=this.commandants[j];
                for (i=0;i<persolist.length;i++) {
                    let pl=persolist[i];
                    if (pl.text.indexOf(c)>-1) {
                        ss0.push(pl);
                        break;
                    }
                }
                if (i==persolist.length) {
                    console.log("commandant "+c+" ("+this.text+") non trouvé");
                }
            }
            ss0.sort((a,b)=>(a.faction<b.faction));
            ss=ss0/*.filter((x)=>this.flag.includes(x.faction))*/
                .map((x)=>"<span class='blason "+NOM_FACTION[x.faction]+"'>"+x.text+"</span><br/>");

        }

        for (i=0;i<persolist.length;i++) {
            let pl=persolist[i];
            if (typeof pl.dates!="undefined") {
                let es=this.start.getFullYear();
                if (pl.dates[0]<=es&&pl.dates[1]>=es) s.push(pl);
                if (pl.dates[2]<=es&&pl.dates[3]>=es) s.push(pl);
            }
        }
        s.sort((a,b)=>(a.faction<b.faction));
        s=s.filter((x)=>(this.flag.includes(x.faction)||x.faction==MERCENAIRE)&&ss0.indexOf(x)==-1)
            .map((x)=>"<span class='blason "+NOM_FACTION[x.faction]+"'>"+x.text+"</span><br/>");
        
        p="<h5 lang='fr'>"+this.text+"</h5><h5 lang='en'>"+this.etext+"</h5>";

        if (this.campagne) p+="<div class='text-muted'>"+this.campagne+"</div>";
        if (this.victoire) p+="<div class='text-muted blason "+NOM_FACTION[this.victoire]+"'><span lang='fr'>Victoire</span><span lang='en'>Victory</span> </div>";
        if (this.desc) p+="<div lang='fr' class='text-justify'>"+this.desc+"</div>";
        if (this.edesc) p+="<div lang='en' class='text-justify'>"+this.edesc+"</div>";
        if (ss.length>0) 
            p+="<div lang='fr' class='text-muted'>Liste des personnages ayant participé</div><div lang='en' class='text-muted'>List of heroes directly involved</div><div class='container cc2'>"+ss.join(' ')+"</div>";
         if (s.length>0)
             p+="<div lang='fr' class='text-muted'>Liste d'autres personnages vivants cette année</div><div lang='en' class='text-muted'>Other heroes living at this date</div><div class='container cc2'>"+s.join(' ')+"</div>";
       if (this.wiki) {
            p+="<div class='text-muted'><em><a target='_blank' href='https://fr.m.wikipedia.org/wiki/"+this.wiki+"'>"+this.text+"</a></em>, Wikipédia (<a href='"+this.source+"'&action=history'>auteurs</a>)</div>";
        }
        if (this.book) {
            p+="<div class='text-muted'><em><a target='_blank' rel='prefetch' href='r.html?page="+this.book+"'>Répertoire des combats franco-anglais de la guerre de cent ans</a></em> (Jean-Claude Castex)</div>";
        }

        return p;
    }
}

var evenements=Evenement.liste();

