const BATAILLE=0,SIEGE=1,CHEVAUCHEE=2,TRAITE=3,CROISADE=4,REVOLTE=5;
const COULEUR_BATAILLES=["col-blue","col-yellow","col-red","col-green","col-red","col-black"];

class Evenement {
    static el() {
        return [{start:"1297-09-11",text:"Bataille du Pont de Stirling", victoire:ECOSSAIS,desc:"La bataille du pont de Stirling constitue une des batailles des guerres d’indépendance de l’Écosse. Le 11 septembre 1297, les armées d'Andrew de Moray et de William Wallace affrontent celles de John de Warenne, 6e comte de Surrey, leur infligeant une défaite.",flag:[ECOSSAIS,ANGLAIS],commandants:["Wallace"],wiki:"Bataille_du_pont_de_Stirling",campagne:"Guerre d'indépendance de l'Ecosse"},
                {start:"1298-07",text:"Bataille de Falkirk", flag:[ECOSSAIS,ANGLAIS],desc:"La bataille de Falkirk, qui eut lieu en juillet 1298, marqua la fin de l'épopée de William Wallace lors de la Première Guerre d'indépendance de l'Écosse.",victoire:ANGLAIS,commandants:["Wallace"],campagne:"Guerre d'indépendance de l'Ecosse",wiki:"Bataille_de_Falkirk_(1298)"},
                {start:"1327-01-25",text:"Début du règne d'Edouard III",flag:[ANGLAIS]},
                {start:"1339-10",stop:"1339-11",text:"Siège de Cambrai",flag:[FRANCAIS,ANGLAIS],commandants:["Edouard III"],desc:"Cambrai résiste à tous les assauts des Anglais pendant 2 semaines. Les forces anglaises se retirent quand l'armée de soutien de Philippe IV arrive.",wiki:"Si%C3%A8ge_de_Cambrai_(1339)",campagne:"Chevauchée d'Edouard III"},
                {start:"1340-05-24",text:"Bataille de l'Ecluse",flag:[FRANCAIS,ANGLAIS],desc:"Une bataille navale où la flotte anglaise écrase la flotte française.",victoire:ANGLAIS,wiki:"Bataille_de_L%27%C3%89cluse_(1340)",campagne:"Chevauchée d'Edouard III"},
                {start:"1340-07-23",stop:"1340-09-25",text:"Siège de Tournai", flag:[FRANCAIS,ANGLAIS],commandants:["Edouard III","Philippe VI de Valois"],desc:"Edouard III assiège Tournai, Philippe VI approche avec une puissante armée. Jeanne de Valois, la belle-mère d'Edouard et soeur de Philippe, négocie une trève et chacun retourne en son pays.",wiki:"Si%C3%A8ge_de_Tournai_(1340)",campagne:"Chevauchée d'Edouard III"},
                {start:"1340-07-26",text:"Bataille de Saint-Omer", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,campagne:"Chevauchée d'Edouard III",desc:"L'arrière garde et les bagages de l'armée anglo-flamande est massacrée devant Saint-Omer par les Français.",wiki:"Bataille_de_Saint-Omer_(1340)"},
                {start:"1341-10-14",text:"Bataille de Champtoceaux", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:FRANCAIS,desc:"La bataille inaugure le conflit dynastique en Bretagne, opposant Charles de Blois à Jean de Montfort, soutenu par les Anglais. Les deux rivaux s'opposent pendant 2 jours près d'une ferme et finalement Jean de Montfort s'enfuie à Nantes.",commandants:["Brienne"],wiki:"Bataille_de_Champtoceaux"},
                {start:"1342-04",text:"Bataille de Quimperlé", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:ANGLAIS,desc:"Louis de la Cerda , commandant de l'armée de Charles de Blois de 6000 hommes, rencontre 3000 archers anglais. Les premiers finissent par fuir.",wiki:"Bataille_de_Quimperl%C3%A9"},
                {start:"1342-05",start:"1342-06",text:"Siège d'Hennebont", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:ANGLAIS,wiki:"Si%C3%A8ge_d%27Hennebont",desc:"Les troupes montfortistes font le siège d'Hennebont, dans laquelle est Jeanne de Flandre, mère de Jean de Montfort. Grace à des ruses, Jeanne parvient à sortir de la ville et revient avec des renforts. Le siège est levé par la suite."},
                {start:"1342-12-05",stop:"1343-01-19",text:"Siège de Vannes", flag:[FRANCAIS,ANGLAIS,BIEN],victoire:BIEN,campagne:"Guerre de succession de Bretagne",commandants:["Edouard III","Salisbury"],desc:"Quatre sièges successifs et la ville sera remise aux légats du pape, après intervention du pape Clément VI",wiki:"Si%C3%A8ges_de_Vannes_(1342)"},
                {start:"1342-09-19",text:"Bataille de Morlaix", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:FRANCAIS,commandants:["Northampton"],wiki:"Bataille_de_Morlaix",desc:"Northampton, assiegeant Morlaix, intercepte l'armée Francaise-Bretonne de Charles de Blois qui vient libérer la ville"},
                {start:"1345-06-17",text:"Bataille de Cadoret", campagne:"Guerre de succession de Bretagne",wiki:"Bataille_de_Cadoret",flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,desc:"Charles de Blois combat Thomas Dagworth toute une après-midi. Pris sous une pluie de flèches, l'armée de Charles de Blois subit de nombreuses pertes."},
                {start:"1345-08",text:"Bataille de Bergerac", flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,desc:"Les armées anglo-gasconnes commandées par le comte de Derby combattent les Français autour du pont de Bergerac qui est sur la frontière de la Gascogne (anglaise) et devant les murs, avant la prise de la ville.",wiki:"Bataille_de_Bergerac"},
                {start:"1345-10-21",text:"Bataille d'Auberoche", flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,desc:"Les anglo-gascons commandés par le comte de Derby, en infériorité numérique attaquent les Français pendant le déjeuner. Déroute totale des Français.",victoire:ANGLAIS,wiki:"Bataille_d%27Auberoche"},
                {start:"1346-06-09",text:"Bataille de Saint-Pol-de-Léon", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:ANGLAIS,desc:"Charles de Blois lance des multiples assauts frontaux de fantassins contre des archers anglais retranchés. Il ne peut remporter la victoire et du retourner dans ses bastions.",wiki:"Bataille_de_Saint-Pol-de-L%C3%A9on"},
                {start:"1346-07-02",stop:"1347-10-12",text:"Chevauchée d'Édouard III", flag:[FRANCAIS,ANGLAIS],wiki:"Chevauch%C3%A9e_d%27%C3%89douard_III_(1346)",campagne:"Chevauchée d'Edouard III (1346)",commandants:["Edouard III","Prince Noir","Warwick","Northampton","Chandos","Jean 1er de Luxembourg","Arundel"]},
                {start:"1346-07-26",text:"Siège de Caen", flag:[FRANCAIS,ANGLAIS],campagne:"Chevauchée d'Edouard III (1346)",victoire:ANGLAIS,commandants:["Edouard III","Le Prince Noir","Warwick","Northampton"],wiki:"Si%C3%A8ge_de_Caen_(1346)",desc:"Prise de la ville française, peu défendue et pillage."},
                {start:"1346-08-24",text:"Bataille du gué de Blanquetaque",campagne:"Chevauchée d'Edouard III (1346)",victoire:ANGLAIS,commandants:["Edouard III","Le Prince Noir","Warwick","Northampton"], flag:[FRANCAIS,ANGLAIS],desc:"La bataille se déroule au milieu du gué de la Somme.",wiki:"Bataille_du_gu%C3%A9_de_Blanquetaque",desc:"L'armée anglaise se retrouve sur un gué devant la Somme, avec une armée française sur la rive opposée. Quelques Anglais traversent et les Français se précipitent à leur rencontre dans le fleuve."},
                {start:"1346-08-26",type:BATAILLE,scenario:true,campagne:"Chevauchée d'Edouard III (1346)",victoire:ANGLAIS,commandants:["Edouard III","Le Prince Noir","Northampton","Philippe VI le Valois","Chandos","Jean 1er de Luxembourg","Arundel","Charles II"],text:"La bataille de Crécy",joueurs:[2],stars:2,flag:[FRANCAIS,ANGLAIS],desc:"Sur le chemin de retour de sa chevauchée, Edouard III obtient une victoire écrasante face à l'armée de Philippe VI, pourtant supérieure numériquement."},
                {start:"1346-09-04",stop:"1347-08-03",type:SIEGE,scenario:true,text:"Siège de Calais", campagne:"Chevauchée d'Edouard III (1346)",joueurs:[2],stars:2,flag:[FRANCAIS,ANGLAIS],commandants:["Jean de Vienne","Edouard III"],victoire:ANGLAIS,desc:"6 bourgeois de Calais, la corde au cou, pieds nus et en chemise, se rendent à Edouard III pour épargner la ville.",wiki:"Si%C3%A8ge_de_Calais_(1346-1347)"},/* Jean de Vienne a 5 ans */
                {start:"1346-10-17",text:"Bataille de Neville's Cross", victoire:ANGLAIS,flag:[ECOSSAIS,ANGLAIS],wiki:"Bataille_de_Neville%27s_Cross",desc:"Espérant vaincre les Anglais alors concentrés en France, les Ecossais avec le roi David II envahissent le nord de l'Angleterre. Ils se heurtent à une force bien retranchée qui les bat et capture le roi.",},
                {start:"1347-06-18",text:"Bataille de La Roche-Derrien", flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,campagne:"Guerre de succession de Bretagne",wiki:"Bataille_de_La_Roche-Derrien",desc:"Les anglo-monfortistes commandés par Thomas Dagworth gagnent contre les Bretons de Charles de Blois. Celui-ci est fait prisonnier."},
                {start:"1348-02",type:BATAILLE,scenario:true,text:"La Peste",flag:[BIEN,MAL]},
                {start:"1349-07",text:"Bataille de Lunalonge", commandants:["Captal","Boucicaut"],flag:[FRANCAIS,ANGLAIS],desc:"Un raid des Français contre les Anglais. La bataille a lieu sur une colline occupée par les Anglais, combattant avec des lances. Boucicaut est capturé.",wiki:"Bataille_de_Lunalonge"},
                {start:"1349-12-31",stop:"1350-01-01",text:"Siège de Calais", flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,commandants:["Edouard III","Salisbury","Suffolk"],desc:"Le gouverneur de Calais s'apprête à livrer Calais aux Français. Edouard III l'apprend et embusque les Français."},
                {start:"1350-06",text:"Combat de Fougeray",flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Guesclin"],campagne:"Guerre de succession de Bretagne",desc:"Du Guesclin prend par ruse ce faubourg de Rennes. Se faisant passer pour des paysans, transportant du bois dans des chariots pour couvrir leurs armes, ils s'introduisent dans la ville après le départ d'une troupe. Ils bloquent la herse et le pont levis avec le bois et les chariots et les 31 hommes du commando massacrent les 100 hommes de la garnison. Le diner préparé par les Anglais fut mangé par les Français",book:"185"},
                {start:"1351-06",text:"Bataille de Saintes", flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,desc:"Les Français, assiégeant Saintes, sont mis en déroute par une armée de secours anglaise.",wiki:"Bataille_de_Saintes"},
                {start:"1351-03",stop:"1351-08-07",text:"Siège de Saint-Jean-d'Angély", flag:[FRANCAIS,ANGLAIS],commandants:["Jean II","Amanieu"],victoire:FRANCAIS,desc:"Un siège Français sur une petite ville non stratégique. La ville se rend sans combat.",wiki:"Si%C3%A8ge_de_Saint-Jean-d%27Ang%C3%A9ly_(1351)"},
                {start:"1351-03-26",type:BATAILLE,text:"Combat des Trente", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",commandants:["Knolles"],victoire:FRANCAIS,wiki:"Combat_des_Trente",desc:"À la suite d'un défi lancé par Jean IV de Beaumanoir, un combat est organisé entre trente partisans de Charles de Blois et trente partisans de Jean de Montfort"},
                {start:"1351-06-06",text:"Bataille d'Ardres", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,desc:"Les Anglais sont vaincus après êtres pris par une armée Française alors qu'ils se retiraient d'un raid.",wiki:"Bataille_d%27Ardres"},
                {start:"1352-08-14",text:"Bataille de Mauron", flag:[FRANCAIS,ANGLAIS],campagne:"Guerre de succession de Bretagne",victoire:ANGLAIS,wiki:"Bataille_de_Mauron",desc:"Les Français attaquent les Anglais sur une colline, forcent les archers à combattre comme des fantassins mais finissent par se faire battre puis massacrer. Les pertes furent importantes des deux cotés."},
                {start:"1354-04-10",text:"Bataille de Montmuran", campagne:"Guerre de succession de Bretagne",commandants:["Guesclin"],victoire:FRANCAIS,flag:[FRANCAIS,ANGLAIS],desc:"Les Franco-Bretons dirigés par Du Guesclin se vengent de la bataille de Mauron.",wiki:"Bataille_de_Montmuran"},
                {start:"1355-10-10",stop:"1355-12-09",text:"Chevauchée du Prince noir", commandants:["Prince Noir"],flag:[FRANCAIS,ANGLAIS]},
                {start:"1356-08-04",stop:"1356-09-19",scenario:true,type:CHEVAUCHEE,type:CHEVAUCHEE,text:"La Chevauchée du Prince Noir",flag:[FRANCAIS,ANGLAIS],commandants:["Prince Noir"],joueurs:[2,4],stars:3,campagne:"Chevauchée du Prince Noir"}, /* TODO: Boucicaut n'est pas la */
                {start:"1356-09-01",type:BATAILLE,text:"La bataille de Romorantin", flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,commandants:["Clermont","Romorantin","Boucicaut","Craon"],book:"329",desc:"Avant la bataille de Poitiers, l'avant garde française embusque les éclaireurs Anglais. La stratégie anglaise a consisté à esquiver le choc de la charge des Français et à se retourner pour les attaquer immédiatement dans le dos.",campagne:"Chevauchée du Prince Noir"},
                {start:"1356-09-19",scenario:true,type:BATAILLE,text:"La bataille de Poitiers", joueurs:[2,6],stars:3,flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,commandants:["Jean II","Le Prince Noir","Salisbury","Philippe d'Orléans","Andrehem","Gautier VI","Clermont","Chandos","Warwick","Captal"],wiki:"Bataille_de_Poitiers_(1356)",desc:"Déroute francaise, Jean II est capturé.",campagne:"Chevauchée du Prince Noir"},
                {start:"1356-10-03",stop:"1357-06-30",text:"Siège de Rennes",flag:[ANGLAIS,FRANCAIS],wiki:"Si%C3%A8ge_de_Rennes_(1356-1357)",victoire:ANGLAIS,campagne:"Guerre de succession de Bretagne",commandants:["Guesclin"],desc:"Les Anglais ont pour stratégie d'affamer la ville mais les défenseurs usent de ruse. Les Anglais font paitre devant les portes des troupeaux de porc, pour attirer les Rennais hors de la ville. Le capitaine de la ville fait suspendre une truie qui par ses cris attirent les cochons dans la ville! Enfin Du Gueslin entre dans la ville avec des charettes de vivre par ruse, en faisant croire à des mercenaires allemands. La ville paie une rançon finalement."},
                {start:"1356-12",type:BATAILLE,scenario:true, text:"Du Guesclin au siège de Rennes",joueurs:[2],stars:1,flag:[ANGLAIS,FRANCAIS],commandants:["Guesclin"],campagne:"Guerre de succession de Bretagne"}, /* TODO: Un an plus tot que le scenario*/
                {start:"1358-04-18",stop:"1358-08-02",text:"Siège de Paris", flag:[FRANCAIS,AUTRE],desc:"Charles le Dauphin reprend Paris à Etienne Marcel et Charles le Mauvais",victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Paris_(1358)",campagne:"Grande Jacquerie"},
                {start:"1358-06-09",text:"Siège de Meaux", flag:[FRANCAIS,AUTRE],wiki:"Si%C3%A8ge_de_Meaux_(1358)",campagne:"Grande Jacquerie",victoire:FRANCAIS,commandants:["Buch"],desc:"Des paysans révoltés par les ravages de la guerre, la peste, font le siège du marché de Meaux, où sont les princesses dont la femme du Dauphin. Le comte de Foix et Captal de Buch délivrent les princesses"},
                {start:"1358-06-01",text:"Bataille de Longeuil Sainte Marie", flag:[FRANCAIS,AUTRE],wiki:"Si%C3%A8ge_de_Meaux_(1358)",campagne:"Grande Jacquerie",victoire:AUTRE,desc:"Des paysans révoltés par les ravages de la guerre, la peste, s'en prennent aux troupes d'occupation anglaises. Guillaume d'Aloue puis le Grand Ferré commandent les paysans. La bataille se fait autour d'un corps de ferme et de l'église du village."},
                {start:"1358-08-01",stop:"1359-04-29",text:"Siège de Saint-Valery", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Saint-Valery",desc:"Les Français assiègent et prennent la ville des mains du roi de Navarre, Charles le Mauvais"},
                {start:"1358-09-16",text:"Bataille d'Amiens", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,wiki:"Bataille_d%27Amiens_(1358)",desc:"Les partisans de Charles le Mauvais essaient de prendre Amiens alors qu'une nouvelle enceinte était en construction"},
                {start:"1359-10-28",stop:"1360-05-08",text:"Chevauchée d'Edouard III", flag:[FRANCAIS,ANGLAIS],campagne:"Chevauchée d'Edouard III (1359)"},
                {start:"1359-12-20",stop:"1360-01-11",text:"Siège de Reims",commandants:["Edouard III"],campagne:"Chevauchée d'Edouard III (1359)",flag:[FRANCAIS,ANGLAIS],desc:"Le siège est abandonné, faute de matériel de siège.",wiki:"Si%C3%A8ge_de_Reims",victoire:FRANCAIS},
                {start:"1360-03-12",text:"Attaque de Winchelsea", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,desc:"Un raid francais en Angleterre pour libérer Jean II, supposé être à Winchelsea."},
                {start:"1360-03-31",stop:"1360-04-12",text:"Siège de Paris", flag:[FRANCAIS,ANGLAIS],commandants:["Edouard III"],campagne:"Chevauchée d'Edouard III (1359)",victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Paris_(1360)",desc:"Les Anglais campent dans les faubourgs. Charles le Dauphin refuse le combat. Les Anglais doivent lever le siège."},
                {start:"1360-03-31",text:"Siège de l'église fortifiée de Chastres",flag:[FRANCAIS,ANGLAIS],commandants:["Edouard III"],campagne:"Chevauchée d'Edouard III (1359)",victoire:ANGLAIS,desc:"Les Anglais passent le temps autour d'une église fortifiée.",book:"125"},
                {start:"1360-04-13",text:"Lundi noir", victoire:BIEN,flag:[ANGLAIS,BIEN],commandants:["Edouard III","Le Prince Noir","Warwick"],campagne:"Chevauchée d'Edouard III (1359)",victoire:FRANCAIS,desc:"Un orage décime les troupes anglaises, et conclue la chevauchée d'Edouard III",wiki:"Lundi_noir_(1360)"},
                {start:"1360-05",text:"Traité de Brétigny",flag:[FRANCAIS,ANGLAIS],wiki:"Trait%C3%A9_de_Br%C3%A9tigny"},
                {start:"1361-04",text:"Bataille de Briouze", flag:[FRANCAIS,MERCENAIRE],commandants:["Guesclin"],victoire:FRANCAIS,campagne:"Campagne contre les grandes compagnies",desc:"La flatterie fut l'élément essentiel qu'utilisèrent les Anglais pour que Du Guesclin les laisse se déployer en rase campagne afin qu'ils puissent utiliser toutes leurs forces",book:"99"},
                {start:"1362-04",text:"Bataille de Mortain",flag:[FRANCAIS,MERCENAIRE],commandants:["Guesclin"],victoire:FRANCAIS,campagne:"Campagne contre les grandes compagnies"},
                {start:"1362-04",text:"Bataille de Livarot", flag:[FRANCAIS,ANGLAIS,MERCENAIRE],commandants:["Jouel","Guesclin"],victoire:FRANCAIS,campagne:"Campagne contre les grandes compagnies",book:"223"},
                {start:"1362-04-06",scenario:true,type:BATAILLE,text:"La bataille de Brignais", joueurs:[2,3,4],stars:3,flag:[FRANCAIS,MERCENAIRE],victoire:MERCENAIRE,commandants:["Seguin","Meschin","Jacques de Bourbon"],campagne:"Campagne contre les grandes compagnies",wiki:"Bataille_de_Brignais"},
                {start:"1362-04",text:"Bataille de Saint-Martin-de-Seez", flag:[FRANCAIS,MERCENAIRE],victoire:FRANCAIS,commandants:["Guesclin"],campagne:"Campagne contre les grandes compagnies",book:"342",desc:"Du Guesclin força 3 Grandes Compagnies anglaises à capituler"},
                {start:"1364-03",stop:"1364-04-09",text:"Siège de Rolleboise", flag:[FRANCAIS,MERCENAIRE],commandants:["Guesclin","Auxerre"],victoire:FRANCAIS,campagne:"Campagne contre les grandes compagnies",wiki:"Si%C3%A8ge_de_Rolleboise"},
                {start:"1364-04-07",text:"Siège de Mantes", flag:[FRANCAIS,ANGLAIS],campagne:"Reconquête contre Charles le Mauvais",victoire:FRANCAIS,commandants:["Guesclin","Boucicaut"],wiki:"Si%C3%A8ge_de_Mantes",desc:"Boucicaut et Du Guesclin reprennent la ville à Charles le Mauvais par ruse, afin de ne pas lever le siège de Rolleboise: Boucicaut se présente avec 100 chevaux et fait semblant d'être poursuivi par des brigants. Les gardiens ouvrent et Du Guesclin en profite pour entrer et piller la ville"},
                {start:"1364-04-10",text:"Siège de Meulan", flag:[FRANCAIS,ANGLAIS],commandants:["Guesclin","Boucicaut"],victoire:FRANCAIS,campagne:"Reconquête contre Charles le Mauvais",wiki:"Si%C3%A8ge_de_Meulan",desc:"Boucicaut et Du Guesclin reprennent la ville à Charles le Mauvais par ruse, afin de ne pas lever le siège de Rolleboise: Du Guesclin se fait passer pour un envoyé du roi de Navarre. On lui ouvre les portes et la ville est pillée et massacrée"},
                {start:"1364-05-16",text:"Bataille de Cocherel", flag:[FRANCAIS,ANGLAIS,MERCENAIRE],stars:3,joueurs:[2,3],commandants:["Guesclin","Auxerre","Captal","Amanieu","Cervole","Jouel","Lens"],campagne:"Reconquête contre Charles le Mauvais",victoire:FRANCAIS,wiki:"Bataille_de_Cocherel",desc:"Les troupes du roi de France s'opposent à celles de Charles le Mauvais"},
                {start:"1365-09-29",text:"Bataille d'Auray", flag:[FRANCAIS,ANGLAIS],wiki:"Bataille_d%27Auray",victoire:ANGLAIS,commandants:["Guesclin","Chandos","Knolles","Auxerre"],desc:"Bataille décisive met fin à la guerre de succession de Bretagne. Charles de Blois est tué et Jean IV de Bretagne victorieux. Du Guesclin est fait prisonnier.",campagne:"Guerre de succession de Bretagne"},
                {start:"1367-04-03",text:"Bataille de Nájera", flag:[FRANCAIS,ANGLAIS],wiki:"Bataille_de_N%C3%A1jera",victoire:ANGLAIS,commandants:["Guesclin","Prince Noir","Chandos","Buch","Albret"]/*TODO: Albret est avec les anglais*/,desc:"Les Anglais commandés par le Prince Noir, en soutien à Pierre le Cruel, combattent les troupes françaises menées par Du Guesclin, soutenant Henri II de Castille. Du Guesclin sera capturé.", campagne:"Guerre civile de Castille"},
                {start:"1369-03-14",text:"Bataille de Montiel", flag:[FRANCAIS],campagne:"Guerre civile de Castille",victoire:FRANCAIS,commandants:["Guesclin"],wiki:"Bataille_de_Montiel",desc:"Bataille décisive de Henri II de Castille grâce à ses soutiens français. Pierre le Cruel est tué quelques jours plus tard."},
                {start:"1369-06",text:"Bataille de Lusignan", flag:[FRANCAIS,ANGLAIS],book:"342",victoire:FRANCAIS},
                {start:"1369-07-01",stop:"1369-07-30",text:"Siège de La Roche-Posay",victoire:FRANCAIS,flag:[FRANCAIS,ANGLAIS],book:"327",desc:"Siège de la ville par les Français pour faire respecter le traité de Brétigny"},
                {start:"1369-12-31",text:"Siège de Saint-Savin-sur-Gartempe", flag:[FRANCAIS,ANGLAIS],book:"343",victoire:FRANCAIS,commandants:["Chandos"],desc:"Les Anglais commandés par Chandos essaient de prendre la ville par surprise, mais sont surpris par hasard par les Francais."},
                {start:"1370-01-01",type:BATAILLE,text:"Combat du Pont de Lussac",book:"342", victoire:FRANCAIS,commandants:["Chandos"],desc:"Les Français faisant une chevauchée dans le Poitou anglais, sont rattrappés par 2 armées anglaises au pont de Lussac. La bataille a notamment lieu sur le pont, étroit et bombé. Les Français furent vaincus mais la mort du grand capitaine anglais John Chandos fut une catastrophe pour l'Angleterre.",flag:[FRANCAIS,ANGLAIS]},
                {start:"1370-09-19",text:"Sac de Limoges", flag:[FRANCAIS,ANGLAIS],wiki:"Sac_de_Limoges",victoire:ANGLAIS,desc:"Les Anglais après un court sièege pillent Limoges en représailles, après que celle ci a ouvert ses portes aux armées françaises. Le Prince Noir est venu en personne, bien que malade. Cet événement a contribué à la réputation négative du Prince Noir chez les Français",commandants:["fils du Roi","Prince Noir","Jean de Lancastre"]},
                {start:"1370-09-23",text:"Siège de Paris", flag:[FRANCAIS,ANGLAIS],wiki:"Si%C3%A8ge_de_Paris_(1370)",desc:"Robert Knolles part de Calais et avec une armée anglaise, pille la campagne et se présente à Paris en incendiant les villages alentours. Charles V refuse de miser sa couronne sur une bataille et refuse le combat. Après 2 jours d'incendies et de pillage des faubourgs, Knolles se retire",commandants:["Knolles"]},
                {start:"1370-12-04",text:"Bataille de Pontvallain", flag:[FRANCAIS,ANGLAIS],wiki:"Bataille_de_Pontvallain",commandants:["Vienne","Guesclin","Knolles","Audrehem"],desc:"Du Guesclin partit à la poursuite de Knolles après le siège de Paris et le harcela. Il combat l'arrière garde de l'armée anglaise à Pontvallain. Toute l'arrière garde fut massacrée.",victoire:FRANCAIS},
                {start:"1372-06",text:"Siège de Guernesey", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Guernesey",desc:"Sous les ordres de Owain le Gallois, prétendant à la principauté de Galles, les troupes françaises débarquent à Guernesey. C'est une diversion pour le siège de la Rochelle. L'expédition doit être abandonnée quand Owain est rappelé par Charles V pour La Rochelle"},
                {start:"1372-06-22",stop:"1372-08-23",text:"Siège de La Rochelle", flag:[FRANCAIS,ANGLAIS],wiki:"Si%C3%A8ge_de_La_Rochelle_(1372)",commandants:["Guesclin"],victoire:FRANCAIS,desc:"Les Rochelais chassent la garnison anglaise à l'aide d'une ruse du maire. Le maire invite le commandant anglais à diner et lui fait passer un document avec un sceau d'Edouard III comme d'un ordre pour faire sortir ses troupes sur la place, le commandant ne sachant pas lire. Les Rochelais armés les attendaient et laissent entrer Du Guesclin après avoir négocié des avantages pour la  ville."},
                {start:"1372-08-22",text:"Siège de Soubise", flag:[FRANCAIS,ANGLAIS],commandants:["Buch"],victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Soubise",desc:"Ce siège met fin à l'emprise anglaise sur la Saintonge. Owain le Gallois attaque par surprise l'armée anglaise de Jean de Grailly, captal de Buch, qui est capturé. Il restera emprisonné à Paris jusqu'à sa mort."},
                {start:"1373-03-21",text:"Bataille de Chizé", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Guesclin"],book:"135",desc:"La bataille est autour du chateau de Chizé que Du Guesclin assiège. Quand l'armée de secours anglaise arrive, Du Guesclin met sur son chemin un convoi de barriques de vin. Une fois l'armée de secours très éméchée, Du Guesclin l'attaque. Les assiégés sortent alors et se font massacrer."},
                {start:"1373-06-12",stop:"1373-12",text:"Chevauchée de Lancastre", flag:[FRANCAIS,ANGLAIS],commandants:["Jean de Lancastre"],wiki:"Chevauchée_de_Lancastre_(1373)",desc:"Chevauchée de Jean de Lancastre avec au final un maigre butin et une armée qui est l'ombre de celle qui a commencé la chevauchée, Charles V et Du Guesclin ayant refusé de la combattre et fait la politique de la terre brulée."},
                {start:"1373-06-16",stop:"1373-06-28",text:"Siège de Mauvezin", flag:[FRANCAIS,ANGLAIS],book:"245",desc:"La garnison anglaise de Mauvezin pille les environs. Le duc d'Anjou décide de reprendre le chateau aux Anglais. Sans réserve d'eau (mais pas sans vin), les Anglais capitulent.",victoire:FRANCAIS},
                {start:"1374-06",text:"Siège de Bayonne", flag:[FRANCAIS,ANGLAIS],victoire:ANGLAIS,desc:"Henri II de Castille cherche à reprendre la ville aux Anglais, avec l'aide des Français notamment Louis d'Anjou. Ce dernier reste à Toulouse, Henri II finit par lever le siège",wiki:"Si%C3%A8ge_de_Bayonne_(1374)"},
                {start:"1376-09",scenario:true,type:BATAILLE,text:"L'offensive contre Plymouth",joueurs:[4],stars:3, flag:[FRANCAIS]},
    {start:"1377-06-21",text:"Début du règne de Richard II",flag:[ANGLAIS]},
                {start:"1377-06-29",type:CHEVAUCHEE,text:"Raid sur Rye", flag:[FRANCAIS,ANGLAIS],commandants:["Vienne"],desc:"Une expédition de pillage suite à la mort d'Edouard III et la fin de la trève de Bruges entre France et Angleterre. Les paysans n'opposèrent qu'une défense molle, la ville fut brulée. Les Anglais pendirent des paysans, outrés par la faible défense.",victoire:FRANCAIS,book:"339"},
                {start:"1377-07",text:"Bataille de Lewes", flag:[FRANCAIS,ANGLAIS],commandants:["Vienne"],book:"221",desc:"Un coup de force contre la ville de Rottingdean. Le prieur du monastère de Lewes défendit la ville farouchement avec ses habitants et des paysans. Pas de garnison dans cette ville",victoire:FRANCAIS},
                {start:"1377-08-21",text:"Bataille de l'île de Wight", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Vienne"],book:"206",desc:"Bataille sur la plage. Les Français s'emparent de toute l'île sauf du chateau, et repartent avec une somme d'argent payée par les habitants pour préserver leurs maisons"},
                {start:"1377-08-22",text:"Bataille de Yarmouth", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Vienne"],book:"372",desc:"La ville fut prise d'assaut à l'aide d'échelle et détruite par les Français"},
                {start:"1377-07-01",stop:"1377-09",text:"Siège de Bergerac", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["Guesclin"],desc:"Le duc d'Anjou fait le siège et est rejoint par Du Guesclin en août. Il fait chercher une tour de siège qui permet de gagner la ville",source:"http://riviereesperance.canalblog.com/archives/2016/05/10/33697129.html"},
                {start:"1377-09-01",text:"Bataille d'Eymet", victoire:FRANCAIS,flag:[FRANCAIS,ANGLAIS],book:"175",desc:"Pour sortir le siège de Bergerac de son enlisement, Du Guesclin envoie chercher une tour de siège à la Réole. Le sénéchal de Guyenne Sir Thomas Felton en a vent et décide de tendre une embuscade à Eymet. L'embuscade se fait déborder et les Anglais paniquent et se font massacrer. La tour parvient à Bergerac."},
                {start:"1378-08-14",stop:"1378-09",text:"Siège de Saint-Malo", flag:[FRANCAIS,ANGLAIS],wiki:"Si%C3%A8ge_de_Saint-Malo",victoire:FRANCAIS,commandants:["Lancastre","Guesclin"],desc:"Les Anglais veulent reprendre ce port stratégique. Lancastre fait bombarder la ville jusqu'à l'arrivée d'une armée de renfort commandée par Du Guesclin. Il essaie ensuite de saper les murailles, mais un miracle fait découvrir la sape aux malouins. Lancastre abandonne alors le siège"},
                {start:"1380-06-20",stop:"1380-06-26",text:"Siège de Chaliers", flag:[FRANCAIS,MERCENAIRE],book:"123",campagne:"Contre les grandes compagnies anglo-gasconnes",commandants:["Guesclin","Badefol"],desc:"Le Languedoc et le Massif Central étant continuellement troublés par des incursions des grandes compagnies, le roi y envoie Du Guesclin. Les Français bombardèrent pendant une semaine le chateau, ouvrant une brèche dans le mur. Les assiégés capitulèrent",victoire:FRANCAIS},
                {start:"1380-02-28",stop:"1380-07-14",text:"Siège de Châteauneuf-de-Randon", flag:[FRANCAIS,ANGLAIS,MERCENAIRE],campagne:"Contre les grandes compagnies anglo-gasconnes",commandants:["Guesclin","Badefol"],book:"129",desc:"Le Languedoc et le Massif Central étant continuellement troublés par des incursions des grandes compagnies, le roi y envoie Du Guesclin. Comme pour Chaliers, un siège en règle est établi. Du Guesclin meurt de maladie pendant le siège, à 60 ans, le jour de la capitulation de la ville."},
                {start:"1380-11-08",stop:"1381-01-14",text:"Siège de Nantes", flag:[FRANCAIS,ANGLAIS],commandants:["Knolles"],victoire:FRANCAIS,wiki:"Si%C3%A8ge_de_Nantes_(1380-1381)",desc:"Les Anglais assiègent Nantes avec une force de 6000 hommes comme 2000 hommes de garnison. Après 2 mois de siège, les Anglais, malades de dysenterie et famine, décident de lever le siège"},
                {start:"1381-03",text:"Tournoi de Vannes", flag:[FRANCAIS,ANGLAIS],wiki:"Tournoi_de_Vannes",desc:"Un tournoi affrontant 5 chevaliers anglais contre 5 chevaliers français, en hommage au combat des Trente, 30 ans plus tôt. Les adversaires doivent se donner 5 coups de lance, 5 coups d'épée, 5 coups de hache puis 5 coups de dague. Les Français ne perdent aucun combat",victoire:FRANCAIS},
    {start:"1382-06-29",type:BATAILLE,scenario:true,text:"La revanche de la Tarasque",stars:3,joueurs:[3],flag:[FRANCAIS,MAL,BIEN]},
    {start:"1382-07-29",type:BATAILLE,scenario:true,text:"L'Enfant",joueurs:[2],stars:3,flag:[MAL,BIEN]},
                {start:"1382-11-27",text:"Bataille de Roosebeke", flag:[FRANCAIS,AUTRE],wiki:"Bataille_de_Roosebeke",commandants:["Hardi"],campagne:"Révolte des Tisserands de Gand",desc:"Lors de la révolte des tisserands gantois, le comte de Flandres fait appel à son gendre Philippe le Hardi. Philippe van Artevelde commande les troupes flamandes. Il meurt dans la bataille.",victoire:FRANCAIS,wiki:"Bataille_de_Roosebeke"},
                {start:"1382-12-21",stop:"1383-09-17",text:"Croisade d'Henri le Despenser", flag:[FRANCAIS,ANGLAIS],commandants:["Hardi"],wiki:"Croisade_d'Henri_le_Despenser"},
                {start:"1383-06-08",stop:"1383-08-08",text:"Siège d'Ypres", flag:[FRANCAIS,ANGLAIS],wiki:"Siège_d'Ypres_(1383)",desc:"Le siège fini par être levé par les Anglais.",campange:"Croisade d'Henri le Despenser"},
    {start:"1383-12-25",type:BATAILLE,text:"La Croix du Loup-Pendu",scenario:true,joueurs:[2],stars:2,flag:[FRANCAIS,MAL]},
                {start:"1385-07",text:"Siège de Wark", flag:[FRANCAIS,ANGLAIS,ECOSSAIS],commandants:["Vienne"],wiki:"Siège_de_Wark",victoire:FRANCAIS,desc:"L'amiral Jean de Vienne débarque en Ecosse afin de prendre à revers les Anglais. Les Français, avec leurs alliés écossais, mènent un siège efficace de la forteresse de Wark, un poste frontalier, et la prennent."},
                {start:"1385-08-14",text:"Bataille d'Aljubarrota", commandants:["Lancastre"],flag:[FRANCAIS,ANGLAIS]/* Boulangere tueuse */,desc:"Le roi Jean Ier de Castille envahit le Portugal à l'occasion d'une crise de succession pour le Portugal. Il est soutenu par les Français, les Portugais par les Anglais. La défaite est sévère pour les Espagnols. Selon une légende portugaise, une femme dénommée la boulangère d'Aljubarrota élimine plusieurs soldats castillans ayant déserté le combat, en les enfermant tour à tour dans son fourneau de pain, prétendument pour les cacher des Portugais et en les tuant de sa pelle quand ils essayaient d'en sortir.",wiki:"Bataille_d'Aljubarrota" },
                {start:"1388-08-19",text:"Bataille d'Otterburn",flag:[ANGLAIS,ECOSSAIS],victoire:ECOSSAIS,wiki:"Bataille_d'Otterburn",desc:"Une victoire décisive des Ecossais. Inquiet des mouvements écossais, le roi d'Angleterre Richard II signa un traité de paix avec Charles VI"},
                {start:"1395-05-17",text:"Bataille de Rovines", flag:[VALAQUE,OTTOMAN],victoire:VALAQUE,wiki:"Bataille_de_Rovine",campagne:"Campagne du Danube"},
                {start:"1396-09-25",text:"Bataille de Nicopolis", flag:[OTTOMAN,FRANCAIS,ANGLAIS,VALAQUE],campagne:"Campagne du Danube",victoire:OTTOMAN,commandants:["Boucicaut","Jacques de Bourbon"],desc:"L'armée chrétienne assiège Nicopolis. Le sultan Bajazet Ier vient au secours de la ville et défait les croisés"},
    {start:"1399-09-30",text:"Début du règne de Henry IV",flag:[ANGLAIS]},
                {start:"1402-05-19",type:BATAILLE,text:"Combat des Sept", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,wiki:"Combat_des_Sept",desc:"7 chevaliers français combattent 7 chevaliers anglais lors d'un défi"},
                {start:"1404-04",text:"Bataille de Blackpool Sands", wiki:"Bataille_de_Blackpool_Sands", victoire:ANGLAIS, desc:"Un raid français sur la cote anglaise qui tourne à la défaite",flag:[ANGLAIS,FRANCAIS]},
                {start:"1404-04",text:"Siège de Harlech", flag:[FRANCAIS,ANGLAIS],wiki:"Siège_de_Harlech",victoire:FRANCAIS,desc:"Owain Glyndŵr commande l'insurection galloise contre les Anglais. Les Français envoient un corps expéditionnaire pour aider à prendre la forteresse de Harlech, avec des engins de siège. Celle-ci est très mal équipée mais résiste. Affamés, les défenseurs finissent par capituler.",campagne:"Insurection du pays de Galles"},
                {start:"1404-04",text:"Siège de Caernarfon", flag:[FRANCAIS,ANGLAIS],campagne:"Insurection du pays de Galles",wiki:"Siège_de_Caernarvon",victoire:FRANCAIS,desc:"Owain Glyndŵr commande l'insurection galloise contre les Anglais. Les Français escaladent les murs et la ville capitule.",book:"110"},
                {start:"1404-11-16",stop:"1404-11-19",text:"Siège de Falmouth", flag:[FRANCAIS,ANGLAIS,MAL],book:"178",commandants:["Jacques de Bourbon"],desc:"Cette expédition française vainquit la ville, défendue par des paysans anglais. Mais le 19, un raz de marée coula 12 navires français."},
                {start:"1405-06-2",stop:"1405-07-04",type:CHEVAUCHEE,text:"Raid contre Saint-Vaast-la-Hougue", flag:[FRANCAIS,ANGLAIS],book:"345",desc:"Pour mettre fin à l'aide aux Gallois, l'amiral Thomas de Lancastre essaie de prendre, sans succès la citadelle de l'Ecluse. En compensation, il pille Saint-Vaast-la-Hougue",campagne:"Insurection du pays de Galles"},
                {start:"1405-08",text:"Siège de Haverford", flag:[FRANCAIS,ANGLAIS],campagne:"Insurection du pays de Galles",desc:"L'armée française pris probablement la ville par escalade",victoire:FRANCAIS,book:"205"},
                {start:"1405-08",text:"Siège de Carmarthen", flag:[FRANCAIS,FRANCAIS],campagne:"Insurection du pays de Galles",victoire:FRANCAIS,desc:"La ville de Merlin l'enchanteur fut prise par escalade, grâce au corps expéditionnaire français, en soutien aux insurgés gallois commandés par Owen Glendowr",book:"115"},
                {start:"1405-09",text:"Bataille de Worcester", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,campagne:"Insurection du pays de Galles",desc:"En se dirigant vers Worcester, l'armée franco-galloise se heurta à une armée anglaise. Pendant une semaine, il n'y eu que des escarmouches. Les fourageurs gallois finirent par voler les bagages des Anglais lors d'une nuit, l'armée anglaise retraitant alors. Cela mis fin à cette campagne franco-galloise.",book:"369"},
                {start:"1406-01-01",stop:"1407-10-12",text:"Siège de Lourdes", flag:[FRANCAIS,ANGLAIS],book:"229",commandants:["Jean de Bourbon"],victoire:FRANCAIS,desc:"Seul nid d'aigle restant aux mains des Anglais, il est assiégé, bombardé, affamé avant une reddition négociée"},
                {start:"1406-09",type:CHEVAUCHEE,text:"Raid sur Jersey", flag:[FRANCAIS,ANGLAIS],book:"213",desc:"Une troupe franco-castillane débarque sur Jersey et combat la garnison anglaise. Les Anglais sont vaincus et le butin du pillage est rapporté à Brest",victoire:FRANCAIS,},
    {start:"1409-08",type:BATAILLE,text:"Saint Michel et le Dragon",scenario:true,joueurs:[2],stars:2,flag:[MAL,BIEN]},
                {start:"1411-04",text:"Siège de Rethel", flag:[FRANCAIS,BOURGUIGNON],campagne:"Armagnacs contre Bourguignons",victoire:BOURGUIGNON,desc:"La ville défendue par les Bourguignons reste close et n'est pas prise. Les Armagnacs mettent le feu à ses faubourgs"},
                {start:"1412-05-09",text:"Bataille de Saint-Rémy-du-Plain",campagne:"Armagnacs contre Bourguignons", flag:[FRANCAIS,BOURGUIGNON],wiki:"Bataille_de_Saint-Rémy-du-Plain",victoire:BOURGUIGNON,desc:"Les Bourguignons attendent les Armagnacs qui chargent et sont défaits par les arbalétriers et archers bourguignons"},
                {start:"1412-06-11",stop:"1412-07-12",text:"Siège de Bourges",campagne:"Armagnacs contre Bourguignons", flag:[FRANCAIS,BOURGUIGNON],commandants:["fils du Roi"],victoire:FRANCAIS,wiki:"Siège_de_Bourges_(1412)"},
                {start:"1412-07-10",stop:"1412-07-15",text:"Siège de Dreux", flag:[FRANCAIS,BOURGUIGNON],campagne:"Armagnacs contre Bourguignons",wiki:"Siège_de_Dreux_(1412)",desc:"La ville aux mains des Armagnacs, notamment Charles d'Albret, comte de Dreux, capitule à force de bombardements",commandants:["Charles d'Albret"],victoire:BOURGUIGNON},
    {start:"1413-03-20",text:"Début du règne de Henry V",flag:[ANGLAIS]},
                {start:"1413-04-27",stop:"1413-09-05",text:"Révolte des Cabochiens", flag:[FRANCAIS,BOURGUIGNON],campagne:"Armagnacs contre Bourguignons",wiki:"Révolte_des_Cabochiens",victoire:FRANCAIS,desc:"La corporation des Bouchers, avec Simon Caboche, à Paris controlée par les Bourguignons, refuse les impôts pour financer la guerre. Ils forcent le roi à signer une ordonnance en leur faveur, mais leurs exactions poussent les Parisiens à demander un retour des Armagnacs. La révolte est matée dans le sang. La Boucherie du Parvis Notre-Dame est rasée. Jean sans peur s'enfuie de Paris", wiki:"Révolte_des_Cabochiens"},
                {start:"1415-08-18",text:"Siège d'Harfleur", flag:[FRANCAIS,ANGLAIS],commandants:["Henry V","Charles d'Albret"],desc:"Henry V envahit la France et revendique la couronne, rallumant la guerre après 35 ans de trêve. Harfleur est assiégée, bombardée et après un délai pour attendre une armée de secours de Charles d'Albert qui n'arriva pas à casser le siège, la ville capitula.",wiki:"Siège_d'Harfleur",victoire:ANGLAIS},
                {start:"1415-10-25",type:BATAILLE,scenario:true,text:"La bataille d'Azincourt", joueurs:[2,4],stars:3,flag:[FRANCAIS,ANGLAIS],commandants:["Richemont","Charles d'Albret","Henry V","Oxford","York","Brimeu","de Croy","Boucicaut"],desc:"Les Français chargent sans organisation, et se font massacrer. Cette bataille décisive est un tournant dans l'art de la guerre du Moyen âge. Les armées plus disciplinées, plus maniables et les armes de jet/d'artillerie vont se développer. A l'issue de la bataille, d'Albret, Brimeu, de Croy, les comtes d'Oxford et d'York sont morts à Azincourt",victoire:ANGLAIS,book:"35",wiki:"Bataille_d'Azincourt"},
                {start:"1416-03-09",text:"Bataille de Valmont", flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,wiki:"Bataille_de_Valmont",desc:"Un raid anglais commandé par Thomas de Beaufort est intercepté par une armée française commandée par Bernard d'Armagnac, qui tourne à l'avantage des Français. 2 jours plus tards, cette armée française sera battue près de Harfleur",wiki:"Bataille_de_Valmont"},
                {start:"1417-08-18",text:"Siège de Caen", flag:[FRANCAIS,ANGLAIS],commandants:["Henry V"],desc:"Henry V décida de faire sauter Caen, bloquant la Normandie et qu'il considérait sienne. La ville n'avait pas de garnison, mais après une forte résistance des milices bourgeoises, des échanges d'artillerie, la ville se rendit",victoire:ANGLAIS,wiki:"Siège_de_Caen_(1417)"},
                {start:"1418-07-29",stop:"1419-01-19",type:SIEGE,text:"Siège de Rouen", joueurs:[2],stars:2,scenario:true,flag:[FRANCAIS,ANGLAIS],commandants:["Blanchard","Bouteiller","Henry V"],victoire:ANGLAIS,desc:"Un long siège de Rouen mena les habitants à la famine. Les habitants négocient la réddition. Blanchard, commandant les canons et les arbalétriers, sera executé, car trop pauvre pour acheter sa grâce",victoire:ANGLAIS,wiki:"Siège_de_Rouen_(1418-1419)"},
                {start:"1420-06-16",stop:"1420-07-01",text:"Siège de Montereau-Fault-Yonne", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON],commandants:["Henry V"],victoire:ANGLAIS,desc:"La ville est rapidement prise, mais le chateau résiste. La garnison obtient un laissez passer et se rend",wiki:"Siège_de_Montereau-Fault-Yonne"},
                {start:"1420-07-07",stop:"1420-11-17",text:"Siège de Melun", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON] ,commandants:["Henry V"],victoire:ANGLAIS,desc:"La ville tomba pour cause de famine",wiki:"Siège_de_Melun_(1420)"},
                {start:"1420-04",text:"Prise de Paris", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON],wiki:"Prise_de_Paris_(1420)",commandants:["Henry V"],victoire:ANGLAIS,desc:"Entrée des Anglais dans Paris. Les Armagnacs en ont été chassés depuis l'assassinat du Duc de Bourgogne, Jean sans Peur l'année d'avant."},
                {start:"1421-03-22",text:"Bataille de Baugé", flag:[FRANCAIS,ANGLAIS,ECOSSAIS],victoire:ECOSSAIS,commandants:["Buchan","Salisbury","Derneley"],wiki:"Bataille_de_Baugé",desc:"Le duc de Clarence, impulsif, lance l'armée anglaise à l'assaut d'une colline défendue par l'armée franco-écossaise menée par Jean Stuart de Buchan. C'est un massacre pour les anglais."},
                {start:"1421-08-30",text:"Bataille de Mons-en-Vimeu", flag:[FRANCAIS,BOURGUIGNON],commandants:["Xaintrailles","Hire","II de Luxembourg"],victoire:BOURGUIGNON,campagne:"Armagnacs contre Bourguignons",wiki:"Bataille_de_Mons-en-Vimeu",desc:"Les Bourguignons battent les Armagnacs, et permet aux Bourguignons de controler la Picardie. Il y eu beaucoup de prisonniers"},
                {start:"1421-10-06",stop:"1422-05-10",text:"Siège de Meaux", flag:[FRANCAIS,ANGLAIS],wiki:"Siège_de_Meaux_(1421-1422)",victoire:ANGLAIS,commandants:["Henry V"],desc:"Meaux était une place forte proche de Paris encore tenue par les partisans du Dauphin. Après la défaite à Baugé, Henry V mène une campagne éclair, avec Dreux, Chartres, puis Meaux. Malgré une défense vaillante, la ville se rend. La conséquence fut qu'un grand nombre de villes se livrèrent à Henry V"},
    {start:"1421-10-31",type:BATAILLE,scenario:true,text:"Plus de place en Enfer", joueurs:[1],stars:3,flag:[FRANCAIS,MAL]},
                {start:"1421-10",text:"Traité de Troyes",flag:[FRANCAIS,ANGLAIS],wiki:"Traité_de_Troyes"},
                {start:"1422-08",text:"Bataille de Bernay", flag:[FRANCAIS,ANGLAIS],commandants:["Loré"],victoire:FRANCAIS,wiki:"Bataille_de_Bernay",desc:"Ayant appris que la riche cille de Bernay était peu défendue, l'armée française la capture"},
                    {start:"1422-08-31",text:"Début du règne de Henry VI",flag:[ANGLAIS]},
                {start:"1423-07-31",scenario:true,type:BATAILLE,text:"La bataille de Cravant", joueurs:[2,3,4],stars:3,flag:[FRANCAIS,ANGLAIS,BOURGUIGNON,ECOSSAIS],victoire:ANGLAIS,wiki:"Bataille_de_Cravant",commandants:["Buchan","Derneley","Toulongeon","Salisbury","Chastellux","Sévérac","Suffolk"]},
                {start:"1423-09-26",type:BATAILLE,text:"La Brossinière",scenario:true,joueurs:[2],stars:1,flag:[FRANCAIS,ANGLAIS],victoire:FRANCAIS,commandants:["John de la Pôle","Loré"],desc:"De la Pôle, à l'issue d'une chevauchée en Maine et Anjou, revenait avec son butin et ses otages. Yolande d'Aragon, la belle-mère du dauphin, monte une interception. C'est un massacre pour les Anglais",wiki:"Bataille_de_la_Brossinière"},
    /*{start:"1424-08-15",text:"Siège de Verneuil", flag:[FRANCAIS,ECOSSAIS,ANGLAIS]},*/
                {start:"1424-08-17",text:"Bataille de Verneuil", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON,ECOSSAIS],wiki:"Bataille_de_Verneuil_(1424)",victoire:ANGLAIS,commandants:["Buchan","Montaigu","Lancastre"],desc:"En ayant pris Verneuil, les franco-écossais provoquèrent un siège de la ville par les Anglais. Les deux parties convinrent de régler ça par une bataille plutôt que par un long siège. John Stuart de Buchan y trouva la mort."},
                {start:"1426-03-06",text:"Bataille de Saint-James", flag:[FRANCAIS,ANGLAIS],commandants:["Richemont","Lancastre"],victoire:ANGLAIS,wiki:"Bataille_de_Saint-James_(1426)",desc:"Richemont assiège les Anglais à Saint-James, avec de nombreuses pièces d'artillerie. Les Anglais tentent une dernière action: ils sortent de la ville et prennent en tenaille les Français, en criant 'Saint Georges et Salisbury!'. Croyant que le redoutable comte est à la maneuvre, les Français fuient" },
                {start:"1427-07-15",stop:"1427-09-05",text:"Siège de Montargis", flag:[FRANCAIS,ANGLAIS],commandants:["William de la Pôle","Xaintrailles","Hire","Dunois","Warwick"],victoire:FRANCAIS,wiki:"Siège_de_Montargis",desc:"Les Anglais voulaient la ville de Montargis comme quartier général pour la région. Ils en font le siège mais le Dauphin envoie une armée de secours, commandée par le jeune Dunois. Pris entre 2 feux, les Anglais fuient"},
    {start:"1428-02-13",type:BATAILLE,text:"L'Epée de Fierbois",scenario:true,joueurs:[2],stars:1,flag:[FRANCAIS,ANGLAIS]},
                {start:"1428-03-13",text:"Siège de Laval", flag:[FRANCAIS,ANGLAIS],commandants:["Talbot"],victoire:ANGLAIS,wiki:"Siège_de_Laval_(1428)",desc:"Talbot parvint par faute de gué à prendre la ville et la mit à sac"},
    {start:"1428-10-12",stop:"1429-05-08",text:"Siège d'Orléans", flag:[FRANCAIS,ANGLAIS,ECOSSAIS],campagne:"Campagne de la vallée de la Loire"},
                {start:"1429-02-12",text:"La bataille des Harengs",scenario:true,joueurs:[2,3],stars:2,type:BATAILLE, flag:[FRANCAIS,ANGLAIS,ECOSSAIS],commandants:["Derneley","Dunois","Fastolf","Charles de Bourbon"],victoire:ANGLAIS,wiki:"Journée_des_Harengs",desc:"Le convoi transportant du poisson est attaqué par les Français sortant d'Orléans. Les Anglais, retranchés derrière les chariots, gagnèrent la bataille. De Derneley y perdit la vie",campagne:"Campagne de la vallée de la Loire"}, /* Jean Stuart de Buchan est mort avant cette date, 1424!! C'est bien Derneley qui est aux harengs */
    {start:"1429-02-25",text:"La cour de Chinon",scenario:true,type:BATAILLE,flag:[FRANCAIS,ANGLAIS],joueurs:[2,4],stars:3},
                {start:"1429-05-05",type:BATAILLE,text:"La bastille Saint-Loup",joueurs:[2],stars:2,scenario:true,flag:[FRANCAIS,ANGLAIS],commandants:["Jeanne","Xaintrailles","Hire","Dunois","Montaigu","Salisbury","Talbot","Scales"],victoire:FRANCAIS,wiki:"Siège_d'Orléans_(1428-1429)",campagne:"Campagne de la vallée de la Loire"},
                {start:"1429-05-06",type:BATAILLE,text:"L'attaque des Tourelles",scenario:true,joueurs:[2],stars:2,flag:[FRANCAIS,ANGLAIS],commandants:["Jeanne","Xaintrailles","Hire","Dunois","Montaigu","Salisbury","Talbot","Scales"],victoire:FRANCAIS,wiki:"Siège_d'Orléans_(1428-1429)",campagne:"Campagne de la vallée de la Loire"},
                {start:"1429-06-10",text:"Bataille de Jargeau", flag:[FRANCAIS,ANGLAIS],campagne:"Campagne de la vallée de la Loire",commandants:["Arc","William de la Pôle","Dunois","Xaintrailles","Hire"],victoire:FRANCAIS,wiki:"Bataille_de_Jargeau",desc:"Les Français s'emparèrent de Jargeau et capture Suffolk (William de la Pôle)"},
                {start:"1429-06-15",text:"La bataille de Meung-sur-Loire", scenario:true,type:BATAILLE,joueurs:[2,4],stars:1,flag:[FRANCAIS,ANGLAIS],campagne:"Campagne de la vallée de la Loire",commandants:["Arc","Talbot","Scales","Dunois","Xaintrailles","Hire"],victoire:FRANCAIS,desc:"Meung-sur-Loire controlait un pont d'importance stratégique. Les Francais s'en empare mais laissent la ville."},
                {start:"1429-06-16",text:"Bataille de Beaugency", flag:[FRANCAIS,ANGLAIS],campagne:"Campagne de la vallée de la Loire",commandants:["Arc","Talbot","Fastolf","Dunois","Xaintrailles","Hire","Rais"],victoire:FRANCAIS,desc:"Beaugency controlait un passage stratégique sur la Loire et est attaqué dès le pont de Meung sur Loire conquis"},
    {start:"1429-06-18",type:BATAILLE,scenario:true,text:"La bataille de Patay",joueurs:[2],stars:1, flag:[FRANCAIS,ANGLAIS],campagne:"Campagne de la vallée de la Loire"},
    {start:"1429-07-04",/*stop:"1429-07-16",*/text:"Prendre Troyes par la foi", joueurs:[2],stars:3,scenario:true, type:BATAILLE,flag:[FRANCAIS,BOURGUIGNON]},/* Brimeu et de Croy sont morts a Azincourt */
    {start:"1429-08-15",text:"Bataille de Montépilloy", flag:[FRANCAIS,ANGLAIS]},
    {start:"1429-09-03",text:"Siège de Paris", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON]},
    {start:"1429-09-25",text:"Siège de Laval", flag:[FRANCAIS,ANGLAIS]},
    {start:"1429-11",text:"Siège de Saint-Pierre-le-Moûtier", flag:[FRANCAIS,BOURGUIGNON]},
    {start:"1429-11-24",stop:"1429-12-25",text:"Siège de La Charité-sur-Loire", flag:[FRANCAIS,BOURGUIGNON]},
    {start:"1430-05-20",stop:"1430-10-28",text:"Siège de Compiègne", flag:[FRANCAIS,BOURGUIGNON]},
    {start:"1430-05-23",type:BATAILLE,text:"La capture de Jeanne d'Arc",scenario:true,joueurs:[2,4],stars:2,flag:[FRANCAIS,ANGLAIS]},
    {start:"1431-02-19",text:"La libération de Jeanne d'Arc",scenario:true,joueurs:[2,4],stars:3,flag:[FRANCAIS,ANGLAIS]},
    {start:"1431-07-02",text:"Bataille de Bulgnéville", flag:[BOURGUIGNON,FRANCAIS]},
    {start:"1432-07",stop:"1432-08-20",text:"Siège de Lagny-sur-Marne", flag:[FRANCAIS,ANGLAIS,BOURGUIGNON,ECOSSAIS]},
    {start:"1435-05-09",text:"Bataille de Gerberoy", flag:[FRANCAIS,ANGLAIS]},
    {start:"1436-04",text:"Siège de Paris", flag:[FRANCAIS,ANGLAIS]},
    {start:"1436-07-09",stop:"1436-07-29",text:"Siège de Calais", flag:[BOURGUIGNON,ANGLAIS]},
    {start:"1441-08-31",stop:"1442-06-24",text:"Siège de Tartas", flag:[FRANCAIS,ANGLAIS]},
    {start:"1442-11-02",stop:"1443-08-15",text:"Siège de Dieppe", flag:[FRANCAIS,ANGLAIS]},
    {start:"1449-03-23",stop:"1449-11-04",text:"Siège de Fougères", flag:[FRANCAIS,ANGLAIS]},
    {start:"1449-07-19",stop:"1449-08",type:BATAILLE,text:"Prise de Verneuil", flag:[FRANCAIS,ANGLAIS]},
    {start:"1450-04-15",type:BATAILLE,scenario:true,text:"La bataille de Formigny", stars:3,joueurs:[2,6],flag:[FRANCAIS,ANGLAIS]},
    {start:"1450-10-19",stop:"1450-07-01",text:"Siège de Caen", flag:[FRANCAIS,ANGLAIS]},
    {start:"1450-11-01",text:"Bataille de la Male Jornade", flag:[FRANCAIS,ANGLAIS]},
    {start:"1453-06-25",text:"Bataille de Martignas", flag:[FRANCAIS,ANGLAIS]},
                {start:"1453-07-17",text:"Bataille de Castillon", flag:[FRANCAIS,ANGLAIS]},
                    {start:"1461-03-04",text:"Début du règne d'Edouard IV",flag:[ANGLAIS]},

    {start:"1462-06-17",scenario:true,type:BATAILLE,text:"Vlad Tepes à Targoviste",joueurs:[2],stars:2,flag:[VALAQUE,OTTOMAN]},
    {start:"1462-06-18",scenario:true,type:BATAILLE,text:"Soif de sang",stars:2,joueurs:[2,3],flag:[VALAQUE,OTTOMAN,MAL]},
    {start:"1463-04-06",text:"Chute de Constantinople", flag:[OTTOMAN]},
    {start:"1475-08",text:"Traité de Picquigny",flag:[FRANCAIS,ANGLAIS]},
               ];
    }
    constructor(e) {
        Object.assign(this,e);
        if (this.text.startsWith("Bataille")) this.type=BATAILLE;
        if (this.text.startsWith("Siège")) this.type=SIEGE;
        if (this.text.startsWith("Chevauchée")) this.type=CHEVAUCHEE;
        if (this.text.startsWith("Croisade")) this.type=CROISADE;
        if (this.text.startsWith("Début")) this.type=TRAITE;
        if (this.text.startsWith("Traité")) this.type=TRAITE;
        if (this.text.startsWith("Révolte")) this.type=REVOLTE;
        if (typeof this.type!="undefined"&&this.type!=BATAILLE)
            this.class=COULEUR_BATAILLES[this.type];
        if (this.scenario) this.text=this.text+"*";
    }
    static liste() {
        let i,l=[];
        let liste=Evenement.el();
        for (i=0;i<liste.length;i++) {
            let e=liste[i];
            e.id=i;
            l[i]=new Evenement(e);
        }
        return l;
    }
    format(withdate) {
        let t=this.text,j;
        if (this.scenario&&withdate) {
            if (this.stars>=2) t+="*";
            if (this.stars==3) t+="*";
        }
        if (this.start&&withdate) {
            t=this.start.getFullYear()+" "+t;
        }
        if (this.flag) {
            t+=" ";
            for (j=0;j<this.flag.length;j++)
                t+="<span class='blason"+NOM_FACTION[this.flag[j]]+"'/>";
        }
        if (!withdate) return t;
        if (this.joueurs) t+=" [p"+this.joueurs.join(", p")+"]";
        return $("<span>"+t+"</span>");
    }
    info(persolist) {
        let i,s=[],ss=[],ss0=[],p="",j;
        if (typeof this.commandants!="undefined") {
            for (j=0;j<this.commandants.length;j++)  {
                let c=this.commandants[j];
                for (i=0;i<persolist.length;i++) {
                    let pl=persolist[i];
                    if (pl.text.indexOf(c)>-1) {
                        ss0.push(pl);
                        break;
                    }
                }
            }
            ss0.sort((a,b)=>(a.faction<b.faction));
            ss=ss0/*.filter((x)=>this.flag.includes(x.faction))*/
                .map((x)=>"<span class='blason "+NOM_FACTION[x.faction]+"'>"+x.text+"</span><br/>");

        }
        for (i=0;i<persolist.length;i++) {
            let pl=persolist[i];
            let es=this.start.getFullYear();
            if (pl.dates[0]<=es&&pl.dates[1]>=es) s.push(pl);
            if (pl.dates[2]<=es&&pl.dates[3]>=es) s.push(pl);
        }
        s.sort((a,b)=>(a.faction<b.faction));
        s=s.filter((x)=>this.flag.includes(x.faction)&&ss0.indexOf(x)==-1)
            .map((x)=>"<span class='blason "+NOM_FACTION[x.faction]+"'>"+x.text+"</span><br/>");
        
        p="<h5>"+this.text+"</h5>";

        if (this.campagne) p+="<div class='text-muted'>"+this.campagne+"</div>";
        if (this.victoire) p+="<div class='text-muted blason "+NOM_FACTION[this.victoire]+"'>Victoire </div>";
        if (this.desc) p+="<div class='text-justify'>"+this.desc+"<div/>";
        if (ss.length>0) 
            p+="<div class='text-muted'>Liste des personnages ayant participé</div><div class='container cc2'>"+ss.join(' ')+"</div>";
         if (s.length>0)
             p+="<div class='text-muted'>Liste d'autres personnages vivants cette année</div><div class='container cc2'>"+s.join(' ')+"</div>";
       if (this.wiki) {
            p+="<div class='text-muted'><em><a target='_blank' href='https://fr.m.wikipedia.org/wiki/"+this.wiki+"'>"+this.text+"</a></em> de Wikipédia en français (<a href='"+this.source+"'&action=history'>auteurs</a>)</div>";
        }
        if (this.book) {
            p+="<div class='text-muted'><em><a target='_blank' href='r.html?page="+this.book+"'>Répertoire des combats franco-anglais de la guerre de cent ans</a></em> (Jean-Claude Castex)</div>";
        }

        return p;
    }
}

var evenements=Evenement.liste();

