var liste_decors=[
    {text:"chariot",i:"chariot",scale:1.1},
    {text:"oratoire",i:"oratoire",scale:1},
    {text:"arbuste",i:"arbuste",scale:0.8},
    {text:"arbre",i:"arbre",scale:1.5},
    {text:"feu",i:"feu",scale:0.8},
    {text:"puits",i:"puits"},
    {text:"moulin",i:"moulin",scale:3},
    {text:"pont de pierre",i:"pont_pierre",scale:1.3},
    {text:"pont de bois",i:"pont_bois",scale:1.3},
    {text:"ruine",i:"ruine",scale:1},
    {text:"tente",i:"tente",scale:1.5},
    {text:"église",i:"eglise",scale:2.5},
    {text:"chaumiere",i:"chaumiere",scale:1.6},
    {text:"MAISON",i:"maison2",scale:1.6},
    {text:"maison",i:"house1",scale:1.3},
    {text:"rochers",i:"rochers",scale:0.8},
    {text:"pieux",i:"pieux",scale:0.8},
    {text:"pieux60",i:"pieux60",scale:2},
    {text:"pieux120",i:"pieux120",scale:1.5},
    {text:"muret",i:"muret",scale:0.3},
    {text:"muret60",i:"muret60",scale:1.5},
    {text:"muret120",i:"muret120",scale:1.5},
    {text:"palissade",i:"palissade",scale:1},
    {text:"palissade60",i:"palissade60",scale:2},
    {text:"palissade120",i:"palissade120",scale:2},
    {text:"ruine d'église",i:"ruine2",scale:1.5},
    {text:"porte",i:"porte",scale:2.7},
    {text:"tour",i:"tour",scale:2.5},
    {text:"donjon",i:"donjon",scale:4},
    {text:"muraille",i:"muraille",scale:2.5},
    {text:"ralliement",i:"rallie_francais"},
    {text:"ralliement",i:"rallie_anglais"},
    {text:"ralliement",i:"rallie_mal"},
    {text:"ralliement",i:"rallie_bien"},
    {text:"ralliement",i:"rallie_valaque"},
    {text:"ralliement",i:"rallie_ottoman"},
    {text:"ralliement",i:"rallie_bourguignon"},
    {text:"ralliement",i:"rallie_ecossais"},
    {text:"surprise",i:"surprise"},
    {text:"objecif",i:"objectif"},
    {text:"civil",i:"civil"},
    
]
