var dictionnaire_unites = {
    "Amaury de Craon":{box:[CORE],f:'A',dates:[1345,1373],source:"fr.wikipedia.org/wiki/Amaury_IV_de_Craon",blason:true,i:"Héros_monté"},
    "Barral de Pontevès":{box:[CORE],blason:true,f:'A',dates:[1370,1390],source:"fr.wikipedia.org/wiki/Pontev%C3%A8s#Moyen_%C3%82ge",i:"Héros_monté"},
    "Charles II le Magnanime":{box:[CORE],en:"Charles II the Magnanimous",f:'A',dates:[1324,1346],source:"fr.wikipedia.org/wiki/Charles_II_d%27Alen%C3%A7on",blason:true,i:"Héros_monté"},
        "Echelles":{en:"Ladder",box:[SIE]},
    "William Wallace":{box:[REL],f:'WWC',dates:[1296,1305],source:"fr.wikipedia.org/wiki/William_Wallace",blason:true,i:"William_Wallace"},
    "Adeptes":{en:"Disciples",box:[REL],i:"Adeptes"},
    "Aitvaras":{box:[TEU],f:'AIT',i:"Aitvaras"},
    "Alain Blanchard":{box:[SIE],f:'C',dates:[1394,1419],source:"fr.wikipedia.org/wiki/Alain_Blanchard_(capitaine)",i:"Bertrand_de_Poulengy"},
    "Almogavres":{en:"Almogavars",box:[REL],i:"Hallebardiers"},
    "Amaury de Sévérac":{f:'GUE',box:[CRA],dates:[1385,1427],source:"fr.wikipedia.org/wiki/Amaury_de_S%C3%A9v%C3%A9rac",blason:true,i:"Bertrand_du_Guesclin"},
    "Ambroise de Loré":{box:[CORE],f:'A',dates:[1410,1446],source:"fr.wikipedia.org/wiki/Ambroise_de_Lor%C3%A9",blason:true,i:"Héros_monté"},
    "Ange":{en:"Angel",box:[CORE],i:"Ange"},
    "Ange annonciateur":{en:"Angelic Herald",box:[APO]},
    "Ange destructeur":{en:"Destructive Angel",box:[APO]},
    "Ange Glorieux":{en:"Glorious Angel",box:[TEU],f:'Agl',i:"Ange_Glorieux"},
    "Apothicaire":{box:[REL,VIL],en:"Apothecary",civil:true,i:"Apothicaire"},
    "Arbalétriers Génois Retranchés":{en:"Entrenched Genoese Crossbowmen",box:[REL],recultue:true,i:"Arbalétriers"},
    "Arbalétriers Génois":{en:"Genoese Crossbowmen",box:[REL],i:"Arbalétriers"},
    "Arbalétriers montés":{en:"Mounted Crossbowmen",box:[TEU],i:"Arbalétriers_montés"},
    "Arbalétriers":{box:[CORE,LEG],en:"Crossbowmen",i:"Arbalétriers"},
    "Arbre Sacré":{f:'ARS',en:"Sacred Tree",box:[TEU],grand:true,i:"Arbre_sacré"},
    "Archange Gabriel":{en:"Archangel Gabriel",box:[CORE],f:'AGL',i:"Archange_Gabriel"},
    "Archange Raphaël":{en:"Archangel Raphael",box:[APO],f:'ARP',i:"Archange_Raphael"},
    "Archange saint Michel":{en:"Archangel Saint Michael",box:[DRA],f:'ASM',i:"Archange_saint_Michel"},
    "Arche d'Alliance":{en:"Ark of the Covenant",box:[APO],f:'AoC',i:"Arche_de_l_Alliance"},
    "Archers Arc Court":{en:"Bowmen - Short Bow",box:[REL],i:"Archers_Arc_Court"},
    "Archers Azab":{box:[REL],en:"Azab Archers",o1:[100,2,ARCHERS,0,6],i:"Archers_Azab"},
    "Archers Tatars":{en:"Tatar Archers",box:[TEU],i:"Archers_Tatars"},
    "Archers bourguignons":{en:"Burgundian Archers",box:[CRA],i:"Archers_Arc_Court"},
    "Archers montés":{en:"Mounted Bowmen",box:[OTT],i:"Archers_montés"},
    "Archers":{box:[CORE,LEG],en:"Bowmen",i:"Archers"},
    "Archevêque Pierre de Cros":{en:"Archbishop Pierre de Cros",box:[CORE],f:'P',dates:[1362,1388],source:"fr.wikipedia.org/wiki/Pierre_de_Cros",i:"Jean_de_Lancastre"},
    "Arnaud Amanieu d'Albret":{f:'PhO',box:[REL],dates:[1351,1401],source:"fr.wikipedia.org/wiki/Arnaud-Amanieu_d%27Albret",blason:true,i:"Philippe_d_Orléans"},
    "Arnaud de Cervole":{f:'AdC',box:[REL],dates:[1351,1366],source:"fr.wikipedia.org/wiki/Arnaud_de_Cervole",blason:true,i:"Arnaud_de_Cervole"},
    "Arthur de Richemont":{box:[CORE],f:'AdR',dates:[1414,1458],source:"fr.wikipedia.org/wiki/Arthur_III_de_Bretagne",blason:true,i:"Arthur_de_Richemont"},
    "Assassin":{box:[REL],f:'ASS',i:"Assassin"},
    "Baliste":{en:"Ballista",box:[SIE,SIQ],i:"Baliste"},
    "Baudoin de Lens":{box:[CORE],f:'A',blason:true,dates:[1358,1364],source:"fr.wikipedia.org/wiki/Ma%C3%AEtre_des_arbal%C3%A9triers",i:"Héros_monté"},
    "Bernard Szumborski":{f:'HT',box:[TEU],i:"Bernard_Szumborski",source:"en.wikipedia.org/wiki/Bernard_Szumborski",dates:[1444,1470]},
    "Bertrand de Poulengy":{f:'C',blason:true,box:[CORE],dates:[1412,1456],source:"fr.wikipedia.org/wiki/Bertrand_de_Poulengy",i:"Bertrand_de_Poulengy"},
    "Bertrand du Guesclin":{box:[CORE],f:'GUE',dates:[1337,1380],source:"fr.wikipedia.org/wiki/Bertrand_du_Guesclin",blason:true,i:"Bertrand_du_Guesclin"},
    "Bombarde":{en:"Bombard",box:[DRA,SIQ,SIE],i:"Bombarde"},
    "Boucicaut":{box:[CORE],f:'BCC',dates:[1340,1415],source:"fr.wikipedia.org/wiki/Jean_II_Le_Meingre",blason:true,i:"Boucicaut"},
    "Bourgeois":{en:"Citizen",box:[CORE,VIL],civil:true,i:"Bourgeois"},
    "Bourreau":{en:"Executioner",box:[REL],i:"Bourreau",b3:[55,3,CIVIL,0,0,0,1]},
    "Bélier":{en:"Battering Ram",box:[SIE,SIQ],i:"Bélier"},
"Canon":{en:"Cannon",box:[OTT],o1:[190,3,CANON,0,0,0,2]},
    "Captal de Buch":{box:[CORE],f:'CHS',dates:[1348,1372],source:"fr.wikipedia.org/wiki/Jean_de_Grailly",blason:true,i:"Captal_de_Buch"},
"Cavalerie Légère":{box:[CRA],en:"Light Cavalry"},
    "Cavalerie lourde Lituanienne":{en:"Lithuanian heavy cavalry",box:[TEU],i:"Cavalerie_lourde_Lituanienne"},
"Cavaliers Archers":{en:"Mounted Bowmen",box:[OTT],o1:[120,2,ARCHERS_M,0,0,0,3]},
    "Cavaliers Nobles":{en:"Noble Cavalry",box:[REL],o1:[190,3,CAVAL,0,0,0,4],i:"Cavaliers_Nobles"},
    "Cavaliers Polonais":{en:"Polish Knights",box:[TEU],i:"Cavaliers_Polonais"},
    "Cavaliers Sipahi":{en:"Sipahi",box:[REL],o1:[140,2,CAVAL,0,0,0,4],type:INFANTERIE,i:"Cavaliers_Sipahi"},
"Cavaliers damnés":{en:"Damned",box:[APO]},
    "Chariot de guerre":{en:"War wagon",box:[TEU],grand:true,i:"Chariot_de_guerre"},
    "Charles d'Albret":{box:[LEG],f:'C',dates:[1388,1415,1417,1471],source:"fr.wikipedia.org/wiki/Charles_Ier_d%27Albret fr.wikipedia.org/wiki/Charles_II_d%27Albret",blason:true,i:"Bertrand_de_Poulengy"},
    "Charles de Bourbon":{box:[CORE],f:'A',dates:[1416,1456],source:"fr.wikipedia.org/wiki/Charles_Ier_de_Bourbon",blason:true,i:"Héros_monté"},
"Chasseur":{box:[CORE],en:"Hunter",civil:true},
"Chevaliers Impétueux":{en:"Impetuous Knights",box:[REL],i:"Chevaliers_à_pied"},
    "Chevaliers Teutoniques Montés":{en:"Mounted Teutonic Knights",box:[TEU],i:"Chevaliers_Teutoniques_Montés"},
    "Chevaliers Teutoniques":{en:"Teutonic Knights",box:[TEU],i:"Chevaliers_Teutoniques"},
"Chevaliers montés Français":{en:"French Mounted Knights",box:[REL],i:"Chevaliers_montés"},
"Chevaliers montés Petite noblesse":{en:"Gentry Mounted Knights",box:[CORE],i:"Chevaliers_montés"},
    "Chevaliers montés":{en:"Mounted Knights",box:[CORE,LEG],i:"Chevaliers_montés"},
"Chevaliers squelettes":{en:"Mounted Skeletons",box:[APO]},
    "Chevaliers à pied Armes à 2 mains":{en:"Foot Knights 2 Handed Weapons",box:[REL],i:"Chevaliers_à_pied"},
"Chevaliers à pied":{en:"Foot Knights",box:[CORE,LEG],i:"Chevaliers_à_pied"},
    "Chiens de Chasse":{en:"Hunting Dogs",box:[REL],i:"Chiens_de_Chasse"},
"Chiens de Guerre":{en:"War Hounds",box:[REL],i:"Chiens_de_Chasse"},
    "Claude de Chastellux":{f:'G',box:[CRA],dates:[1409,1453],source:"fr.wikipedia.org/wiki/Claude_de_Chastellux",blason:true,i:"Edouard_III"},
    "Cola di Rienzo":{box:[HEL],dates:[1343,1354],source:"fr.wikipedia.org/wiki/Cola_di_Rienzo",f:'C',i:"Bertrand_de_Poulengy"},
    "Comte d'Arundel":{en:"Earl of Arundel",box:[CORE],f:'CAR',dates:[1313,1376,1426,1430],source:"fr.wikipedia.org/wiki/Richard_FitzAlan_(3e_comte_d%27Arundel) fr.wikipedia.org/wiki/John_FitzAlan_(7e_comte_d%27Arundel)",blason:true,i:"Boucicaut"},
    "Comte d'Auxerre":{box:[CORE],en:"Earl of Auxerre",f:'C',dates:[1350,1364],source:"fr.wikipedia.org/wiki/Jean_III_de_Chalon-Auxerre",blason:true,i:"Bertrand_de_Poulengy"},
    "Comte d'Oxford":{en:"Earl of Oxford",box:[LEG],f:'C',dates:[1331,1360,1400,1417],source:"www.luminarium.org/encyclopedia/devere7.htm fr.wikipedia.org/wiki/Richard_de_Vere",blason:true,i:"Bertrand_de_Poulengy"},
    "Comte de Northampton":{en:"Earl of Northampton",box:[CORE],f:'C',dates:[1339,1360],source:"fr.wikipedia.org/wiki/Guillaume_de_Bohun",blason:true,i:"Bertrand_de_Poulengy"},
    "Comte de Salisbury":{box:[LEG],en:"Earl of Salisbury",f:'CSY',dates:[1344,1397,1414,1428],source:"fr.wikipedia.org/wiki/William_Montagu_(2e_comte_de_Salisbury) fr.wikipedia.org/wiki/Thomas_Montaigu",blason:true,i:"Comte_de_Salisbury"},
    "Comte de Suffolk":{box:[CORE,LEG],en:"Earl of Suffolk",f:'G',dates:[1337,1369],source:"fr.wikipedia.org/wiki/Robert_d%27Ufford",blason:true,i:"Captal_de_Buch"},
    "Comte de Warwick":{en:"Earl of Warwick",box:[LEG],f:'CWW',dates:[1329,1369],source:"fr.wikipedia.org/wiki/Thomas_Beauchamp_(11e_comte_de_Warwick)",blason:true,i:"Comte_de_Warwick"},
    "Couleuvrine":{en:"Culverin",box:[REL,SIQ,SIE],i:"Couleuvrine"},
    "Coureurs des bois":{en:"Forest Striders",box:[TEU],i:"Coureurs_des_bois"},
    "Devin":{en:"Soothsayer",box:[CORE],civil:true,i:"Devin"},
    "Dracula":{box:[REL],f:'DRL',i:"Dracula"},
    "Dragon":{box:[DRA],m1:[1250,10,APOCALYPSE,0,0,0,1],m2:[1250,10,APOCALYPSE,0,0,0,1],m3:[1250,10,APOCALYPSE,0,0,0,1],f:'DRG'},
    "Démons Volants":{en:"Flying Demons",box:[REL],i:"Démons_Volants"},
    "Démons Voraces":{en:"Voracious Demon",box:[REL],i:"Démons_Voraces"},
"Dévoreurs":{en:"Devourers",box:[APO]},
"Dévôts":{en:"Devotees",box:[APO]},
    "Edmond de Sommerset":{en:"Edmund of Somerset",box:[LEG],f:'C',dates:[1420,1455],source:"fr.wikipedia.org/wiki/Edmond_Beaufort_(1er_duc_de_Somerset)",blason:true,i:"Bertrand_de_Poulengy"},
    "Edouard III":{box:[CORE],en:"Edward III",f:'G',dates:[1327,1377],source:"fr.wikipedia.org/wiki/%C3%89douard_III",blason:true,i:"Edouard_III"},
    "Edouard d'York":{box:[LEG],en:"Edward of York",f:'G',dates:[1401,1415],source:"fr.wikipedia.org/wiki/%C3%89douard_de_Norwich",blason:true,i:"Edouard_III"},
    "Erwan de Romorantin":{box:[CORE],f:'G',dates:[1356,1356],i:"Edouard_III"},
    "Espion":{box:[REL],en:"Spy",f:'SPY',i:"Espion"},
"Expiateurs hérétiques":{box:[APO],en:"Heretic Expiators"},
    "Fantassins d'infanterie légère":{en:"Light Infantry",box:[TEU],i:"Fantassins_d_infanterie_légère"},
    "Fantômes":{en:"Ghost",box:[CORE],i:"Fantômes"},
    "Fermier":{en:"Farmer",box:[REL],civil:true,i:"Paysans"},
    "Flagellants":{en:"Flaggelants",box:[REL],i:"Adeptes"},
    "Forgeron":{en:"Blacksmith",box:[CORE,VIL],civil:true,i:"Forgeron"},
"Gargouilles":{en:"Gargoyles",box:[APO]},
    "Gautier VI de Brienne":{en:"Walter VI Count of Brienne",f:'GUE',box:[LEG],dates:[1311,1356],source:"fr.wikipedia.org/wiki/Gautier_VI_de_Brienne",blason:true,i:"Bertrand_du_Guesclin"},
    "Gilles de Rais":{box:[CORE],f:'GdR',dates:[1420,1436],source:"fr.wikipedia.org/wiki/Gilles_de_Rais",blason:true,i:"Gilles_de_Rais"},
"Gog":{box:[SE],f:'GOG',grand:true},
    "Guide":{box:[REL],civil:true,i:"Guide"},
    "Guillaume de Molins":{box:[SIE],f:'B',dates:[1429,1429],source:"www.persee.fr/docAsPDF/bec_0373-6237_1847_num_8_1_452089.pdf",i:"Edouard_III"},
    "Guisarmiers":{box:[REL],i:"Hallebardiers"},
    "Guy le Bouteiller":{box:[SIE],f:'F',dates:[1414,1438],source:"www.mesqui.net/Articles_fortif/pdf/Guy-le-Bouteillier-et-La-Roche-Guyon.pdf",i:"Robert_Knolles"},
    "Hacquebutiers":{box:[SIE,SIQ],i:"Hacquebutiers"},
    "Hallebardiers":{en:"Halberdiers",box:[CORE,LEG],i:"Hallebardiers"},
    "Henry V":{box:[REL],f:'HV',dates:[1410,1422],source:"fr.wikipedia.org/wiki/Henri_V_(roi_d%27Angleterre)",blason:true,i:"Henry_V"},
    "Héros":{box:[CORE],en:"Hero",f:'A',i:"Héros"},
    "Héros bourguignon":{box:[CORE],en:"Burgundian Hero",f:'C',i:"Bertrand_de_Poulengy"},
    "Héros Lituanien":{f:'HL',box:[TEU],en:"Lithuanian Hero",i:"Héros_Lituanien"},
    "Héros monté":{box:[CORE],en:"Mounted Hero",f:'A',i:"Héros_monté"},
    "Héros Polonais monté":{f:'HPM',box:[TEU],en:"Mounted Polish Hero",i:"Héros_Polonais_monté"},
    "Héros Teutonique monté":{f:'WK',en:"Mounted Teutonic Hero",box:[TEU],i:"Winrich_von_Kniprod"},
    "Héros Teutonique":{box:[TEU],en:"Teutonic Hero",f:'HTeu',i:"Héros_teutonique"},
    "Hérétiques":{en:"Heretics",box:[REL],i:"Hérétiques"},
    "Infanterie de Soutien":{en:"Support Infantry",box:[TEU],i:"Infanterie_de_Soutien"},
    "Infanterie légère":{en:"Light Infantry",box:[REL],o1:[80,1,FANTASSINS,0,0,2,6],i:"Janissaires"},
    "Jacques de Bourbon":{box:[CORE],f:'C',dates:[1342,1362,1393,1438],source:"fr.wikipedia.org/wiki/Jacques_Ier_de_Bourbon-La_Marche fr.wikipedia.org/wiki/Jacques_II_de_Bourbon",blason:true,i:"Bertrand_de_Poulengy"},
"Jacques le troubadour":{en:"Jacques the Troubadour",box:[SE],civil:true},
    "Janissaires":{en:"Janissaries",box:[REL],o1:[105,1,INFANTERIEELITE,2,4],i:"Janissaires"},
    "Jean 1er de Luxembourg":{f:'AdR',box:[CORE],en:"John I of Luxembourg",dates:[1310,1346],source:"fr.wikipedia.org/wiki/Jean_Ier_de_Boh%C3%AAme",blason:true,i:"Arthur_de_Richemont"},
    "Jean II Le Bon":{en:"Jean II The Good",f:'JE2',box:[REL],dates:[1350,1364],source:"fr.wikipedia.org/wiki/Jean_II_le_Bon",blason:true,i:"Jean_II_le_Bon"},
    "Jean II de Luxembourg":{f:'PhO',en:"John II of Luxembourg",box:[REL],dates:[1414,1441],source:"fr.wikipedia.org/wiki/Jean_II_de_Luxembourg-Ligny",blason:true,i:"Philippe_d_Orléans"},
    "Jean Jourdain":{box:[SIE],f:'C',dates:[1418,1419],source:"www.paris-normandie.fr/rouen/l-histoire-revisitee--le-siege-de-rouen-entre-1418-et-1419-CN13969319",i:"Bertrand_de_Poulengy"},
    "Jean Stuart de Buchan":{en:"John Stewart of Buchan",box:[CORE],f:'G',dates:[1404,1424],source:"fr.wikipedia.org/wiki/John_Stuart_(3e_comte_de_Buchan)",blason:true,i:"Edouard_III"},
    "Jean Stuart de Derneley":{en:"John Stewart of Darnley",box:[REL],f:'JSD',dates:[1421,1429],source:"fr.wikipedia.org/wiki/John_Stuart_de_Darnley",blason:true,i:"Jean_Stuart_de_Derneley"},
    "Jean de Bourbon":{box:[LEG],f:'G',dates:[1426,1488],source:"fr.wikipedia.org/wiki/Jean_II_de_Bourbon",blason:true,i:"Edouard_III"},
    "Jean de Brimeu":{f:'A',blason:true,box:[CORE],dates:[1388,1415],source:"www.pagedhistoire.com/bataille/1/Azincourt.php",i:"Héros"},
    "Jean de Croy":{f:'C',box:[CORE],dates:[1380,1415],source:"fr.wikipedia.org/wiki/Jean_Ier_de_Cro%C3%BF",blason:true,i:"Bertrand_de_Poulengy"},
    "Jean de Dunois":{box:[CORE],f:'E',dates:[1422,1468],source:"fr.wikipedia.org/wiki/Jean_de_Dunois",blason:true,i:"Jean_de_Dunois"},
    "Jean de Lancastre":{en:"John of Lancaster",box:[CORE],f:'P',dates:[1403,1435],source:"fr.wikipedia.org/wiki/Jean_de_Lancastre",blason:true,i:"Jean_de_Lancastre"},
    "Jean de Metz":{box:[CORE],f:'G',dates:[1428,1456],source:"fr.wikipedia.org/wiki/Jean_de_Metz",blason:true,i:"Edouard_III"},
    "Jean de Murs":{box:[HEL],f:'JDM',civil:true},
    "Jean de Toulongeon":{f:'C',box:[CRA],dates:[1395,1427],source:"fr.wikipedia.org/wiki/Jean_II_de_Toulongeon",blason:true,i:"Bertrand_de_Poulengy"},
    "Jean de Vienne":{box:[CORE],f:'G',dates:[1347,1347,1358,1396],source:"fr.wikipedia.org/wiki/Jean_Ier_de_Fiennes fr.wikipedia.org/wiki/Jean_de_Vienne",blason:true,i:"Edouard_III"},
    "Jean, fils du Roi":{f:'AdC',box:[LEG],en:"Jean - Son of the King",c:110,dates:[1356,1416],source:"fr.wikipedia.org/wiki/Jean_Ier_de_Berry",blason:true,i:"Arnaud_de_Cervole"},
    "Jeanne d'Arc a cheval":{box:[REL],en:"Mounted Joan of Arc",f:'JJM',dates:[1428,1431],source:"fr.wikipedia.org/wiki/Jeanne_d%27Arc",blason:true,i:"Jeanne_d_Arc_à_cheval"},
    "Jeanne d'Arc":{en:"Joan of Arc",f:'JJ',box:[CORE],dates:[1428,1431],source:"fr.wikipedia.org/wiki/Jeanne_d%27Arc",blason:true,i:"Jeanne_d_Arc"},
    "John Chandos":{box:[CORE],f:'CHS',dates:[1339,1370],source:"fr.wikipedia.org/wiki/John_Chandos",blason:true,i:"Captal_de_Buch"},
    "John Fastolf":{box:[CORE],f:'H',dates:[1410,1459],source:"fr.wikipedia.org/wiki/John_Fastolf",blason:true,i:"John_de_la_Pôle"},
    "John Hawkwood":{f:'CWW',box:[REL],dates:[1342,1394],source:"fr.wikipedia.org/wiki/John_Hawkwood",blason:true,i:"Comte_de_Warwick"},
    "John Talbot":{box:[CORE],f:'CSY',dates:[1404,1453],source:"fr.wikipedia.org/wiki/John_Talbot_(1er_comte_de_Shrewsbury)",blason:true,i:"Comte_de_Salisbury"},
    "John de la Pôle":{en:"John de la Pole",box:[CORE],f:'C',dates:[1423,1428],source:"fr.wikipedia.org/wiki/Bataille_de_la_Brossini%C3%A8re#John_de_la_Pole",blason:true,i:"John_de_la_Pôle"},
    "Jugement":{en:"Judgement",box:[APO],f:'Jug',i:"Jugement"},
    "L'Inquisiteur":{en:"The Inquisitor",box:[REL],f:'IQ',i:"L_Inquisiteur"},
    "L'Antéchrist":{box:[APO],en:"The Antichrist",f:'LAN',i:"L_antechrist"},
    "La Bête":{box:[REL],en:"The Beast",f:'LBT',i:"La_bête"},
    "La Cocatrix":{box:[REL],en:"The Cockatrice",f:'CCX',grand:true,i:"La_Cocatrix"},
    "La Conquête":{box:[APO],en:"Conquest",f:'CQT',grand:true,i:"La_Conquete"},
    "L'Agneau de Dieu":{box:[APO],en:"The Lamb of God",f:'LoG',grand:true,i:"L_Agneau_de_Dieu"},
    "La Mort":{box:[APO],en:"Death",f:'DTH',grand:true,i:"La_Mort"},
    "La Famine":{box:[APO],en:"Famine",f:'LFM',grand:true,i:"La_Famine"},
    "La Guerre":{box:[APO],en:"War",f:'LGU',grand:true,i:"La_Guerre"},
    "La Grande Faucheuse":{en:"The Great Reaper",box:[REL],f:'LGF',i:"La_Grande_Faucheuse"},
    "La Hire":{box:[CORE],f:'LH',dates:[1418,1443],source:"fr.wikipedia.org/wiki/%C3%89tienne_de_Vignolles",blason:true,i:"La_Hire"},
    "Laima, Déesse de la Chance":{box:[TEU],en:"Laima, Goddess of Luck",f:'GOL',i:"Laima"},
    "La Licorne":{en:"Unicorn",box:[CORE],f:'LLI',i:"La_Licorne"},
    "La Succube":{en:"Succubus",box:[TEU],f:'SUC',i:"La_Succube"},
    "La Tarasque":{en:"The Tarasque",box:[CORE],f:'TRQ',grand:true,dates:[1382,1382],source:"fr.wikipedia.org/wiki/Tarasque",i:"La_Tarasque"},
"Lala Sahin Pacha":{box:[OTT],o1:[325,4,PERSONNAGE,1,2],f:'LL',dates:[1360,1388],source:"en.wikipedia.org/wiki/Lala_%C5%9Eahin_Pasha"},
    "Lanciers montés":{en:"Mounted Lancers",box:[TEU],i:"Lanciers_montés"},
"Le Diable":{box:[HEL],en:"The Devil",f:'LDL'},
    "Le Griffon":{en:"The Griffin",box:[REL],f:'LGR',grand:true,i:"Le_Griffon"},
"Le Léviathan":{box:[APO],f:'LLH'},
    "Le Prince Noir a cheval":{en:"Mounted Black Prince",box:[REL],f:'PNM',dates:[1346,1376],source:"fr.wikipedia.org/wiki/%C3%89douard_de_Woodstock",blason:true,i:"Le_Prince_Noir_à_cheval"},
    "Le Prince Noir":{en:"The Black Prince",box:[CORE],f:'PN',dates:[1346,1376],source:"fr.wikipedia.org/wiki/%C3%89douard_de_Woodstock",blason:true,i:"Le_Prince_Noir"},
    "Le Veneur":{f:'CSY',box:[CORE],i:"Comte_de_Salisbury"},
    "Loup-garou":{en:"The Werewolf",box:[CORE],f:'LGU',i:"Loup-garou"},
    "Loups":{en:"Wolves",box:[CORE],i:"Chiens_de_Chasse"},
    "Légion démoniaque":{box:[HEL],en:"Demonic Legion",i:"Légion_démoniaque"},
"Léo l'aubergiste":{en:"Leo the Innkeeper",box:[SE],civil:true},
"Magog":{box:[SE],f:'MGG',grand:true},
    "Manvydas":{f:'HL',box:[TEU],blason:true,i:"Manvydas",dates:[1341,1348],source:"en.wikipedia.org/wiki/Manvydas"},
    "Marchande":{en:"Merchant Girl",box:[CORE,VIL],civil:true,i:"Marchande"},
    "Maréchal Arnoul d'Audrehem":{box:[LEG],en:"Marshal Arnoul d'Audrehem",f:'GdR',dates:[1351,1370],source:"fr.wikipedia.org/wiki/Arnoul_d%27Audrehem",blason:true,i:"Gilles_de_Rais"},
    "Maréchal Jean de Clermont":{box:[LEG,LEG],en:"Marshal Jean de Clermont",f:'F',dates:[1352,1356],source:"fr.wikipedia.org/wiki/Jean_de_Clermont",blason:true,i:"Robert_Knolles"},
    "Mathieu Goth":{en:"Matthew Goth",f:'CHS',box:[LEG],dates:[1406,1450],source:"formigny.free.fr/acteurs.html",i:"Captal_de_Buch"},
    "Mehmet II":{box:[REL],f:'M2',o1:[285,3,PERSONNAGE,1,2],dates:[1444,1481],source:"fr.wikipedia.org/wiki/Mehmed_II",i:"Mehmet_II"},
    "Mehmet le Conquérant":{box:[REL],en:"Mehmet the Conqueror",f:'M2C',o1:[550,6,PERSONNAGE,1,2],grand:true,dates:[1453,1481],source:"fr.wikipedia.org/wiki/Mehmed_II",i:"Mehmet_le_Conquérant"},
    "Milice Bourgeoise":{en:"Provincial Militia",box:[CORE],i:"Piquiers"},
    "Milice Paysanne":{en:"Peasant Militia",box:[REL],i:"Paysans"},
"Milice d'Archers":{box:[REL],en:"Militia Bowmen",i:"Archers_Arc_Court"},
"Monsieur Quirk":{box:[SE],civil:true},
    "Montreur d'ours":{en:"Bear Tamer",box:[REL],i:"Ours"},
    "Musicien":{en:"Musician",box:[REL],i:"Musicien"},
    "Médecin":{en:"Doctor",box:[REL],civil:true,i:"Médecin"},
    "Narimantas":{f:'CL',blason:true,box:[TEU],i:"Narimantas",dates:[1333,1348],source:"fr.wikipedia.org/wiki/Narimantas"},
    "Noble dame":{en:"Noble Lady",box:[VIL],civil:true,i:"Noble_Dame"},
    "Okchu":{box:[REL],o1:[85,2,ARCHERS,0,6],i:"Okchu"},
    "Ours":{en:"Bear",box:[REL],i:"Ours"},
"Pape Clément VI":{box:[HEL],en:"Pope Clement VI",f:'LPCV'},
    "Pavois":{en:"Pavise Shield",box:[SIE,SIQ],i:"Pavois"},
    "Pavoisiers":{en:"Pavisiers",box:[REL],i:"Infanterie_de_Soutien"},
    "Paysans Révoltés":{box:[REL],en:"Angry Peasants",i:"Paysans"},
    "Paysans":{en:"Peasants",box:[CORE,LEG],i:"Paysans"},
    "Perkunas":{f:'PER',box:[TEU],grand:true,i:"Perkunas"},
    "Pestiférés":{en:"Plague Bearer",box:[REL],i:"Pestiférés"},
    "Petit Meschin":{f:'H',box:[REL],dates:[1362,1369],source:"fr.wikipedia.org/wiki/Chefs_routiers_c%C3%A9l%C3%A8bres#Le_Petit_Meschin",i:"John_de_la_Pôle"},
    "Philippe VI de Valois":{box:[CORE],f:'A',dates:[1328,1350],source:"fr.wikipedia.org/wiki/Philippe_VI_de_Valois",blason:true,i:"Héros_monté"},
    "Philippe d'Orléans":{box:[LEG],f:'PhO',dates:[1352,1356],source:"fr.wikipedia.org/wiki/Philippe_d%27Orl%C3%A9ans_(1336-1375)",blason:true,i:"Philippe_d_Orléans"},
    "Philippe de Vitry":{box:[HEL],dates:[1321,1361],source:"fr.wikipedia.org/wiki/Philippe_de_Vitry",f:'P',i:"Jean_de_Lancastre"},
    "Philippe le Hardi":{box:[CORE],en:"Philippe the Bold",f:'A',dates:[1352,1404],source:"fr.wikipedia.org/wiki/Philippe_II_de_Bourgogne",blason:true,i:"Héros"},
    "Piquiers Ecossais":{box:[REL],en:"Scottish Pikemen",i:"Piquiers"},
    "Piquiers Flamands":{en:"Flemish Pikemen",box:[REL],i:"Piquiers"},
    "Piquiers avec pavois":{en:"Pikemen with Pavise",box:[TEU],i:"Piquiers_avec_pavois"},
    "Piquiers":{en:"Pikemen",box:[CORE,LEG],i:"Piquiers"},
    "Porte-Etendard":{en:"Standard Bearer",box:[REL],i:"Porte-Etendard"},
    "Poton de Xaintrailles":{box:[CORE],f:'A',dates:[1423,1450],source:"fr.wikipedia.org/wiki/Jean_Poton_de_Xaintrailles",blason:true,i:"Héros_monté"},
    "Prigent de Coétivy":{box:[LEG],f:'E',dates:[1399,1450],source:"fr.wikipedia.org/wiki/Prigent_VII_de_Co%C3%ABtivy",blason:true,i:"Jean_de_Dunois"},
    "Prêtre":{box:[CORE],en:"Priest",civil:true,i:"Prêtre"},
    "Pénitents":{en:"Penitents",box:[REL],i:"Pénitents"},
    "Radu III le Beau":{f:'Vla',en:"Radu III The Handsome",box:[REL],dates:[1462,1475],source:"fr.wikipedia.org/wiki/Radu_III_le_Beau",blason:true,i:"Radu_III_Le_Beau"},
    "Relique sacrée":{en:"The Holy Relic",box:[APO],f:'RQS',i:"Relique"},
    "Rebouteuse":{en:"Bonesetter",box:[CORE],civil:true,i:"Rebouteuse"},
"Repentants hérétiques":{en:"Heretic Repentants",box:[APO]},
"Ribaudequin":{box:[CRA]},
"Robert Knolles":{f:'F',box:[REL],dates:[1351,1407],source:"fr.wikipedia.org/wiki/Robert_Knolles",blason:true,i:"Robert_Knolles"},
    "Roi Casimir IV de Lituanie":{f:'CL',dates:[1440,1492],blason:true,en:"King Casimir IV f Lithuania",box:[TEU],i:"Narimantas"},
    "Sainte Marthe":{en:"Saint Martha",box:[CORE],f:'SME',i:"Sainte_Marthe"},
    "Sapeurs":{en:"Sappers",box:[SIE,SIQ],i:"Sapeurs"},
    "Seguin de Badefol":{f:'SdB',box:[REL],dates:[1350,1366],source:"fr.wikipedia.org/wiki/Seguin_de_Badefol",i:"Seguin_de_Badefol"},
    "Sergents Teutoniques":{en:"Teutonic Sergeants",box:[TEU],i:"Sergents_Teutoniques"},
    "Sergents d'armes Gascons & Bretons":{en:"Sergeants-at-arms Gascons and Bretons",box:[REL],i:"Sergents_d_armes"},
"Sergents d'armes Lourds":{en:"Heavy Sergeants-at-arms",box:[REL],i:"Sergents_d_armes"},
"Sergents d'armes montés":{en:"Mounted Sergeants-at-arms",box:[LEG]},
"Sergents d'armes":{en:"Sergeants-at-arms",box:[CORE],i:"Sergents_d_armes"},
    "Simon Morhier":{box:[CORE],f:'C',dates:[1422,1429],source:"fr.wikipedia.org/wiki/Simon_Morhier",i:"Bertrand_de_Poulengy"},
    "Sir John Jouel":{box:[CORE],f:'CHS',dates:[1353,1374],source:"fr.wikipedia.org/wiki/Bataille_de_Cocherel",i:"John_de_la_Pôle"},
"Sorcière de Sabbat":{en:"Sabbat Witch",f:'SRC',box:[APO],f:'SdS'},
    "Sorcière des marais":{en:"The Swamp Witch",f:'SRC',box:[CORE],i:"Sorcière"},
    "Sorcière":{en:"The Witch",box:[CORE],f:'SRC',i:"Sorcière"},
"Spectres montés":{en:"Mounted Spectres",box:[APO]},
    "Squelettes Danse Macabre":{box:[REL],en:"Skeletons Danse Macabre",i:"Squelettes"},
"Squelettes Démoniaques":{en:"Devilish Skeletons",box:[REL],i:"Squelettes"},
"Squelettes":{box:[CORE],en:"Skeletons",i:"Squelettes"},
    "Thomas Kyriel":{box:[LEG],en:"Thomas Kyriell",f:'PN',dates:[1416,1461],source:"fr.wikipedia.org/wiki/Thomas_Kyriell",blason:true,i:"Le_Prince_Noir"},
    "Thomas Montagu":{box:[CRA],f:'CHS',dates:[1414,1428],source:"fr.wikipedia.org/wiki/Thomas_Montaigu",blason:true,i:"Captal_de_Buch"},
    "Thomas de Scales":{box:[CORE],f:'AdR',dates:[1419,1460],source:"fr.wikipedia.org/wiki/Thomas_de_Scales",blason:true,i:"Arthur_de_Richemont"},
    "Tour de Siège":{en:"Siege Tower",box:[SIE],grand:true,i:"Tour_de_Siège"},
    "Trébuchet":{en:"Trebuchet",box:[SIE,SIQ],grand:true,i:"Trébuchet"},
    "Triomphe":{en:"Triumph",box:[APO],grand:true,i:"Triomphe",f:"Tri"},
    "Vlad Tepes":{f:'Vla',blason:true,box:[REL],dates:[1448,1476],source:"fr.wikipedia.org/wiki/Vlad_III_l%27Empaleur",i:"Radu_III_Le_Beau"},
    "Vougiers":{en:"Voulgier",box:[REL],i:"Hallebardiers"},
    "Wickerman":{box:[TEU],f:'Wic',i:"Wickerman"},
    "William Glasdale":{box:[SIE],f:'C',dates:[1409,1429],source:"fr.wikipedia.org/wiki/William_Glasdale",blason:true,i:"Bertrand_de_Poulengy"},
    "William de la Pôle":{en:"William de la Pole",f:'A',box:[CORE],dates:[1415,1450],source:"fr.wikipedia.org/wiki/William_de_la_Pole",blason:true,i:"Héros_monté"},
    "Winrich von Kniprod":{f:'WK',box:[TEU],blason:true,i:"Winrich_von_Kniprod",dates:[1351,1382],source:"fr.wikipedia.org/wiki/Winrich_von_Kniprode"},
    "Yerli Kulu":{box:[REL],o1:[70,1,INFANTERIEELITE,2,4],i:"Janissaires"},
"Yildirim Bayezid":{box:[OTT],f:'Y',o1:[415,4,PERSONNAGE,1,2],dates:[1389,1402],source:"fr.wikipedia.org/wiki/Bajazet_Ier"},
}
var liste_unites=[
    {nom:"Amaury de Craon",carac:"C%MA1*1j3",f1:[280,3,PERSONNAGE,1,2],melee:[rouge],defense:[noir,noir],pdv:2,desc:"%ACTIVATED%: %TOURCOND%, %MOVE% %THIS%%HEREANDTHERE%"},
{nom:"Amaury de Sévérac",carac:"I%M12*2R1o",melee:[blanc,blanc,jaune],defense:[rouge,rouge],pdv:3,desc:"%BLESSURE% &rarr; %XP%"},
{nom:"Ambroise de Loré",carac:"C%cJ1MA1*2",melee:[rouge,rouge],defense:[noir],pdv:3,desc:"%ACTIVATED%: %ROUNDCOND%, +1 %VERT%"},
{nom:"Archange Gabriel",carac:"VïgT2M22*2s2J0",melee:[rouge,rouge,rouge,noir],defense:[noir,noir],pdv:6,desc:"%MELEE%: %BOUCLIER% &rarr; %BONUSMOVE%%BR%%ACTIVATED%: %TOURCOND%, %LOOK2%"},
{nom:"Archange Raphaël",carac:"VïuM22j4*1tpJ0",b1:[560,7,APOCALYPSE,0,0,0,1],b2:[560,7,APOCALYPSE,0,0,0,1],b3:[560,7,APOCALYPSE,0,0,0,1],melee:[rouge_bouclierxp,rouge_bouclierxp,rouge_bouclierxp,jaune_bouclierxp],defense:[noir,noir],pdv:4,desc:"%TOUTTYPE%%HERE%: + %CHARGE%"},
    {nom:"Archange Raphaël",carac:"VïR1M32*2ts2J0S",melee:[rouge,rouge,rouge,blanc],defense:[noir,noir,noir],pdv:4,desc:"%ACTIVATED%: %TOURCOND%, %XP%%XP% &rarr; +1 %JAUNE%"},
    {nom:"Archange saint Michel",carac:"VïMA3*2R1os2",melee:[rouge,rouge,rouge,blanc,blanc],defense:[noir,blanc,blanc],pdv:6,bonusmelee:[rouge,rouge,rouge,rouge,blanc,blanc],bonuscond:silegende,desc:"%ACTIVATED% %XP%: %TOURCOND%, +1 %BLEU%"},
    {nom:"Arche d'Alliance",carac:"IïM12pT3",b1:[360,4,APOCALYPSE,0,0,0,1],b2:[360,4,APOCALYPSE,0,0,0,1],b3:[360,4,APOCALYPSE,0,0,0,1],tir:[rouge,rouge,rouge],defense:[noir,noir],pdv:3,typetir:CLOCHE,portee:2,desc:"%MONTOUR%: -1 %LEGENDE% ou retirez %THIS%"},
{nom:"Archevêque Pierre de Cros",carac:"IïypM12*2",defense:[noir],pdv:3},
{nom:"Arthur de Richemont",carac:"C%peM13*2",melee:[rouge,rouge,blanc],pdv:3,desc:"%ACTIVATED% %LEGENDE%%LEGENDE%: %TOURCOND%, %CHOOSE% 1 %CARTELEGENDE%%BR%%CONSEIL%: %ROLL% %DENOIR%: <span class='facenoir touche'></span> &rarr; -1 %GRIS% / %VERT% / %BLEU% / %JAUNE% %ADVERSAIRE%"},
    {nom:"Barral de Pontevès",carac:"C%cMA1*1j4",f3:[240,4,SOUTIEN,0,1],melee:[rouge,rouge],defense:[noir],pdv:2},
{nom:"Barral de Pontevès",carac:"C%clM12*2R1",subfaction:MAL,melee:[rouge,rouge],defense:[jaune,jaune,jaune],pdv:3},
{nom:"Bertrand du Guesclin",carac:"I%gM12*2oU",subfaction:MAL,melee:[rouge,rouge],defense:[rouge,blanc],pdv:5,desc:"%XP%%XP% %MELEE%: 1 %DEROUGE% &rarr; <span class='facerouge tue'></span>%BR%%MELEE%: %MORT% &rarr; %XP%"},
{nom:"Bertrand du Guesclin",carac:"I%cM11*2R1o",subfaction:BIEN,melee:[rouge,noir,jaune],defense:[rouge,blanc],pdv:5,desc:"%CAMP%: %RALLIE%<span class='troupe combat-cond'></span>%BR%%ACTIVATED%: %ROUNDCOND%, +1 %BLEU%"},
{nom:"Captal de Buch",carac:"I£cM22*2v",melee:[rouge,noir],defense:[noir,rouge],pdv:3,desc:"%ACTIVATED% %LEGENDE%: %TOURCOND%, + <span class='commandement'>&nbsp;&nbsp;&nbsp; 1</span> / <span class='commandement'><span style='color:black;text-shadow:1px 1px;'>1</span></span>%BR%%ACTIONPLAYER% %XP%: %TOURCOND%, +1 %BLEU%"},
{nom:"Charles II le Magnanime",carac:"C%xMA1*1j4R1c",f1:[310,4,PERSONNAGE,1,2],melee:[jaune_blanclegende,jaune_blanclegende],defense:[blanc_blanccarte,blanc_blanccarte],pdv:2},
{nom:"Charles d'Albret",carac:"I%cxyM22*2j4",melee:[rouge,blanc],defense:[noir,noir],pdv:4,desc:"%MONTOUR% %XP%: %GRIS% &rarr; %VERT%%BR%une zone ennemie adjacente vient d'être activée: + %MELEE%"},
{nom:"Charles de Bourbon",carac:"C%x*2cx",melee:[rouge,rouge,jaune_blanclegende],defense:[noir],pdv:3,desc:"%ACTIVATED% %LEGENDE%%LEGENDE%: +1 %RUMEUR%"},
{nom:"Comte d'Arundel",carac:"I£GM12*2",melee:[rouge,rouge],defense:[noir],pdv:3,desc:"%ACTIVATED%: %TOURCOND%, %MOVE% %THIS% %HEREANDTHEREHEXA%"},
    {nom:"Comte d'Oxford",carac:"I£cM12*2R1T1",melee:[noir,jaune],defense:[rouge,blanc,blanc],pdv:3,bonusmelee:[rouge,rouge,blanc,blanc],bonuscond:si3troupesinfanterie, desc:"%DEFENSE%,%NOPLAIN%: %TOUCHE% &rarr; %RECUL%" },
    {nom:"Comte de Northampton",carac:"I£pM12*2",melee:[rouge,noir],defense:[noir],pdv:2,bonusdefense:[noir,jaune],bonuscond: si2troupesinfanterie,desc:"%TROUPE%%HERE%: + %MASSE%"},
{nom:"Comte de Salisbury",carac:"I£uM12*2R1v",melee:[rouge,noir],defense:[rouge,noir],pdv:3,desc:"1 %UNITE(Archers)%%HERE%%TIRCLOCHE%: +1 %DEROUGE%%BR%%LEGENDE% %ACTIVATED%: %TOURCOND%, + %CELERITE% 2"},
{nom:"Comte de Suffolk",carac:"I£uM12*2",melee:[rouge,rouge],defense:[blanc,blanc],pdv:2,desc:"%TROUPE%%HERE%: + %COHESION%"},
{nom:"Comte de Warwick",carac:"I£cgM13*2P1",melee:[rouge,noir,blanc],defense:[rouge,noir],pdv:4,desc:"%ACTIVATED% %XP%: %TOURCOND%, %INFANTERIE%<span class='troupe combat-cond'></span>%HERE% + %CELERITE% 2%BR%%MONTOUR% %LEGENDE%: + <span class='commandement'>&nbsp;&nbsp;&nbsp; 1</span>" },
    {nom:"Dracula",carac:"IâM31*2T2s3",melee:[rouge,rouge,rouge],defense:[noir,noir],pdv:4,bonusmelee:[rouge_boucliertue,rouge_boucliertue,rouge_boucliertue],bonuscond:silegende,desc:"%MELEE%: %MORT% &rarr; -1 %BLESSURE% à %THIS%"},
{nom:"Echelles",carac:"A",s1:[20,0,TOURDESIEGE,0,0,2,4]},
{nom:"Edmond de Sommerset",carac:"I£eM12*2R1da",melee:[noir,jaune,jaune],defense:[blanc,rouge],pdv:3,desc:"%MONTOUR%: +1 %LEGENDE%"},
{nom:"Edouard III",carac:"I£yM23*2aS",melee:[rouge,rouge,rouge],defense:[noir,noir],pdv:2,desc:"%CAMP%: %RALLIE%<span class='troupe combat-cond'></span>%BR%%ACTIVATED% %LEGENDE%%LEGENDE%: %ROUNDCOND%, %GRIS% &rarr; %JAUNE%"},
{nom:"Edouard d'York",carac:"I£cgM23*2U",melee:[noir,jaune,jaune],defense:[noir,rouge],pdv:3,modattaque:transformetoucherecul,desc:"%MONTOUR%: +1 %LEGENDE%"},
{nom:"Erwan de Romorantin",carac:"I%M12*2",melee:[rouge,rouge],defense:[noir,noir],pdv:3,desc:"%UNITE(Paysans)%%HERE%,%UNITE(Milice Bourgeoise)%%HERE%,%MELEE% +1 %DEJAUNE%"},
{nom:"Gilles de Rais",carac:"I%M11*2oa",subfaction:BIEN,melee:[rouge,rouge,jaune,jaune],defense:[noir,jaune],pdv:3,desc:"%ACTIVATED%: au début d'activation,%MOVE% 1+ %RALLIEMENT%%BR%%MELEE%: 1+ <span class='facejaune vierge'></span> &rarr; %REROLL% 1 %DEROUGE% / %DEJAUNE%"},
{nom:"Gilles de Rais",carac:"I%MA3*2a",subfaction:MAL,melee:[noir,jaune],defense:[blanc,blanc],pdv:2,desc:"%ACTIVATED% %XP%%XP%: %TOURCOND%, placez une troupe alliée détruite dans la zone de %THIS%%BR%%ACTIVATED% %XP%%XP%%XP%: %TOURCOND%, une troupe ennemie adjacente à %THIS% rejoint sa zone et passe sous votre controle"},
{nom:"Guillaume de Molins",carac:"I£pF1M11*2P1",melee:[rouge],defense:[noir],pdv:3},
{nom:"Henry V",carac:"I£GM22*2v",subfaction:BIEN,melee:[rouge,jaune],defense:[noir],pdv:3,desc:"%ROUNDCOND%: vous pouvez jouer 2 %BLEU% à la suite%BR%%ACTIVATED%: %MONTOUR%, %MOVE%%THERE% %THIS%"},
{nom:"Henry V",carac:"I£cGM33*2v",subfaction:MAL,melee:[rouge,blanc],defense:[noir,noir],pdv:3,desc:"<span class='blason-large mal'></span>%HERE%: + %CHARGE%%BR%%MONTOUR%: +1 %BLEU%"},
{nom:"Héros monté",carac:"C%cM11*2",melee:[rouge,rouge],defense:[noir],pdv:3},
{nom:"Héros monté",carac:"C£cM11*2",melee:[rouge,rouge],defense:[noir],pdv:3},
{nom:"Héros monté",carac:"C%cMA1*1j3",f2:[210,3,PERSONNAGE,1,2],f1:[200,4,PERSONNAGE,1,2],melee:[rouge,rouge],defense:[noir],pdv:2},
{nom:"Héros monté",carac:"C£cMA1*1j3",a3:[200,3,PERSONNAGE,1,2],a2:[210,3,PERSONNAGE,1,2],a1:[200,3,PERSONNAGE,1,2],melee:[rouge,rouge],defense:[noir],pdv:2},
{nom:"Héros monté",carac:"CïcM11*2",melee:[rouge,rouge],defense:[noir],pdv:2},
{nom:"Héros monté",carac:"CïcMA1*1j3",b1:[200,4,PERSONNAGE,1,2],b2:[210,3,PERSONNAGE,1,2],melee:[rouge,rouge],defense:[noir],pdv:2},
{nom:"Héros",carac:"I%pM11*2P1",subfaction:BIEN,melee:[rouge],defense:[noir],pdv:2},
{nom:"Héros",carac:"I%pMA2*2T1",subfaction:MAL,melee:[blanc_blanctouche,jaune_blanctouche],defense:[blanc,blanc],pdv:2},
{nom:"Héros",carac:"I£pM11*2P1",subfaction:BIEN,melee:[rouge],defense:[noir],pdv:2},
{nom:"Héros",carac:"I£pMA2*2T1",subfaction:MAL,melee:[blanc_blanctouche,jaune_blanctouche],defense:[blanc,blanc],pdv:2},
{nom:"Héros Lituanien",carac:"IùF1M11*2P1",subfaction:MAL,melee:[rouge,blanc,blanc],defense:[blanc,rouge],pdv:2,desc:"%MELEE%%FORET%: %RECUL% &rarr; %TOUCHE%"},
{nom:"Jacques de Bourbon",carac:"I%M12*2",melee:[rouge,rouge],defense:[noir],pdv:3,desc:"%DEFENSE%: %TOUTTYPE%%HERE% &rarr; +1 %BOUCLIER%"},
    {nom:"Jean II Le Bon",carac:"I%cxM13*2R1",melee:[rouge,rouge,blanc],defense:[rouge],pdv:4,desc:"%MONTOUR%: +1 %VERT% / %JAUNE%%BR%%CONSEIL%: 2 %XP%"},
{nom:"Jean II de Luxembourg",carac:"I£MA1*2aEg",melee:[noir,blanc],defense:[blanc,jaune],pdv:2,desc:"%DEFENSE%:  si %THIS% ne peut se déplacer dans une zone adjacente à la suite d'un %RECUL%,annulez ce %RECUL%"},
{nom:"Jean Stuart de Buchan",carac:"IécxhM12*2",melee:[rouge,blanc],defense:[blanc],pdv:3,desc:"%UNITE(Sergents d'armes)%<span class='commandementhexa combat-cond'></span>: %CANDOACTION% %CHARGE%%BR%%UNITE(Sergents d'armes)%%HERE%: + %CHARGE%"},
{nom:"Jean Stuart de Derneley",carac:"IécF1MA2*2",melee:[rouge,noir],defense:[noir],pdv:3,desc:"%MELEE%: %MORT% &rarr; reprenez le jeton de relance si vous ne l'avez plus%BR%%POURSUITE%: +1 %LEGENDE%"},
{nom:"Jean de Bourbon",carac:"I%cM22*2j4R1L",melee:[blanc,blanc,noir],defense:[noir,noir],pdv:3,desc:"%ACTIVATED% %XP%: %TOURCOND%, %GRIS% &rarr; %VERT%"},
{nom:"Jean de Dunois",carac:"I%pMA1*2U",subfaction:MAL,melee:[rouge,noir,blanc],defense:[noir],pdv:3,desc:"%ACTIVATED% 1 %TROUPE%%THERE%%MELEE%: %TOURCOND%, +1 %DENOIR%%BR%%DEFENSE%: %LEGENDE%%LEGENDE% &rarr; %REROLL% %DEBLANC%<span class='melee combat-cond'></span>"},
{nom:"Jean de Dunois",carac:"I%ueM12*2",subfaction:BIEN,melee:[rouge,jaune,noir],defense:[noir,noir],pdv:3,desc:"%ACTIVATED% %LEGENDE%%ROUNDCOND% : %GRIS% &rarr; %BLEU%%BR%%ACTIVATED%: %ROUNDCOND%, %MOVE% 1 %RALLIEMENT%"},
{nom:"Jean de Lancastre",carac:"I£yM11*2R1",subfaction:BIEN,melee:[rouge,blanc],defense:[jaune,jaune,blanc_blancbouclier],pdv:2,desc:"%MONTOUR%: 1 %GRIS%/%VERT%/%BLEU%/%JAUNE% &rarr; 1 %GRIS%/%VERT%/%BLEU%/%JAUNE%"},
{nom:"Jean de Lancastre",carac:"I£yM12*2R1",subfaction:MAL,melee:[noir,jaune_blanclegende,jaune_blanclegende],defense:[noir,noir],pdv:2,modattaque:annule1touche,desc:"%MELEE%: <span class='facenoir touche'></span> &rarr; %LEGENDE%"},
    {nom:"Jean de Vienne",carac:"I%g*2Sp",melee:[jaune,jaune,jaune],defense:[noir,blanc],pdv:3,desc:"%ACTIVATED%: -1 %CARTELEGENDE% &rarr; +1 %CARTELEGENDE%%BR%%ACTIVATED%: %ROUNDCOND%, %ROLL% 1 %DENOIR%,<span class='facenoir bouclier'></span> &rarr; -1 %LEGENDE% %ADVERSAIRE% / +1 %CARTELEGENDE%"},
    {nom:"Jeanne d'Arc",carac:"C%M22*2R1_T2r2",subfaction:MAL,melee:[rouge,blanc],defense:[blanc,rouge],pdv:4,desc:"%MELEE% / %DEFENSE%: <span class='faceblanc vierge'></span> &rarr; %LEGENDE% / %CARTELEGENDE%%BR%2 %TOUTTYPE%%HERE%%MELEE%: +1 %DEBLANC%"},
    {nom:"Jeanne d'Arc",carac:"C%ypM32*2_r2P",subfaction:BIEN,melee:[blanc,blanc],defense:[noir,noir],pdv:3,desc:"%ACTIVATED%: %ROUNDCOND%, +1 %JAUNE%%BR%%ACTIVATED% %ROLL% le dé du Destin: %RALLIE% &rarr; %TOUTTYPE%%RALLIE%"},
{nom:"Jeanne d'Arc",carac:"I%M22*2R1T2",subfaction:MAL,melee:[rouge,jaune],defense:[rouge,jaune],pdv:4,desc:"%ACTIVATED%: %ROUNDCOND%, en fin d'activation, jouez un %JAUNE%  depuis la réserve commune dans la zone sitée jusqu'à 3 zones de distance de %THIS%%BR%%ACTIVATED%: %ROUNDCOND%, +1 %LEGENDE%, +1 %CARTELEGENDE%"},
{nom:"Jeanne d'Arc",carac:"I%up*0",defense:[noir],pdv:2,desc:"%STARTGAME% +1 %CARTELEGENDE%,+1 %LEGENDE%"},
{nom:"Jeanne d'Arc",carac:"I%upM32*2T1",subfaction:BIEN,melee:[blanc,jaune],defense:[noir,noir],pdv:3,desc:"%ACTIVATED%: %ROUNDCOND%, en fin d'activation,jouez %JAUNE% depuis la réserve commune dans la zone sitée jusqu'à 3 zones de distance de %THIS%%BR%%CAMP%: %RETARDE% &rarr; %RALLIE%"},
{nom:"John Chandos",carac:"I£gMA3*2o",subfaction:MAL,melee:[noir,noir,noir],defense:[noir],pdv:4,bonusattaque:untouchetue,desc:"%MONTOUR%: +1 %GRIS%"},
{nom:"John Chandos",carac:"I£uM12*2R1",subfaction:BIEN,melee:[rouge,noir],defense:[rouge,rouge,rouge],pdv:3,desc:"%CONSEIL%: +1 %GRIS%,+1 %XP%"},
{nom:"John Fastolf",carac:"I£M21*2P1Uo",subfaction:MAL,melee:[rouge],defense:[noir],pdv:3,desc:"%DEFENSE%: %TOUCHE% &rarr; %RECUL%,vous pouvez l'affecter à une autre de vos unités%HEREANDTHERE%"},
{nom:"John Fastolf",carac:"I£cM12*2R1",subfaction:BIEN,melee:[rouge_recultouche,rouge_recultouche],defense:[noir],pdv:2,desc:"%ACTIVATED% %XP%: %MOVE% 1 %CAVALERIE% alliée d'une zone"},
{nom:"John Talbot",carac:"I£cF1M13*2P1",subfaction:BIEN,melee:[rouge,rouge],defense:[noir],pdv:4,desc:"%MONTOUR%: +1 %GRIS%"},
{nom:"John Talbot",carac:"I£cM12*2T1",subfaction:MAL,melee:[rouge,rouge],defense:[noir],pdv:3,desc:"%ONCEINGAME% +2 %UNITE(Chiens de Guerre)%%HERE%%BR%%UNITE(Chiens de Guerre)%%HERE%: + %CHARGE%"},
{nom:"John de la Pôle",carac:"I£yM11*2",melee:[rouge,noir],defense:[blanc,jaune],pdv:3,desc:"%MELEE%: %BOUCLIER% &rarr; +1 %LEGENDE%, +1 %CARTELEGENDE%"},
    {nom:"Jugement",carac:"VïT2lgDJ0M33",melee:[rouge,rouge,rouge,rouge],defense:[noir,noir],pdv:12,desc:"%MELEE%: %BOUCLIER% &rarr; +1 %LEGENDE% /  +1 %CARTELEGENDE%"},
    {nom:"L'Agneau de Dieu",carac:"IïM43Dpy",b1:[300,2,APOCALYPSE,0,0,0,1],b2:[300,2,APOCALYPSE,0,0,0,1],b3:[300,2,APOCALYPSE,0,0,0,1],defense:[noir,blanc],pdv:2,desc:"%ACTIVATED%: %TOURCOND%, %LEGENDE% &rarr; %RALLIE%<span class='combat-cond troupe'></span>"},
    {nom:"L'Antéchrist",carac:"IâM24DpT2l",m1:[750,7,APOCALYPSE,0,0,0,1],m2:[750,7,APOCALYPSE,0,0,0,1],m3:[750,7,APOCALYPSE,0,0,0,1],defense:[blanc,blanc],pdv:3,desc:"%TOUTTYPE%%HERE%, %DEFENSE%: +1 %DENOIR%%BR%%ACTIVATED%: %TOURCOND%, %ROLL% %DENOIR%: %BOUCLIER% &rarr; placez une troupe ennemie à 2 zones de %THIS% dans sa zone."},
    {nom:"La Conquête",carac:"Câ*1M32Ds2uj6c",melee:[blanc,blanc,jaune],defense:[blanc],tir:[jaune,jaune],portee:3,typetir:TENDU,m1:[310,4,APOCALYPSE,0,0,0,1],m2:[310,4,APOCALYPSE,0,0,0,1],m3:[310,4,APOCALYPSE,0,0,0,1],pdv:5,desc:"%MELEE%: %ANNULER% 1+ %BOUCLIER%"},
    {nom:"La Conquête",carac:"Câ*2M33Ds2uc",melee:[rouge,blanc,blanc],defense:[blanc,blanc],tir:[jaune,jaune,jaune],portee:3,typetir:TENDU,pdv:6,desc:"%TOUTTYPE%<span class='combat-cond mal'></span>: %POURSUITE% &rarr; +1 %LEGENDE% / +1 %CARTELEGENDE%"},
    {nom:"La Mort",carac:"Câ*1M22Dr2j5T1",m1:[350,6,APOCALYPSE,0,0,0,1],m2:[350,6,APOCALYPSE,0,0,0,1],m3:[350,6,APOCALYPSE,0,0,0,1],melee:[rouge,rouge],defense:[noir],pdv:4,desc:"%ACTIVATED%: %XP% &rarr; -1 %BLESSURE%<span class='combat-cond mal'></span>%BR%%MELEE%: %TUE% &rarr; +1 %LEGENDE%%BR%%MELEE%: %TUE%<span class='combat-cond bien'></span> &rarr; +2 %LEGENDE%"},
    {nom:"La Mort",carac:"Câ*2M22Dr2T2",melee:[noir_boucliertue,noir_boucliertue],defense:[noir],pdv:5,desc:"%DEFENSE%: %LEGENDE% &rarr; 1 %TOUTTYPE%<span class='mal combat-cond'></span>, %DEFENSE%: +1 %DENOIR%"},
    {nom:"La Famine",carac:"Câ*1M21Duj5",m1:[230,4,APOCALYPSE,0,0,0,1],m2:[230,4,APOCALYPSE,0,0,0,1],m3:[230,4,APOCALYPSE,0,0,0,1],melee:[noir,blanc],defense:[noir,noir],pdv:3,desc:"%DEBUTACTIVATION%: %UNITEENNEMIE%%THERE% &rarr; +1 %LEGENDE%, -1 %LEGENDE% %ADVERSAIRE%%BR%%MELEE%: %LEGENDE% &rarr; +1 %MELEE%"},
    {nom:"La Famine",carac:"Câ*2M21Dpu",melee:[jaune_blancrecule,jaune_blancrecule,jaune_blancrecule],defense:[noir,noir],pdv:3,desc:"%XP%%XP%%XP%, %MELEE%: 3 zones<span class='combat-cond melee'></span>"},
    {nom:"La Guerre",carac:"Câ*1M23Dj6R1P1o",m1:[320,5,APOCALYPSE,0,0,0,1],m2:[320,5,APOCALYPSE,0,0,0,1],m3:[350,5,APOCALYPSE,0,0,0,1],melee:[rouge_touchetue,blanc_touchetue],defense:[rouge],pdv:6},
    {nom:"La Guerre",carac:"Câ*2M23DR1P1o",melee:[rouge_touchetue,rouge_touchetue,blanc_touchetue],defense:[noir,rouge],pdv:6,desc:"%POURSUITE%: +1 %MELEE%, -1 %BOUCLIER%"},
{nom:"La Hire",carac:"I%*2T2",subfaction:MAL,melee:[rouge,rouge,blanc,blanc],defense:[rouge,blanc],pdv:4,desc:"X %BLESSURE% &rarr; %MELEE%: +X %DEROUGE%%BR%%MELEE%: %MORT% &rarr; %XP%%XP%"},
{nom:"La Hire",carac:"I%cMA2*2R1",subfaction:BIEN,melee:[rouge,rouge,rouge],defense:[rouge,rouge],pdv:5,desc:"X %BLESSURE% &rarr; %MELEE%: +X %DENOIR%"},
{nom:"La Tarasque",carac:"Iâ*2T1R1D",postattaque:doubleblessure,melee:[rouge,rouge,rouge],defense:[noir,noir],pdv:10},
{nom:"Lala Sahin Pacha",carac:"I?yM22*2T1r2",melee:[rouge,rouge],defense:[noir],pdv:3,desc:"%ACTIVATED% %LEGENDE%: %TOURCOND%, %GRIS% &rarr; %JAUNE%/%BLEU%%BR%%BLEU%%HERE%%ROUNDCOND%: vous pouvez jouer  %BLEU%%HERE% à la suite"},
{nom:"Le Prince Noir",carac:"C£cF1MA3*2_",subfaction:MAL,melee:[rouge,rouge,rouge,jaune],defense:[noir],pdv:3,desc:"%ACTIVATED% %LEGENDE%: <span class='commandement'><span style='color:black;text-shadow:1px 1px;'>3</span>&nbsp;&nbsp;6</span>%BR%le trait %VISEE% ne peut pas être utilisé contre %THIS%"},
{nom:"Le Prince Noir",carac:"C£cM12*2_r2",subfaction:BIEN,melee:[rouge,rouge,jaune],defense:[noir],pdv:4,desc:"%MONTOUR%: +3 %CARTELEGENDE%,%DEFAUSSEZEN% 2%BR%%MONTOUR% %LEGENDE%: %GRIS% &rarr; %VERT%"},
{nom:"Le Prince Noir",carac:"I£M12*2UT2",subfaction:MAL,melee:[rouge,rouge,rouge],defense:[noir],pdv:3,desc:"au début de votre tour,%ROLL% 1 %DENOIR%: <span class='facenoir touche'></span> &rarr; -1 %LEGENDE% %ADVERSAIRE%%BR%%ACTIVATED% %XP%%XP%: +2 %CARTELEGENDE%"},
{nom:"Le Prince Noir",carac:"I£cM12*2T1",subfaction:BIEN,melee:[rouge,rouge],defense:[noir],pdv:3,desc:"%MONTOUR%: +1 %BLEU%%BR%%ACTIVATED%: %MOVE% 1 %RALLIEMENT%"},
{nom:"Loup-garou",carac:"IâM11*2or2",melee:[noir,blanc],defense:[noir],pdv:2,desc:"<span class='niveau1 combat'></span> &rarr; <span class='combat niveau2'> </span>: +1 %UNITE(Loups)%%HERE%"},
    {nom:"Maréchal Arnoul d'Audrehem",carac:"I%cxM22*2R1",melee:[rouge,rouge],defense:[noir,noir],pdv:3,desc:"%ACTIVATED% %XP%: %TOURCOND%, %GRIS% &rarr; %VERT%%BR%%PERSONNAGE%%HERE%: + %PARADE%"},
{nom:"Maréchal Jean de Clermont",carac:"I%cxM12*2R1L",melee:[rouge,rouge],defense:[noir,rouge],pdv:3,desc:"%TROUPE%%HERE%: + %COHESION%"},
{nom:"Mehmet II",carac:"I?ypeM12*2",melee:[rouge],defense:[noir,blanc],pdv:2,desc:"%ACTIVATED% %XP%: %ROUNDCOND%, +1 %GRIS%"},
{nom:"Narimantas",carac:"CùcgM21*2v",melee:[rouge,rouge],defense:[noir],pdv:3,desc:"%DEFENSE%: %TOUCHE%/ %RECUL%/ %TUE% &rarr; +1 %RIPOSTE% %RECUL%."},
    {nom:"Perkunas",carac:"VùliM21*2T2s3",melee:[rouge,noir],tir:[violet_recultue],portee:1,typetir:CLOCHE,defense:[unbouclier,unbouclier],pdv:4,grand:true},
{nom:"Philippe VI de Valois",carac:"C%pM21c*2",subfaction:MAL,melee:[rouge,rouge],defense:[noir,noir],pdv:3,desc:"%TROUPE%%HERE%%DEFENSE%: + %GARDEDUCORPS%%BR%%ACTIVATED% %LEGENDE%: au début d'activation,+ <span class='commandement'>&nbsp;&nbsp;&nbsp; 1</span>"},
{nom:"Philippe VI de Valois",carac:"C%pM32*2Lc",subfaction:BIEN,melee:[rouge,rouge],defense:[noir,noir],pdv:3,desc:"%TROUPE%%HERE%: + %CHARGE%"},
{nom:"Philippe d'Orléans",carac:"I%cgyM13*2a",melee:[rouge,noir],defense:[noir,jaune],modattaque:annule1recul,pdv:3,desc:"X %BLESSURE% &rarr; %MELEE%: +X %RECUL%"},
{nom:"Radu III le Beau",carac:"I!F1M11*2a",melee:[blanc,blanc],defense:[noir],pdv:2,desc:"%ACTIVATED%: %ROUNDCOND% %XP%%XP% &rarr; %MOVE% une unité ennemie d'une zone"},
{nom:"Roi Casimir IV de Lituanie",carac:"CùcF1M12*2P1R1",melee:[rouge,rouge],defense:[noir,blanc],pdv:4,desc:"%DEFENSE%,%THIS% seul dans sa zone: 2 %TOUCHE% &rarr; 2 %RECUL%"},
{nom:"Sainte Marthe",carac:"Iïp*2T0T2",melee:[jaune,jaune,jaune],defense:[noir],pdv:2,modattaque:touchetuerecul},
{nom:"Simon Morhier",carac:"I£GMA1*2P1",melee:[rouge],defense:[noir,noir],pdv:2,desc:"%INFANTERIE%%INFANTERIE%<span class='troupe combat-cond'></span>%HERE%%MELEE%: +1 %DEBLANC%"},
{nom:"Sorcière des marais",carac:"IâM11*2",melee:[blanc],defense:[noir,noir],pdv:3,desc:"quand elle est dans une zone de marais,%THIS% ignore les effets de terrains liés aux marais et peut réaliser une action de mouvement vers n'importe quelle autre zone de marais du plateau de jeu%BR%%ACTIVATED% %LEGENDE%%LEGENDE%: %TOURCOND%, posez ou déplacez un jeton Marais sur une zone qui n'est pas une zone de village"},
    {nom:"Sorcière",carac:"Iâ*2s2",melee:[blanc],defense:[blanc],pdv:2,bonusmelee:[blanc_blanctue],bonuscond:sicartelegende},
{nom:"Thomas Kyriel",carac:"I£F1M22*2v",melee:[noir_blanclegende,jaune_blanclegende,jaune_blanclegende],defense:[jaune,rouge],pdv:3,desc:"1 %UNITE(Archers)%%HERE%%TIRCLOCHE%: %TOURCOND% +1 %DEROUGE%"},
{nom:"Thomas de Scales",carac:"C£M11*2R1oc",melee:[rouge],defense:[noir,noir],pdv:3,desc:"une fois pendant votre tour,%POURSUITE%: +1 %MELEE%"},
{nom:"Vlad Tepes",carac:"I!F1M21*2P1T1r2",melee:[rouge,noir],defense:[noir,blanc],pdv:3,desc:"%MELEE%: un des %TOUCHE% ne peut être annulé par %BOUCLIER%%BR%%ACTIVATED% %XP%: %TOURCOND%, %MOVE% 1 %RALLIEMENT%"},
{nom:"William Glasdale",carac:"I£F1M13*2R1",melee:[rouge,rouge],defense:[blanc,blanc],pdv:3,modattaque:annule1touche},
{nom:"William Wallace",carac:"IéceM12*1j2",e1:[250,3,PERSONNAGE,1,2],melee:[blanc,jaune],defense:[blanc],pdv:2,desc:"%ACTIVATED%: %TOURCOND%, 1+ %TROUPE%%HEREANDTHERE% + %CHARGE%%BR%%ACTIVATED%: %ROUNDCOND%, %CHOOSEZONE%%THERE% &rarr; %1ORDERTOACTIVATE%"},
{nom:"William Wallace",carac:"IécxMA2*2",subfaction:MAL,melee:[noir],defense:[rouge,noir],pdv:2,desc:"%POURSUITE%: %ROUNDCOND%, +1 %MELEE%%BR%%MELEE%: <span class='facenoir bouclier'></span> &rarr; %BONUSMOVE% / +1 %XP%"},
{nom:"William de la Pôle",carac:"C£cM11*2",melee:[rouge,rouge],defense:[noir],pdv:2,desc:"1 %UNITE(Archers)% dans cet hexagone %TIRCLOCHE%: +1 %DEROUGE%"},
{nom:"Winrich von Kniprod",carac:"C€cF1M11*2",melee:[rouge,blanc,blanc],defense:[noir,blanc],pdv:3,desc:"%MELEE%: si %THIS% obtient au moins 2 %TOUCHE%,l'attaque de %THIS% ne peut pas être bloquée par des résultats %BOUCLIER%"},
{nom:"Yildirim Bayezid",carac:"I?cM13*2Ur2",melee:[rouge_bouclierrecule,rouge_bouclierrecule,noir_bouclierrecule],defense:[noir,noir],pdv:4,desc:"%MONTOUR% %XP%: %TROUPE%%HERE% + Célérité 2"},
{nom:"Adeptes",carac:"Iâ",m2:[80,1,FANTASSINS,0,0,1,0],melee:[rouge],defense:[noir],desc:"quand ils sont dans une zone de marais,%THIS% ignorent les effets de terrain liés aux marais et peuvent réaliser un mouvement vers n'importe quelle autre zone de marais du plateau de jeu"},
    {nom:"Aitvaras",carac:"IùT1qi*1",pdv:3,melee:[rouge,rouge,blanc],defense:[jaune,jaune],desc:"%DEFENSE%: %THIS% réussit son jet d'esquive &rarr; +1 %INCENDIE%%HERE%%BR%%TOUTTYPE%: %TUE%<span class='jetonincendie combat-cond'></span> &rarr; +1 %LEGENDE%"},
    {nom:"Alain Blanchard",carac:"I%",f3:[230,2,PERSONNAGE,1,2],melee:[rouge,jaune],defense:[rouge],pdv:2,tir:[noir_bouclierrecule,noir_bouclierrecule],portee:3,typetir:TENDU},
{nom:"Almogavres",carac:"IqR0",f2:[65,1,HAST,0,5],f3:[70,1,HAST,2,6],a2:[65,1,HAST,2,6],a3:[65,1,HAST,0,5],melee:[blanc],defense:[jaune]},
{nom:"Amaury de Craon",carac:"C%MA2*2",melee:[rouge,rouge],defense:[noir,noir],pdv:2,desc:"%ACTIVATED%: %ROUNDCOND%, %MOVE% %THIS%%HEREANDTHERE2%"},
{nom:"Amaury de Sévérac",carac:"I%M12*1j3R1E",melee:[blanc,blanc],defense:[rouge,rouge],pdv:2,desc:"%BLESSURE% &rarr; %XP%"},
{nom:"Ambroise de Loré",carac:"C%cJ1MA1*1j4",f3:[270,3,PERSONNAGE,1,2],melee:[rouge],defense:[noir],pdv:2,desc:"%ACTIVATED%: %ROUNDCOND%, +1 %VERT%"},
    {nom:"Ange annonciateur",b1:[260,2,APOCALYPSE,0,0,0,1],b2:[260,2,APOCALYPSE,0,0,0,1],b3:[260,2,APOCALYPSE,0,0,0,1],carac:"VïF1uM32J0",defense:[noir,noir],desc:"%ACTIVATED%: %TOURCOND%, %MOVE%%THERE% 1+ %UNITE(Ange)%"},
{nom:"Ange destructeur",carac:"VïG",b3:[220,3,VOLANTS,0,0,0,2],tir:[rouge,noir],defense:[noir,noir],typetir:TENDU,portee:3,desc:"%MELEE%<span class='batiment combat-cond'></span>: %ROUNDCOND%, %BOUCLIER% &rarr; +1 %DETRUIT%"},
    {nom:"Ange Glorieux",carac:"Vïs3*1",pdv:3,melee:[rouge,rouge,rouge],defense:[noir,noir],desc:"%ACTIVATED%: %ROUNDCOND%, %XP%%XP%%XP% &rarr; bénéficiez des effets d'une carte du Conseil de guerre"},
    {nom:"Ange",carac:"Vïtps2",b2:[230,4,VOLANTS,0,0,0,2],b3:[230,4,VOLANTS,0,0,2,2],melee:[rouge,blanc],bonusmelee:[rouge,blanc,blanc],bonuscond:simal,defense:[noir,noir]},
{nom:"Apothicaire",carac:"ISw",defense:[blanc],desc:"%ACTIVATED% %CARTELEGENDE%: %TOURCOND%, +2 %LEGENDE% / +2 %XP% / +1 %CARTELEGENDE%"},
{nom:"Arbalétriers Génois",carac:"I",f1:[80,1,ARBA,0,4],typetir:TENDU,portee:1,tir:[rouge],defense:[noir],desc:"%ACTIVATED%: %ENTRENCH% %THIS%"},
{nom:"Arbalétriers Génois",carac:"Ik",prenom:"Retranchés",typetir:TENDU,portee:1,tir:[rouge,blanc],defense:[noir,blanc],desc:"%THIS% %NOMOVE%"},
{nom:"Arbalétriers montés",carac:"Cr2",tir:[rouge,jaune],portee:1,typetir:TENDU,defense:[blanc],bonusattaque:recultouchesiplaine},
{nom:"Arbalétriers",carac:"I",b2:[80,1,ARBA,0,0,0,3],f1:[75,1,ARBA,0,4],f3:[80,1,ARBA,0,0,0,4],typetir:TENDU,portee:1,tir:[rouge_bouclierrelance],defense:[blanc]},
{nom:"Arbre Sacré",carac:"IùR0T1",melee:[rouge,rouge,blanc],defense:[noir],pdv:4,grand:true,desc:"Si %THIS% est située dans une zone de forêt,elle peut déclarer une attaque de mélée depuis n'importe quelle autre zone de forêt contenant un arbre. Retirez ensuite cet arbre du jeu."},
    {nom:"Archange Gabriel",carac:"VïgM11J0*1j4s2T1",b1:[260,2,APOCALYPSE,0,0,0,1],b2:[260,2,APOCALYPSE,0,0,0,1],b3:[260,2,APOCALYPSE,0,0,0,1],melee:[rouge,rouge,rouge],defense:[noir,noir],pdv:5,desc:"%MELEE%: %BOUCLIER% &rarr; %BONUSMOVE%"},
    {nom:"Archange saint Michel",carac:"VïMA2*1j5R1os2",b1:[620,8,APOCALYPSE,0,0,0,1],b2:[620,8,APOCALYPSE,0,0,0,1],b3:[620,8,APOCALYPSE,0,0,0,1],melee:[rouge,rouge,rouge,blanc],defense:[noir,blanc,blanc],pdv:6,tir:[rouge,rouge],typetir:TENDU,portee:2,bonusmelee:[rouge,rouge,rouge,rouge,blanc],bonuscond:silegende},
    {nom:"Archers Arc Court",carac:"I",b1:[140,1,ARCHERS,0,0,0,4],f2:[125,1,ARCHERS,2,5],B1:[125,1,ARCHERS,2,5],tir:[noir,noir],defense:[blanc],typetir:TENDU,portee:1,desc:"%SONTOUR%: %ROUNDCOND%, +1 %TIRTENDU%"},
{nom:"Archers Azab",carac:"I?qr2",o1:[100,2,ARCHERS,0,6],tir:[jaune,jaune],defense:[jaune],typetir:TENDU,portee:1,desc:"%ACTIVATED%: %THIS% %CANPUTSTAKEHEDGE%"},
    {nom:"Archers Tatars",carac:"Cqr2",tir:[noir,jaune],portee:1,typetir:TENDU,defense:[blanc],desc:"%DEFENSE%: %ESQUIVE% &rarr; + %RIPOSTE% %DEJAUNE%"},
    {nom:"Archers bourguignons",B1:[140,1,ARCHERS,2,5],carac:"Im",typetir:TENDU,portee:1,tir:[noir,noir],defense:[blanc],desc:"%SONTOUR%:  %TOURCOND%, %MOVEENNEMI%%THERE% &rarr; +1 %TIRTENDU%"},
{nom:"Archers montés",carac:"Cr2",a1:[130,1,CAVAL,0,3],a2:[125,1,CAVAL,2,4],a3:[135,1,CAVAL,0,0,0,3],tir:[blanc,blanc],typetir:CLOCHE,portee:2,defense:[noir]},
{nom:"Archers",carac:"I",e1:[140,1,ARCHERS,2,4],a1:[125,1,ARCHERS,0,0,3,3],a2:[115,1,ARCHERS,0,0,2,2],a3:[135,1,ARCHERS,0,0,4,4],tir:[jaune_boucliertouche,jaune_boucliertouche],defense:[blanc],typetir:CLOCHE,portee:2,desc:"%ACTIVATED%: %THIS% %CANPUTSTAKEHEDGE%"},
{nom:"Archevêque Pierre de Cros",carac:"IïpMA2*1j2",b2:[195,3,PERSONNAGE,1,2],defense:[rouge],pdv:2},
{nom:"Arnaud Amanieu d'Albret",carac:"I$yM11P1E",f1:[175,1,MERCEN,0,0,0,1],melee:[noir,jaune],defense:[noir],pdv:2,desc:"%MELEE%: %BOUCLIER% &rarr; %BONUSMOVE%%BR%%ACTIVATED%%LEGENDE%: %ROUNDCOND%, + <span class='commandement'>&nbsp;&nbsp;&nbsp; 1</span>"},
{nom:"Arnaud de Cervole",carac:"I$cpM12R1E",f1:[165,1,MERCEN,0,0,0,1],melee:[rouge,blanc],defense:[noir,rouge],pdv:3,desc:"aucun %BLEU% ne peut être joué par un adversaire dans une zone adjacente à %THIS%"},
    {nom:"Arthur de Richemont",patch:true,carac:"C%pMA2*1j5U",melee:[rouge,jaune],pdv:2,desc:"%ACTIVATED% %LEGENDE%: %TOURCOND%, %MOVE% %THIS%%BR%%TOUTTYPE%%HERE%: - Impetueux",f3:[250,3,PERSONNAGE,1,2]},
{nom:"Assassin",carac:"I£F1R1d",melee:[rouge,blanc],defense:[noir],pdv:2,desc:"%REVEALED%,%MELEE%: +1 %DEROUGE%"},
{nom:"Baliste",carac:"Av",s2:[120,2,CANON,0,0,1,1],tir:[noir_boucliertouche],defense:[unbouclier],typetir:TENDU,portee:3,pdv:2},
{nom:"Barral de Pontevès",carac:"C%cF1MA2*2o",subfaction:BIEN,melee:[rouge,rouge],defense:[noir,blanc],pdv:3},
{nom:"Baudoin de Lens",carac:"C%xpc",f2:[175,3,SOUTIEN,0,1],melee:[noir_bouclierrecule,noir_bouclierrecule],defense:[noir],pdv:2},
{nom:"Bernard Szumborski",carac:"I€F1M12",melee:[rouge,blanc],defense:[noir],pdv:3,desc:"%SPECIAL%: %THIS% peut déclarer une attaque contre une unité adjacente. Seul de jet d'attaque de %THIS% et le jet de défense de l'unité ciblée sont résolus."},
{nom:"Bertrand de Poulengy",carac:"I%ge",melee:[rouge],tir:[noir_bouclierrecule],typetir:TENDU,portee:1,defense:[rouge],pdv:2},
{nom:"Bertrand du Guesclin",carac:"I%cM11*1j5R1do",f1:[435,6,PERSONNAGE,1,2],melee:[rouge,noir],defense:[rouge],pdv:5,desc:"Lorsqu'il est mis hors de combat,%THIS% est directement placé dans la zone d'attente de l'infirmerie"},
{nom:"Bombarde",carac:"A",s2:[260,3,BOMBARDE,0,0,0,2],s1:[220,3,BOMBARDE,0,0,0,1],tir:[rouge,rouge,blanc_blanctue],defense:[unbouclier],typetir:CLOCHE,portee:2,pdv:2,desc:"%TIRCLOCHE%<span class='combat-cond batiment'></span>: 1+ %TUE% &rarr; 1 %DETRUIT%"},
{nom:"Boucicaut",carac:"I%yM22*1j4",melee:[rouge,jaune],f1:[405,5,PERSONNAGE,1,2],defense:[noir,noir],pdv:3,modattaque:annule2recul,desc:"%ACTIVATED% %XP%%XP%%XP%: %ROUNDCOND%, +1 %BLEU%"},
{nom:"Boucicaut",carac:"I%yM32*2r2",melee:[rouge,rouge,blanc],defense:[noir,noir],pdv:3,desc:"%SONTOUR%: %ROUNDCOND% vous pouvez jouer 2 %BLEU% pour activer %THIS%%BR%%ACTIVATED%%XP%%XP%%XP%: %TOURCOND%, +1 %BLEU%"},
{nom:"Bourgeois",carac:"Iw",desc:"%ACTIVATED%: %TOURCOND%, +1 %XP%"},
    {nom:"Bourreau",carac:"I",b2:[55,1,DEVOTS,0,0,0,1],melee:[jaune_blanctue],defense:[blanc],bonusmelee:[rouge,jaune_blanctue],bonuscond:sicommandee},
{nom:"Bélier",carac:"A",s1:[100,3,TOURDESIEGE,0,0,0,1],defense:[unbouclier,unbouclier],pdv:4,desc:"%ACTIVATED%: %ROUNDCOND%, +1 %DETRUIT% %TOFORTIFIEDGATE%"},
{nom:"Canon",carac:"A?",o1:[190,3,CANON,0,0,0,2],tir:[rouge,rouge],defense:[blanc],typetir:CLOCHE,portee:3,pdv:2},
{nom:"Captal de Buch",carac:"I£cM12*1j4",a1:[285,3,PERSONNAGE,1,2],melee:[rouge],defense:[noir],pdv:2,desc:"%ACTIVATED% %LEGENDE%: %TOURCOND%, + <span class='commandement'>&nbsp;&nbsp;&nbsp; 1</span> / <span class='commandement'><span style='color:black;text-shadow:1px 1px;'>1</span></span>"},
{nom:"Cavalerie Légère",carac:"Cqr3",a1:[120,1,CAVAL,0,3],a2:[115,1,CAVAL,2,4],melee:[blanc],defense:[jaune],desc:"%POURSUITE%: %TOURCOND%, +1 %MELEE%"},
{nom:"Cavalerie lourde Lituanienne",carac:"CùcF1",melee:[rouge,rouge],defense:[noir,blanc],modattaque:annule1recul},
{nom:"Cavaliers Archers",carac:"C?qr2",o1:[120,2,ARCHERS_M,0,0,0,3],tir:[jaune,jaune],defense:[blanc],typetir:TENDU,portee:1},
{nom:"Cavaliers Nobles",carac:"C?cR1",o1:[190,3,CAVAL,0,0,0,4],melee:[rouge,blanc],defense:[blanc,rouge],desc:"%DEFENSE%: <span class='recul'></span> &rarr; %CHOOSERECUL%"},
    {nom:"Cavaliers Polonais",carac:"Càc",melee:[rouge,blanc],defense:[blanc],bonusmelee:[rouge,rouge,blanc],bonuscond:sicharge},
{nom:"Cavaliers Sipahi",carac:"IC?cqr2",o1:[140,2,CAVAL,0,0,0,4],melee:[blanc_blanctue],defense:[blanc]},
{nom:"Cavaliers damnés",carac:"CâcR1s2",m2:[250,4,CAVAL,0,0,0,2],melee:[rouge,rouge],defense:[noir,rouge],modattaque:annule1recul},
{nom:"Chariot de guerre",carac:"Af",pdv:5,grand:true,tir:[rouge,blanc,blanc],portee:1,typetir:TENDU,defense:[noir,noir],desc:"%NORECUL%%BR%%DEPLACEMENTINFANTERIE%"},
{nom:"Charles II le Magnanime",carac:"C%xMA2*2R1c",melee:[rouge,jaune],defense:[blanc_blanccarte,blanc_blanccarte,jaune],pdv:3,desc:"%POURSUITE%: +1 %LEGENDE%"},
{nom:"Charles d'Albret",carac:"I%cxM22*1j4a",f3:[220,2,PERSONNAGE,1,2],melee:[blanc,blanc],defense:[noir],pdv:3,desc:"%MONTOUR% %XP%: %GRIS% &rarr; %VERT%%BR%%MELEE%: %MORT% &rarr; %XP%"},
{nom:"Charles de Bourbon",carac:"C%*1j4cx",f3:[200,3,PERSONNAGE,1,2],melee:[rouge,jaune_blanclegende],defense:[noir],pdv:2,desc:"%ACTIVATED% %LEGENDE%%LEGENDE%: +1 %RUMEUR%"},
{nom:"Chasseur",carac:"Iw",desc:"%ACTIVATED%: %TOURCOND%, consultez un jeton scénario placé dans la zone de %THIS%"},
    {nom:"Chevaliers Impétueux",carac:"IxR1",f1:[160,2,CHEVALERIE,0,4],B1:[160,2,CHEVALERIE,0,4],melee:[rouge,rouge,blanc],defense:[blanc],modattaque:annule1recul},
    {nom:"Chevaliers Teutoniques Montés",carac:"C€cxp",melee:[rouge,noir],defense:[noir],bonusmelee:[rouge,noir,blanc],bonuscond:siinfanterie},
{nom:"Chevaliers Teutoniques",carac:"I€cxp",melee:[rouge,noir],defense:[noir_tuebouclier]},
    {nom:"Chevaliers montés",carac:"C%cx",prenom:"Français",f3:[130,2,CHEVALERIE_M,2,6],melee:[rouge,rouge],defense:[noir],bonusmelee:[rouge,rouge,unrecul],bonuscond:sicharge},
    {nom:"Chevaliers montés",carac:"Cc",b2:[145,2,CHEVALERIE_M,0,0,0,4],b1:[145,2,CHEVALERIE_M,0,0,2,2],f1:[130,2,CHEVALERIE_M,2,6],B1:[130,2,CHEVALERIE_M,0,4],a3:[140,2,CHEVALERIE_M,0,0,0,4],melee:[rouge,rouge],defense:[noir]},
{nom:"Chevaliers montés",carac:"Cc",f1:[135,2,CHEVALERIE_M,2,6],f3:[135,2,CHEVALERIE_M,2,6],B1:[135,2,CHEVALERIE_M,0,4],a2:[135,2,CHEVALERIE_M,0,0,0,2],prenom:"Petite noblesse",melee:[rouge_bouclierrecule,noir_bouclierrecule],defense:[noir]},
{nom:"Chevaliers squelettes",carac:"Câcum",m2:[160,2,CAVAL,0,0,0,4],melee:[rouge,blanc],defense:[blanc],modattaque:annule1recul},
    {nom:"Chevaliers à pied",carac:"I",b1:[155,2,CHEVALERIE,0,4],b2:[130,2,CHEVALERIE,2,6],a1:[145,2,CHEVALERIE,0,4],a2:[140,2,CHEVALERIE,0,3],f1:[145,2,CHEVALERIE,0,4],B1:[145,2,CHEVALERIE,0,4],f2:[130,2,CHEVALERIE,0,2],prenom:"Armes à 2 mains",bonusmelee:[rouge,rouge,rouge],bonuscond:siinfanterie,melee:[rouge,rouge],defense:[noir]},
{nom:"Chevaliers à pied",carac:"IR1",b1:[130,2,CHEVALERIE,0,4],b2:[155,2,CHEVALERIE,2,6],a1:[165,2,CHEVALERIE,0,4],f2:[155,2,CHEVALERIE,0,2],melee:[rouge,rouge],defense:[noir],modattaque:annule1recul},
{nom:"Chiens de Chasse",carac:"Ir2F1",a1:[75,1,CHIENS,0,0,0,4],a2:[70,1,CHIENS,0,4],a3:[65,1,CHIENS,2,4],melee:[blanc,jaune],defense:[jaune]},
{nom:"Chiens de Guerre",carac:"Igr2",m3:[110,1,CHIENS,2,6],a2:[120,1,CHIENS,0,4],a3:[120,1,CHIENS,2,4],melee:[rouge,blanc],defense:[jaune]},
    {nom:"Claude de Chastellux",carac:"I~lM11q",melee:[noir,blanc],defense:[noir_blanclegende,jaune_blanclegende],pdv:2,B1:[160,2,PERSONNAGE,1,2]},
{nom:"Cola di Rienzo",carac:"IïyMA2o",b2:[195,3,PERSONNAGE,1,2],melee:[rouge],defense:[jaune_blancbouclier,jaune_blancbouclier],pdv:2},
{nom:"Comte d'Arundel",carac:"I£M11*1j3R1",a1:[265,3,PERSONNAGE,1,2],melee:[rouge],defense:[noir,jaune],pdv:2,desc:"%SPECIAL%: %TOURCOND%, %MOVE% %THIS% %HEREANDTHEREHEXA%"},
{nom:"Comte d'Auxerre",carac:"I%gMA1",f2:[190,3,PERSONNAGE,1,2],melee:[rouge,jaune,blanc],defense:[blanc,blanc],pdv:3},
    {nom:"Comte d'Oxford",carac:"I£cM12*1j4R1",a2:[290,5,PERSONNAGE,1,2],melee:[noir,jaune],defense:[blanc,rouge],pdv:3,bonusmelee:[noir,blanc,jaune],bonuscond:si3troupesinfanterie},
    {nom:"Comte de Northampton",carac:"I£M11*1j3P1",a2:[290,3,PERSONNAGE,1,2],melee:[rouge],defense:[blanc,blanc],pdv:2,bonusmelee:[rouge,jaune],bonuscond:si2troupesinfanterie,desc:"%TROUPE%%HERE%: + %MASSE%"},
{nom:"Comte de Salisbury",carac:"I£uyM11*1j4",a1:[260,2,PERSONNAGE,1,2],melee:[rouge_blancxp,jaune_blancxp],defense:[noir],pdv:2,desc:"1 %UNITE(Archers)%%HERE%%TIRCLOCHE%: +1 %DEROUGE%"},
{nom:"Comte de Suffolk",carac:"I£yMA1*1j3",a1:[190,3,PERSONNAGE,1,2],a3:[260,3,PERSONNAGE,1,2],melee:[rouge,jaune],defense:[blanc,blanc],pdv:2,desc:"%ACTIVATED%%XP%: %TOURCOND%, %RALLIE% %TROUPE%%HERE%"},
{nom:"Comte de Warwick",carac:"I£cM12*1j4o",a2:[250,5,PERSONNAGE,1,2],melee:[rouge,noir],defense:[noir],pdv:3,desc:"%ACTIVATED% %XP%: %TOURCOND%, %INFANTERIE%<span class='troupe combat-cond'></span>%HERE% + %CELERITE% 2"},
{nom:"Couleuvrine",carac:"Av",f3:[130,1,CANON,0,0,0,1],B1:[130,1,CANON,0,1],s1:[140,2,CANON,0,0,0,2],s2:[160,2,CANON,0,0,0,3],tir:[jaune_blancrecule,jaune_blancrecule,jaune_blancrecule],defense:[unbouclier],typetir:TENDU,portee:2},
{nom:"Coureurs des bois",carac:"Iùqr2",melee:[jaune],portee:1,typetir:TENDU,tir:[jaune,jaune],defense:[jaune],bonusattaque:doublereculsiforet},
{nom:"Devin",carac:"Iw",defense:[unbouclier],desc:"%ACTIVATED% %XP%%XP%%XP%: %CHOOSE% %CARTELEGENDE%"},
{nom:"Dracula",carac:"IâM21*1j5T1s2",m2:[335,6,PERSONNAGE,1,2],melee:[rouge,rouge],defense:[rouge,noir],pdv:3,desc:"%ACTIVATED%%LEGENDE%: %ROUNDCOND%,  + <span class='commandement'>&nbsp;&nbsp;&nbsp; 1</span>%BR%+1 %BLESSURE% &rarr; %LEGENDE% / %XP%"},
    {nom:"Dragon",carac:"VâT2H",melee:[rouge,rouge,rouge,blanc],tir:[rouge],portee:2,typetir:TENDU,defense:[unbouclier,unbouclier],pdv:20,desc:"2 %GRIS% &rarr; +1 %JAUNE%%BR%%ACTIVATED%, %LEGENDE%: +1 %TIRTENDU%%BR%%STARTGAME%: +5 %INCENDIE%%BR%%TIRTENDU%: %INCENDIE%%HERE%",modattaque:annuletoutrecul},
{nom:"Démons Volants",carac:"Vâls2",m1:[160,2,VOLANTS,0,0,0,3],m3:[160,2,VOLANTS,0,0,0,3],tir:[rouge,jaune_blanclegende],defense:[noir],typetir:TENDU,portee:1},
    {nom:"Démons Voraces",carac:"Iâc",m1:[125,2,DEMONS,0,0,0,2],m3:[125,2,FANTASSINS,0,0,2,0],bonusdefense:[blanc_blanctue,blanc_blanctue],bonuscond:simelee,melee:[rouge,rouge],defense:[blanc,blanc],contrecoup:ftrue},
    {nom:"Dévoreurs",carac:"Vât",m3:[135,2,VOLANTS,0,0,0,4],melee:[rouge],tir:[noir],defense:[blanc,jaune],typetir:TENDU,portee:1,desc:"%LEGENDE% %TIRTENDU%: <span class='bouclier facenoir'></span> &rarr; <span class='touche facenoir'></span> "},
{nom:"Dévôts",carac:"IïGy",b2:[150,1,DEVOTS,0,0,0,2],melee:[blanc]},
{nom:"Edmond de Sommerset",carac:"I£M11*1j4R1da",a3:[210,3,PERSONNAGE,1,2],melee:[noir,jaune],defense:[rouge],pdv:3},
{nom:"Edouard III",carac:"I£pM22*1j4a",a1:[385,5,PERSONNAGE,1,2],melee:[rouge,rouge],defense:[noir,noir],pdv:2,desc:"%CAMP%: %RALLIE%<span class='troupe combat-cond'></span>%BR%%ACTIVATED%: 1 %UNITE(Archers)%%HEREANDTHERE2% + %MELEE%"},
{nom:"Edouard d'York",carac:"I£cgM22*1j4",a1:[280,4,PERSONNAGE,1,2],melee:[noir,jaune],defense:[rouge],pdv:3,desc:"%ACTIVATED%: %TOURCOND%, %MOVE% %TOUTTYPE%<span class='tircloche combat-cond'></span> / %TOUTTYPE%<span class='tirtendu combat-cond'></span>%HERE%%BR%%MONTOUR%: +1 %LEGENDE%"},
{nom:"Erwan de Romorantin",carac:"I%M11*1j3",f2:[240,3,PERSONNAGE,1,2],melee:[rouge],defense:[noir,noir],pdv:2,desc:"%UNITE(Paysans)%%HERE%,%UNITE(Milice Bourgeoise)%%HERE%,%MELEE% +1 %DEBLANC%"},
{nom:"Espion",carac:"I£P1q",melee:[blanc,blanc],defense:[noir,jaune],pdv:2,desc:"%THIS% peut emprunter un Passage secret sans dépenser de jeton"},
{nom:"Expiateurs hérétiques",carac:"IâGpU",m1:[150,2,HERETIQUE,0,0,0,3],melee:[jaune],defense:[noir_blanclegende],desc:"%DEFENSE%: 1 %TOUTTYPE%%HERE% + %PARADE%"},
{nom:"Fantassins d'infanterie légère",carac:"IP3R3",melee:[blanc,jaune],defense:[jaune]},
{nom:"Fantômes",carac:"IâlnT1",m2:[160,1,FANTASSINS,0,0,0,2],melee:[blanc,blanc,blanc],defense:[blanc,blanc,blanc],desc:"%ACTIVATED% %LEGENDE%: %TOURCOND%, + %SAUT% 2"},
{nom:"Fermier",carac:"Iwe"},
    {nom:"Flagellants",carac:"Iïuc",b2:[70,1,DEVOTS,0,0,1,0],melee:[blanc],defense:[],bonusmelee:[blanc,blanc],bonuscond:sipenitents},
{nom:"Forgeron",carac:"Iw",f2:[160,2,SOUTIEN,0,1],melee:[jaune],desc:"%UNITE(Paysans)%%HERE%, %DEFENSE%: + %RIPOSTE%,<span class='melee'></span> +1 %DEJAUNE%"},
{nom:"Gargouilles",carac:"Vâr2",m3:[90,1,VOLANTS,0,0,0,3],tir:[jaune_blancrecule],defense:[noir],typetir:TENDU,portee:2},
{nom:"Gautier VI de Brienne",carac:"I%M12UE",melee:[rouge_bouclierrecule,blanc_bouclierrecule],defense:[noir],pdv:2},
{nom:"Gilles de Rais",carac:"I%*1j4MA1a",f3:[305,4,PERSONNAGE,1,2],melee:[rouge,rouge,jaune],defense:[noir],pdv:3,desc:"%ACTIVATED% %XP%: %TOURCOND%, %RALLIE%<span class='troupe combat-cond'></span>%HERE%%BR%%MELEE%: 1+ <span class='facerouge vierge'></span> / <span class='facejaune vierge'></span> &rarr; %REROLL% 1 %DEROUGE% / %DEJAUNE%"},
{nom:"Gog",carac:"IâeLUS",m2:[275,5,PERSONNAGE,1,2],melee:[jaune,jaune,blanc],defense:[noir,jaune,blanc],pdv:5,grand:true,desc:"%TOUTTYPE% ennemie à 1 hexagone: -1 %DEBLANC%<span class='melee combat-cond'></span>"},
{nom:"Guide",carac:"Iw",defense:[blanc],modattaque:annule1recul,desc:"%ACTIVATED% %XP%%XP%: %ROUNDCOND%, %MOVE% 1+ %TOUTTYPE%%HERE%"},
{nom:"Guillaume de Molins",carac:"I£pF1MA1*1j3",a3:[180,3,PERSONNAGE,1,2],melee:[rouge],defense:[noir],pdv:2},
{nom:"Guisarmiers",carac:"IP1h",a2:[75,1,HAST,2,6],a3:[80,1,HAST,0,5],e1:[75,1,HAST,2,2,0,1],f1:[70,1,HAST,2,5],f2:[75,1,HAST,0,5],f3:[80,1,HAST,2,6],melee:[jaune_blanctouche],defense:[blanc]},
{nom:"Guy le Bouteiller",carac:"I%M12",f3:[190,5,PERSONNAGE,1,2],melee:[rouge,blanc],defense:[rouge],pdv:2,desc:"%MELEE%: %MORT% &rarr; %XP%%BR%%LEGENDE% %DEFENSE%: <span class='facerouge tue'></span> &rarr; <span class='facerouge bouclier'></span>"},
{nom:"Hacquebutiers",carac:"IT1",s2:[100,1,ARCHERS,0,0,0,2],tir:[jaune_blanctue],defense:[noir],typetir:TENDU,portee:1},
    {nom:"Hallebardiers",carac:"IR1",a3:[125,1,HAST,0,5],e1:[130,2,HAST,2,2,0,1],f1:[110,1,HAST,2,5],f2:[130,2,HAST,0,5],f3:[135,1,HAST,2,6],bonusmelee:[blanc,blanc],bonuscond:siinfanterie,melee:[blanc],defense:[rouge,blanc]},
{nom:"Henry V",carac:"I£F1M12*1j4R1",melee:[noir,jaune],defense:[blanc,blanc],pdv:3,desc:"%MONTOUR% %XP%%LEGENDE%: +1 %BLEU%%BR%%MELEE%: 1+ <span class='bouclier'></span> &rarr; +1 %XP%"},
    {nom:"Héros Polonais monté",carac:"CàcM11*2",melee:[rouge,noir],defense:[noir],pdv:3,bonusmelee:[rouge,rouge,noir],bonuscond:sicharge,desc:"%MELEE%<span class='actionverte combat-cond'></span>: -1 %BOUCLIER%<span class='defense combat-cond'></span>"},
    {nom:"Héros Polonais monté",carac:"CàcMA1*1j4",melee:[rouge,noir],defense:[noir],pdv:2,bonusmelee:[rouge,noir,noir],bonuscond:sicharge},
{nom:"Héros Teutonique monté",carac:"C€cpM21*2P1",melee:[rouge,blanc,noir],defense:[noir],pdv:3},
{nom:"Héros Teutonique monté",carac:"C€cxpM11*1j3",en:"Mounted Hero",melee:[rouge,blanc,noir],defense:[noir],pdv:2},
{nom:"Héros",carac:"I%pF1MA1*1j3",b2:[170,3,PERSONNAGE,1,2],b1:[150,3,PERSONNAGE,1,2],b2:[160,3,PERSONNAGE,1,2],f1:[170,3,PERSONNAGE,1,2],f3:[160,3,PERSONNAGE,1,2],f2:[160,3,SOUTIEN,0,1],melee:[rouge],defense:[noir]},
{nom:"Héros",carac:"I~cu",B1:[120,1,PERSONNAGE,1,2],melee:[rouge,blanc],defense:[blanc],modattaque:annule1recul,pdv:2},
{nom:"Héros",carac:"I£pF1MA1*1j3",a1:[160,3,PERSONNAGE,1,2],a2:[170,3,PERSONNAGE,1,2],melee:[rouge],defense:[noir]},
{nom:"Héros Lituanien",carac:"IùMA1*1j2P1",melee:[blanc],defense:[noir]},
{nom:"Héros Lituanien",carac:"IùyM11*2P1",subfaction:BIEN,melee:[blanc,blanc],defense:[noir],pdv:2,desc:"<span class='foret combat'></span>%HERE% : + <span class='commandement'>&nbsp;&nbsp;&nbsp; 1</span>"},
{nom:"Héros Teutonique",carac:"I€cxF1M11*2",melee:[noir],defense:[noir],pdv:2,desc:"%MELEE%: pour chaque résultat %TUE% obtenu,lancez 1 %DENOIR%. Ce dé dispose du même effet"},
{nom:"Héros Teutonique",carac:"I€cxpMA1*1j3",melee:[noir],defense:[noir],desc:"%MELEE%: pour chaque résultat %TUE% obtenu,lancez 1 %DENOIR%. Ce dé dispose du même effet"},
{nom:"Hérétiques",carac:"Iv",m1:[90,1,HERETIQUE,0,0,1,0],melee:[noir,jaune],defense:[jaune_blanclegende],desc:"%MELEE%<span class='niveau2 combat-cond'></span>: <span class='recul'></span> &rarr; <span class='niveau1 combat'></span>"},
    {nom:"Infanterie de Soutien",carac:"IP1",melee:[jaune],defense:[noir,blanc]},
{nom:"Infanterie légère",carac:"I?qr2",o1:[80,1,FANTASSINS,0,0,2,6],melee:[blanc],defense:[jaune]},
{nom:"Jacques de Bourbon",carac:"I%MA2*1j4",f2:[205,3,PERSONNAGE,1,2],melee:[rouge],defense:[noir],pdv:2},
{nom:"Jacques le troubadour",carac:"IwT1",desc:"%DEFENSE%: 'Le Bon Endroit'%HEREANDTHERE% &rarr;  %ANNULER% 1+ %RECUL%"},
    {nom:"Janissaires",carac:"I?cmq",o1:[105,1,INFANTERIEELITE,2,4],melee:[noir],defense:[blanc],bonusmelee:[noir_boucliertouche],bonuscond:sixp},
{nom:"Jean 1er de Luxembourg",carac:"C%xP1",melee:[rouge,rouge,noir],defense:[blanc],pdv:2,desc:"%DEBUTACTIVATION%: %ROLL% %DENOIR%, <span class='facenoir tue'></span> &rarr; %OPPONENT% %MOVE% %THIS%%THERE%"},
{nom:"Jean II Le Bon",carac:"I%cxM12*1j3",patch:true,f1:[350,5,PERSONNAGE,1,2],melee:[rouge,rouge],defense:[noir],pdv:3,desc:"%MONTOUR%: +1 %VERT%"},
    {nom:"Jean II de Luxembourg",carac:"I£MA1*1j3aE",melee:[noir,blanc],defense:[blanc],pdv:2,bonusdefense:[blanc,blanc],bonuscond:siseul},
{nom:"Jean Jourdain",carac:"I%",f3:[180,2,PERSONNAGE,1,2],melee:[blanc],defense:[noir],pdv:2,desc:"Couleuvrine%HERE%%TIRTENDU%: +1 %DEROUGE%%BR%Couleuvrine%HERE%%TIRTENDU%: %MORT% &rarr; %XP%"},
{nom:"Jean Stuart de Buchan",carac:"IéhxMA1*1j4",e1:[300,3,PERSONNAGE,1,2],melee:[rouge,jaune],defense:[blanc],pdv:2,desc:"%ACTIVATED%%LEGENDE%:  + <span class='commandement'>&nbsp;&nbsp;&nbsp; 1</span> / <span class='commandement'><span style='color:black;text-shadow:1px 1px;'>1</span></span>%BR%%UNITE(Sergents d'armes)%<span class='commandementhexa combat-cond'></span>: %CANDOACTION% %CHARGE%"},
{nom:"Jean Stuart de Derneley",carac:"IécxF1MA1*1j2",e1:[320,4,PERSONNAGE,1,2],melee:[noir,noir],defense:[noir],pdv:2,desc:"%MELEE%: %MORT% &rarr; reprenez le jeton de relance si vous ne l'avez plus"},
{nom:"Jean de Bourbon",carac:"I%cM23*1j4R1L",f3:[250,3,PERSONNAGE,1,2],melee:[blanc,blanc],defense:[rouge,rouge],pdv:2},
{nom:"Jean de Brimeu",carac:"I~cMA2",B1:[190,2,PERSONNAGE,1,2],melee:[rouge],defense:[blanc,noir],pdv:2,modattaque:annule1recul,desc:"%DEFENSE%%THERE%: -1 <span class='recul'></span>"},
{nom:"Jean de Croy",carac:"I~MA1R1",B1:[125,2,PERSONNAGE,1,2],melee:[blanc,blanc],defense:[blanc_blanclegende,jaune_blanclegende],pdv:2},
{nom:"Jean de Dunois",carac:"I%MA1*1j4P1dr2",f3:[410,5,PERSONNAGE,1,2],melee:[rouge,jaune,blanc],defense:[noir,noir],pdv:2,desc:"%ONCEINGAME% %GRIS% &rarr; %BLEU%"},
{nom:"Jean de Lancastre",carac:"I£MA1*1j4R1",a3:[270,3,PERSONNAGE,1,2],melee:[blanc],defense:[jaune,jaune,blanc_blancbouclier],pdv:2,desc:"+X %CARTELEGENDE% &rarr; +1 %CARTELEGENDE%"},
{nom:"Jean de Metz",carac:"I%gR1",f3:[155,3,SOUTIEN,0,1],melee:[rouge],defense:[rouge],pdv:2,desc:"%LEGENDE% %DEFENSE%: <span class='facerouge tue'></span> &rarr; <span class='bouclier'></span>%BR%%MELEE%: %MORT% &rarr; %XP%"},
{nom:"Jean de Murs",carac:"IïGw",b2:[110,3,PERSONNAGE,1,2],desc:"lorsque %THIS% est dans un bâtiment,ce dernier gagne 1 point de résistance%BR%%LEGENDE%: %ROUNDCOND%, choisissez %CARTELEGENDE%"},
    {nom:"Jean de Toulongeon",carac:"I~yM12*1j4R1m",B1:[215,2,PERSONNAGE,1,2],melee:[noir],defense:[rouge,noir],pdv:2,desc:"%MELEE%: 1+ %MORT% &rarr; %CARTELEGENDE%"},
{nom:"Jean de Toulongeon",carac:"I~yM23*2R1m",melee:[noir,blanc],defense:[rouge,noir],pdv:3,desc:"%MELEE%: 1+ %MORT% &rarr; 2 %CARTELEGENDE%"},
{nom:"Jean de Vienne",carac:"I%p*1j3",f2:[255,3,PERSONNAGE,1,2],melee:[jaune,jaune],defense:[noir],pdv:3,modattaque:annule1touche,desc:"%ACTIVATED%: %ROUNDCOND%, %ROLL% 1 %DENOIR%,<span class='facenoir bouclier'></span> &rarr; -1 %LEGENDE% %ADVERSAIRE% / +1 %CARTELEGENDE%"},
{nom:"Jean, fils du Roi",carac:"I%cv",f1:[110,2,PERSONNAGE,1,2],c:110,melee:[blanc],defense:[noir],desc:"%MONTOUR% %LEGENDE%: %PERSONNAGE%%HERE% + Survie%BR%%MELEE%: 1+ %MORT% &rarr; %LEGENDE%"},
    {nom:"Jeanne d'Arc",carac:"C%pM22*1j4P1_r2",f3:[325,5,PERSONNAGE,1,2],melee:[blanc],defense:[noir,blanc],pdv:2,desc:"%ACTIVATED%: %ROUNDCOND%, +1 %JAUNE%"},
{nom:"Jeanne d'Arc",carac:"I%upM11*1j2T1",f3:[390,5,PERSONNAGE,1,2],melee:[blanc],defense:[noir],pdv:2,desc:"%ACTIVATED%: %ROUNDCOND%, en fin d'activation,jouez %JAUNE% depuis la réserve commune dans la zone sitée jusqu'à 3 zones de distance de %THIS%%BR%%CAMP%: %RETARDE% &rarr; %RALLIE%"},
{nom:"John Chandos",carac:"I£MA1*1j2R1o",a1:[290,3,PERSONNAGE,1,2],melee:[noir,jaune],defense:[rouge],pdv:2,desc:"%CONSEIL%: +1 %CARTELEGENDE%"},
{nom:"John Fastolf",carac:"I£MA1*1j3R1q",a3:[260,3,PERSONNAGE,1,2],melee:[noir,jaune],defense:[jaune,jaune],pdv:2,desc:"%DEFENSE%: %RECUL% &rarr; %MOVE% %THIS%%HEREANDTHERE2%"},
{nom:"John Hawkwood",carac:"I$F1M12E",a1:[195,1,MERCEN,0,0,0,1],melee:[noir_bouclierrecule],defense:[blanc],pdv:2,desc:"%ACTIVATED% %XP%: %ROUNDCOND%, +1 %BLEU%"},
{nom:"John Talbot",carac:"I£cF1M11*1j3",a3:[330,3,PERSONNAGE,1,2],melee:[rouge,noir],defense:[noir],pdv:2,desc:"%TROUPE%%HERE%: + %CHARGE%"},
    {nom:"John de la Pôle",carac:"I£GMA1*1j3",a3:[275,3,PERSONNAGE,1,2],melee:[rouge,jaune],defense:[noir,jaune],pdv:2,modattaque:transformetoucherecul},
{nom:"L'Inquisiteur",carac:"IïpM21",b3:[150,2,PERSONNAGE,1,2],b2:[185,3,PERSONNAGE,1,2],defense:[noir],pdv:2,desc:"%MONTOUR%: %ROLL% %DENOIR%: <span class='facenoir bouclier'></span> &rarr; prenez 1 %XP% / %LEGENDE% %ADVERSAIRE%%BR%%ACTIVATED% %LEGENDE%%LEGENDE%: +1 %RUMEUR%%BR%%THIS% peut seulement commander le Bourreau"},
    {nom:"La Bête",carac:"VâT2H",m1:[1110,10,APOCALYPSE,0,0,0,1],m2:[1110,10,APOCALYPSE,0,0,0,1],m3:[1110,10,APOCALYPSE,0,0,0,1],melee:[rouge,rouge,rouge],tir:[rouge],portee:2,typetir:TENDU,defense:[unbouclier,unbouclier],pdv:14,desc:"2 %LEGENDE% &rarr; +1 %JAUNE%%BR%%STARTGAME%: +2 %INCENDIE%%BR%%TIRTENDU%: %INCENDIE%%HERE%%BR%%MELEE%: 1-3 zones adjacentes"},
{nom:"La Cocatrix",carac:"VâvT1",m3:[350,5,PERSONNAGE,1,2],tir:[jaune_blanctouche,jaune_blanctouche,blanc_blanctouche],defense:[blanc,blanc],portee:1,typetir:TENDU,pdv:5,grand:true,desc:"%CONSEIL%: +1 %LEGENDE%"},
{nom:"La Grande Faucheuse",carac:"V$ulMA4T2",m2:[480,1,PERSONNAGE,1,2],melee:[rouge,blanc_blanctue,blanc_blanctue],defense:[noir],pdv:4,desc:"%CAMP% %LEGENDE%: choisissez une unité,%ROLL% le dé du destin,%MORT% / %RETARDE% &rarr; %MORT%"},
    {nom:"La Hire",carac:"I%c*1j4R1",f3:[375,5,PERSONNAGE,1,2],melee:[rouge,rouge,blanc],defense:[rouge,rouge],pdv:3,desc:"X %BLESSURE% &rarr; %MELEE%: +X %DEBLANC%%BR%%MELEE%: %MORT% &rarr; %XP%"},
    {nom:"Laima, Déesse de la Chance",carac:"Cù*1T1F1uMA1j4",melee:[noir,noir],defense:[noir,blanc],pdv:2,desc:"%MELEE%: %TUE% &rarr; +1 %XP% / +1 %LEGENDE%%BR%Après n'importe lequel de vos jet de dés, 1 %LEGENDE%: %REROLL% 1 dé"},
    {nom:"Laima, Déesse de la Chance",carac:"Cù*2T2F1r2uM12",melee:[noir,noir,noir],defense:[noir,noir],pdv:4,desc:"%MELEE%: %BOUCLIER%%BOUCLIER%%BOUCLIER% &rarr; %BOUCLIER% et <span class='facenoir vierge'></span> comptent comme %RECUL%%BR%Après n'importe lequel de vos jet de dés, 1 %LEGENDE%: %REROLL% 1 dé"},
    {nom:"La Licorne",carac:"IïLSr2",b1:[250,4,PERSONNAGE,1,2],melee:[blanc,blanc],defense:[blanc,blanc],pdv:5,desc:"%MELEE% / %DEFENSE%: 1 <span class='faceblanc vierge'></span> &rarr;  <span class='faceblanc touche'></span>  / <span class='faceblanc bouclier'></span>  / <span class='faceblanc recul'></span>"},
    {nom:"La Succube",carac:"Vâ*1s2p",bonusmelee:[jaune,jaune,rouge],bonuscond:sicartelegende,melee:[jaune,jaune,jaune],defense:[blanc,blanc],pdv:2,desc:"%MELEE%: %RECUL% &rarr; +1 %CARTELEGENDE%"},
    {nom:"La Tarasque",carac:"Iâ*1j4R1D",m3:[475,8,PERSONNAGE,1,2],melee:[rouge,rouge,rouge],defense:[noir,noir],pdv:8,postattaque:doubleblessure},
{nom:"Lala Sahin Pacha",carac:"I?yM12*1j5r2",o1:[325,4,PERSONNAGE,1,2],melee:[rouge,jaune],defense:[noir_toucherecule],pdv:2,desc:"%ACTIVATED%: %LEGENDE% &rarr; + <span class='commandement'>&nbsp;&nbsp;&nbsp; 1</span>"},
    {nom:"Lanciers montés",carac:"Cqr2",melee:[jaune,jaune,jaune],defense:[jaune],desc:"%MELEE%: <span class='facejaune vierge'></span> &rarr; %ANNULER% %BOUCLIER%"},
    {nom:"Le Diable",carac:"VâiM55vT2H",m1:[1175,9,APOCALYPSE,0,0,0,1],m2:[1175,9,APOCALYPSE,0,0,0,1],m3:[1175,9,APOCALYPSE,0,0,0,1],melee:[untue,rouge,rouge],defense:[unbouclier,unbouclier],pdv:14,modattaque:annuletoutrecul,desc:"2 %GRIS% &rarr; +1 %BLEU%%BR%%MELEE%: + %VISEE%"},
{nom:"Le Griffon",carac:"VïcF1os2",b1:[320,8,PERSONNAGE,1,2],melee:[noir_bouclierrecule,jaune_bouclierrecule,blanc_bouclierrecule],defense:[blanc,blanc],pdv:4,grand:true},
    {nom:"Le Léviathan",carac:"IâT2H",m1:[750,4,APOCALYPSE,0,0,0,1],m2:[750,4,APOCALYPSE,0,0,0,1],m3:[750,4,APOCALYPSE,0,0,0,1],melee:[unrecul,blanc,blanc,blanc,blanc],defense:[unbouclier,unbouclier],modattaque:annuletoutrecul,pdv:16,desc:"%MELEE%<span class='combat-cond batiment'></span>: 1 %DETRUIT%. Les unités mises Hors de Combat par %THIS% sont posées sur ce plateau au lieu de l’Infirmerie. Durant la phase de Camp, elles sont détruites sur un %TOUCHE%%BR%%MELEE%<span class='batiment combat-cond'></span>: 1 %DETRUIT%"},
{nom:"Le Prince Noir",carac:"C£cyM11*1j5_r2",a1:[435,5,PERSONNAGE,1,2],melee:[rouge,rouge,blanc_bouclierlegende],defense:[noir],pdv:3,desc:"%CAVALERIE%%HERE%: + %CELERITE% 2"},
{nom:"Le Prince Noir",carac:"I£M11*1j5aT1",a1:[300,4,PERSONNAGE,1,2],melee:[rouge,rouge],defense:[noir],pdv:2,desc:"%CAVALERIE%<span class='troupe combat-cond'></span>%HERE%: + %CELERITE% 2%BR%%ACTIVATED%: %MOVE% 1 %RALLIEMENT%"},
{nom:"Le Veneur",carac:"I%M12",melee:[blanc,blanc],defense:[blanc],desc:"%THIS% ne peut commander que les %UNITE(Chiens de Chasse)%%BR%%TOUTTYPE% à %HEREANDTHEREHEXA% doivent toute être révélées"},
{nom:"Loup-garou",carac:"Iâ*1j4",m3:[145,3,PERSONNAGE,1,2],melee:[jaune,jaune],defense:[noir],desc:"%MONTOUR%: +1 %GRIS%"},
{nom:"Loups",carac:"Iâqr2",m2:[70,1,CHIENS,0,0,0,4],m3:[60,1,CHIENS,2,6],melee:[blanc,jaune],defense:[jaune]},
{nom:"Légion démoniaque",carac:"Iâ",m1:[65,1,DEMONS,0,0,2,1],melee:[blanc],defense:[jaune_blanclegende,jaune_blanclegende],desc:"%ACTIVATED%: %TOURCOND%, %MOVE% %TROUPE%%THERE% dans la zone de %THIS%"},
{nom:"Léo l'aubergiste",carac:"ISwT2",desc:"%ACTIVATED%: %ROUNDCOND%, %PERSONNAGE%%HERE%  + <span class='commandement' style='color:black'>1</span>"},
{nom:"Magog",carac:"Iâcgo",m2:[430,7,PERSONNAGE,1,2],melee:[rouge,rouge,noir,blanc],defense:[noir,noir,blanc],pdv:7,grand:true,desc:"%ACTIVATED% %LEGENDE%: %ROUNDCOND%,  1 unité ennemie%THERE% %NOMOVE%%BR%%ROUNDCOND%, %CHOOSE% %PERSONNAGE%%THERE%: ce personnage n'attaque pas %THIS% durant le round &rarr; -1 %LEGENDE% / %XP%"},
{nom:"Manvydas",carac:"IùMA1*1r2",melee:[blanc,blanc],tir:[jaune,jaune],portee:1,typetir:TENDU,defense:[blanc],desc:"%MELEE%%FORET%: %TOUCHE% &rarr; +1 %RECUL%"},
{nom:"Marchande",carac:"Iw",desc:"%ACTIVATED%: %TOURCOND%, +1 %RUMEUR%"},
{nom:"Maréchal Arnoul d'Audrehem",carac:"I%cxM21*1j4o",melee:[rouge,rouge],defense:[noir],f1:[190,4,PERSONNAGE,1,2],modattaque:annule2recul,pdv:2},
{nom:"Maréchal Jean de Clermont",carac:"I%cxM12*1j4",f2:[190,5,PERSONNAGE,1,2],melee:[rouge_bouclierrecule,blanc_bouclierrecule],defense:[noir,blanc],pdv:2,desc:"%TROUPE%%HERE%: + %COHESION%"},
{nom:"Mathieu Goth",carac:"I£cxM22E",melee:[noir,jaune,unrecul],defense:[rouge],pdv:3,desc:"%POURSUITE%: %TOURCOND%, +1 %MELEE%"},
{nom:"Mehmet II",carac:"I?ypeM11*1j4",o1:[285,3,PERSONNAGE,1,2],melee:[noir],defense:[noir,blanc],pdv:2},
{nom:"Mehmet le Conquérant",carac:"V?iM22T2r2",o1:[550,6,PERSONNAGE,1,2],melee:[rouge,noir,jaune,jaune],defense:[noir,noir],grand:true,pdv:6,desc:"%MELEE%: <span class='facerouge vierge'></span> / <span class='facenoir vierge'></span> / <span class='facejaune vierge'></span> &rarr; %INCENDIE%<span class='melee combat-cond'></span>"},
    {nom:"Milice Bourgeoise",carac:"Im",s2:[35,1,MILICE,0,0,2,4],b3:[35,1,MILICE,0,0,3,3],b2:[35,1,PAYSANS,0,0,0,6],m1:[35,1,MILICE,0,0,0,4],a1:[35,1,PIQUIERS,2,6],e1:[40,1,PIQUIERS,2,2,2,2],f1:[35,1,MILICE,0,6],f2:[35,1,MILICE,0,0,3,3],melee:[blanc],defense:[jaune]},
{nom:"Milice Paysanne",carac:"ImF2",f1:[25,1,MILICE,0,6],f2:[25,1,PAYSANS,3,6],B1:[30,1,PAYSANS,0,4],melee:[blanc],defense:[]},
{nom:"Milice d'Archers",carac:"Iq",s2:[75,1,ARCHERS,0,0,2,2],e1:[70,1,ARCHERS,2,4],f2:[65,1,ARCHERS,2,5],tir:[noir],defense:[jaune],typetir:TENDU,portee:1},
{nom:"Monsieur Quirk",carac:"Ilw",desc:"%ACTIVATED% %MONTOUR%: un unité ennemie%THERE% &rarr; +1 %RUMEUR%"},
{nom:"Montreur d'ours",carac:"IR1T1",melee:[rouge,jaune,blanc],defense:[noir],desc:"%POURSUITE%: %ROUNDCOND%, +1 %MELEE%"},
    {nom:"Musicien",carac:"IM31T1",a1:[200,3,MUSICIEN,0,0,0,1],a2:[190,4,MUSICIEN,0,0,0,1],a3:[200,2,MUSICIEN,0,0,0,2],e1:[150,2,MUSICIEN,0,0,0,1],f1:[170,2,MUSICIEN,0,0,0,1],f3:[160,2,MUSICIEN,0,0,0,1],B1:[160,2,MUSICIEN,0,0,0,1],defense:[blanc,blanc],desc:"%MELEEONLY%%HERE% / %TIRTENDU%%HERE% / %TIRCLOCHE%%HERE%: +1 %DEBLANC%%BR%%CAMP%: 1 <span class='touche'></span> &rarr; 1 <span class='rallie'></span>"},
{nom:"Médecin",carac:"ISwr2",e1:[130,2,CIVIL,0,0,0,1],defense:[blanc],desc:"1 %TOUTTYPE%%HERE% %MORT%: %ROLL% %DEJAUNE%,<span class='facejaune vierge'></span> &rarr; %TOUCHE%"},
    {nom:"Narimantas",carac:"CùcgM11*1j4",melee:[rouge,noir],defense:[noir],pdv:2,desc:"%DEFENSE%: %TOUCHE%/ %RECUL%/ %TUE% &rarr; +1 %RIPOSTE% %RECUL%."},
{nom:"Noble dame",carac:"Iw",desc:"%ACTIVATED%: %ROUNDCOND%, +1 %LEGENDE% / %RUMEUR%%BR%%PERSONNAGE%%HERE%: + %CHARISME%"},
{nom:"Okchu",carac:"I?r2",o1:[85,2,ARCHERS,0,6],tir:[jaune_boucliertouche],defense:[jaune],typetir:CLOCHE,portee:2},
{nom:"Ours",carac:"IR1T1",melee:[rouge,jaune_blancrecule],defense:[noir],desc:"%POURSUITE%: %ROUNDCOND%, +1 %MELEE%"},
{nom:"Pape Clément VI",carac:"IïpM11*1T1",b3:[200,3,PERSONNAGE,1,2],defense:[noir],pdv:3,desc:"%ACTIVATED% %XP%: %ROUNDCOND%, +1 %RUMEUR%"},
{nom:"Pavois",carac:"If",s1:[100,1,PAVOIS,0,0,2,2],defense:[noir,blanc],pdv:4},
{nom:"Pavoisiers",carac:"I",defense:[noir,blanc],e1:[100,1,PAVOISIERS,0,0,0,3],f3:[110,1,PAVOISIERS,0,0,0,2],desc:"%TOUTTYPE%%HERE%,%DEFENSE%:  + %PARADE%"},
    {nom:"Paysans Révoltés",B1:[25,1,PAYSANS,0,4],carac:"Im",melee:[blanc],defense:[]},
{nom:"Paysans",carac:"Im",B1:[20,1,PAYSANS,0,4],b3:[20,1,PAYSANS,0,0,0,6],f2:[20,1,PAYSANS,3,6],melee:[jaune],defense:[],desc:"%SPECIAL%: -1 %INCENDIE%%HEREANDTHERE%"},
{nom:"Perkunas",carac:"VùM11*1j5T1s2",melee:[rouge,noir],tir:[blanc,blanc],portee:2,typetir:TENDU,defense:[unbouclier,unbouclier],pdv:3,grand:true,desc:"Il est impossible de se défendre contre une attaque de tir de Perkunas."},
{nom:"Pestiférés",carac:"ImT1",m2:[115,1,FANTASSINS,0,0,2,2],melee:[blanc],defense:[],modattaque:annule1touche},
{nom:"Petit Meschin",carac:"I$cgM12R1E",f1:[195,1,MERCEN,0,0,0,1],melee:[rouge_bouclierrecule,blanc_bouclierrecule],defense:[noir,rouge],pdv:3,desc:"%ACTIVATED%: %TOURCOND%,  réduisez le coût d'une %CARTELEGENDE%"},
    {nom:"Philippe VI de Valois",carac:"C%pM11*1j4",f1:[300,4,PERSONNAGE,1,2],melee:[rouge],defense:[noir,noir],pdv:2,modattaque:annule1recul,desc:"%ACTIVATED%: %ROUNDCOND%, %MOVE% 1 %CAVALERIE% d'une zone en direction d'une zone ennemie"},
{nom:"Philippe d'Orléans",carac:"I%cyM12*1j4am",f2:[240,3,0,1,2],melee:[rouge,blanc],defense:[noir],pdv:2,desc:"X %BLESSURE% &rarr; %MELEE%: +X %RECUL%"},
{nom:"Philippe de Vitry",carac:"IïS",b2:[125,3,PERSONNAGE,1,2],defense:[noir,jaune],desc:"%ACTIVATED% %LEGENDE%: %ROUNDCOND%, %MOVE% <span class='blason-large mal'></span> d'une zone%BR%%CAMP%: 1 %REROLL% le dé du destin"},
    {nom:"Philippe le Hardi",carac:"I%cF1P1",f2:[225,3,SOUTIEN,0,1],melee:[noir],defense:[noir,blanc] ,desc:"%PERSONNAGE%%HERE% : + %PARADE%%BR%Les unités dans sa zone ne peuvent subir d'attaque de tir"},
    {nom:"Piquiers Ecossais",carac:"Iémh",e1:[65,1,PIQUIERS,2,2,2,2],melee:[blanc],defense:[jaune],bonusdefense:[jaune_blanctue],bonuscond:sicavalerie,contrecoup:sicavalerie},
{nom:"Piquiers Flamands",carac:"IR2h",melee:[blanc],defense:[blanc]},
{nom:"Piquiers avec pavois",carac:"ImR2",melee:[blanc_bouclierrecule],defense:[noir]},
    {nom:"Piquiers",carac:"IR2",b1:[65,1,PIQUIERS,0,0,3,3],a1:[60,1,PIQUIERS,2,6],a2:[60,1,PIQUIERS,0,0,0,6],a3:[60,1,PIQUIERS,0,0,0,6],bonusmelee:[blanc,blanc],bonuscond:sicavalerie,f3:[60,1,PIQUIERS,0,0,0,6],melee:[blanc],defense:[jaune]},
{nom:"Porte-Etendard",carac:"IyM31q",a1:[230,3,MUSICIEN,0,0,0,1],a3:[240,3,MUSICIEN,0,0,0,1],e1:[250,3,MUSICIEN,0,0,0,1],f1:[240,3,MUSICIEN,0,0,0,1],f2:[260,3,MUSICIEN,0,0,0,1],f3:[280,3,MUSICIEN,0,0,0,1],B1:[280,3,MUSICIEN,0,0,0,1],defense:[blanc],modattaque:annule2touche,desc:"%CAMP%: 1 <span class='touche'></span> &rarr; 1 <span class='rallie'></span>"},
    {nom:"Poton de Xaintrailles",carac:"C%M12*2o",subfaction:MAL,melee:[noir,noir],defense:[noir],pdv:3,bonuscond:siLaHiredead,bonusdefense:[rouge,noir],desc:"%ROUNDCOND%, une zone adjacente ennemie vient de recevoir un ordre: +1 %MELEE%"},
{nom:"Poton de Xaintrailles",carac:"C%u*1j3",f3:[260,4,SOUTIEN,0,1],melee:[noir,jaune],defense:[noir],pdv:2,desc:"%MELEE%: %XP% &rarr; %REROLL% %DENOIR%%BR%La Hire%HEREANDTHERE% %DEFENSE% +1 %DENOIR%"},
{nom:"Poton de Xaintrailles",carac:"C%uM12*2r2",subfaction:BIEN,melee:[noir,noir],defense:[noir],pdv:3,desc:"La Hire%HEREANDTHERE% %DEFENSE% +1 %DENOIR%%BR%%ROUNDCOND%, une zone adjacente ennemie vient de recevoir un ordre: +1 %MELEE%"},
{nom:"Prigent de Coétivy",carac:"I%uGM12*1j3a",f3:[270,3,PERSONNAGE,1,2],melee:[blanc,jaune],defense:[rouge],pdv:2,desc:"%ROUNDCOND%, une zone ennemie%THERE% vient de recevoir un ordre: + %MELEE%"},
{nom:"Prigent de Coétivy",carac:"I%uGM13*2R1",melee:[blanc,blanc],defense:[rouge,rouge],pdv:2,desc:"%ROUNDCOND%, une zone ennemie%THERE% vient de recevoir un ordre: + %MELEE%%BR%%MONTOUR%: %MOVE% 1 %RALLIEMENT%"},
{nom:"Prêtre",carac:"IïNpJ0M12w",b3:[100,2,CIVIL,0,0,1,0]},
{nom:"Pénitents",carac:"Iïu",b2:[75,1,DEVOTS,0,0,1,0],melee:[rouge],defense:[],desc:"%MELEE%: %ROUNDCOND%, %TUE%<span class='mal combat-cond'></span> &rarr; +1 %VERT%%BR%%UNITE(Flagellants)%%HERE%: + %CHARGE%"},
{nom:"Radu III le Beau",carac:"I!M11*1j2a",melee:[blanc],defense:[blanc],pdv:2,desc:"%MELEE%: 1+ %BOUCLIER% &rarr; %BONUSMOVE%"},
{nom:"Rebouteuse",carac:"Iw",desc:"%CAMP%,%REROLL% une fois le dé du Destin pour deux unités alliés %TOUCHE%"},
    {nom:"Relique sacrée",carac:"IM52J0he",b1:[230,3,APOCALYPSE,0,0,0,1],b2:[230,3,APOCALYPSE,0,0,0,1],b3:[230,3,APOCALYPSE,0,0,0,1],pdv:3,defense:[noir]},
{nom:"Repentants hérétiques",carac:"Iâcur2",m1:[180,2,HERETIQUE,0,0,0,3],melee:[blanc,blanc],defense:[noir],desc:"%POURSUITE%: +1 %MELEE%"},
    {nom:"Ribaudequin",carac:"AT2",B1:[130,1,CANON,0,1],tir:[rouge,blanc],defense:[unbouclier],typetir:TENDU,portee:1,desc:"%STARTGAME%: %CANPUTSTAKEHEDGE%"},
{nom:"Robert Knolles",carac:"I$cM11UE",a1:[175,1,MERCEN,0,0,0,1],melee:[rouge,jaune],defense:[noir,blanc],pdv:3,desc:"%MELEE%:%MORT% &rarr; %XP%"},
{nom:"Roi Casimir IV de Lituanie",carac:"CùcF1M11*1j5P1R1",melee:[rouge,rouge],defense:[noir,blanc],pdv:3,desc:"%DEFENSE%,%THIS% seul dans sa zone: 1 %TOUCHE% &rarr; 1 %RECUL%"},
{nom:"Sainte Marthe",carac:"Iïp*1j5T0",b3:[175,1,PERSONNAGE,1,2],melee:[jaune],defense:[noir],modattaque:touchetuerecul},
{nom:"Sapeurs",carac:"IG",s1:[120,1,SAPEURS,0,0,0,3],melee:[blanc],defense:[blanc]},
    {nom:"Seguin de Badefol",carac:"I$GMA1P1UE",f1:[160,1,MERCEN,0,0,0,1],melee:[noir,blanc],defense:[blanc],pdv:3,desc:"%ACTIVATED% %LEGENDE%: %ROUNDCOND%, +2 %CARTELEGENDE%,%DEFAUSSEZEN% 1%BR%%ACTIVATED%: %TOURCOND%, + %LEGENDAIRE%"},
{nom:"Sergents Teutoniques",carac:"I€R1",melee:[rouge],defense:[noir,blanc]},
{nom:"Sergents d'armes montés",carac:"Ccr2",a1:[120,1,ARME,0,0,0,4],a2:[115,1,ARME,0,0,0,4],f2:[110,1,CAVAL,0,0,0,6],e1:[110,2,CAVAL,0,0,0,3],melee:[rouge],defense:[blanc]},
    {nom:"Sergents d'armes",carac:"IR1",e1:[90,1,ARME,0,0,3,3],f1:[90,1,ARME,0,0,0,4],B1:[90,1,ARME,0,4],f2:[100,2,ARME,0,4],a3:[140,2,ARME,0,4],melee:[rouge],defense:[rouge]},
{nom:"Sergents d'armes",carac:"IR1h",f2:[135,2,ARME,0,4],B1:[135,2,ARME,0,4],e1:[130,2,ARME,0,0,0,3],prenom:"Lourds",melee:[rouge,noir],defense:[noir]},
{nom:"Sergents d'armes",carac:"IcxR1",a1:[125,2,ARME,0,0,0,4],a2:[135,2,ARME,0,0,0,4],a3:[150,2,ARME,0,4],prenom:"Gascons & Bretons",melee:[rouge],defense:[noir],modattaque:annule1recul},
{nom:"Simon Morhier",carac:"I£G*1j2",a3:[195,3,PERSONNAGE,1,2],melee:[rouge],defense:[noir],pdv:2,desc:"%INFANTERIE%<span class='troupe combat-cond'></span>%HERE%%MELEE%: +1 %DEBLANC%"},
{nom:"Sir John Jouel",carac:"I£gMA1",a1:[205,3,PERSONNAGE,1,2],a2:[205,3,PERSONNAGE,1,2],melee:[blanc_blanctouche,blanc_blanctouche],defense:[blanc,noir],pdv:2},
    {nom:"Sorcière de Sabbat",carac:"VâpUvs2",f:'SdS',m1:[340,3,PERSONNAGE,1,2],tir:[rouge,rouge],portee:2,typetir:TENDU,defense:[noir],pdv:3,desc:"%MONTOUR%: 1+ %TUE% &rarr; +1 %LEGENDE%%BR%%TOUTTYPE%%HERE%: + Cruel"},
{nom:"Sorcière des marais",carac:"IâM11*1j2",melee:[blanc],defense:[noir,rouge],pdv:2,desc:"quand elle est dans une zone de marais,%THIS% ignore les effets de terrains liés aux marais et peut réaliser une action de mouvement vers n'importe quelle autre zone de marais du plateau de jeu%BR%%ACTIVATED% %LEGENDE%%LEGENDE%: %TOURCOND%, posez ou déplacez un jeton Marais sur une zone qui n'est pas une zone de village"},
{nom:"Sorcière",carac:"IâMA1*1j4q",m1:[145,3,PERSONNAGE,1,2],melee:[jaune_blanclegende],defense:[jaune],desc:"%MONTOUR%: +1 %CARTELEGENDE%"},
{nom:"Spectres montés",carac:"Câclq",m2:[200,1,CAVAL,0,0,0,4],melee:[rouge,blanc,blanc,],defense:[noir],desc:"Quand elle se déplace sur un nouvel hexagone,%THIS% peut se placer sur n'importe quelle zone de l'hexagone"},
    {nom:"Squelettes",carac:"Iâ",m1:[55,2,SQUELETTES,0,4],m3:[55,1,FANTASSINS,0,0,0,9],melee:[jaune],defense:[],modattaque:annule1recul,bonusmelee:[jaune,jaune],bonuscond:sisquelettes},
    {nom:"Squelettes",carac:"Iâl",m2:[60,1,SQUELETTES,0,0,0,4],prenom:"Danse Macabre",melee:[jaune],defense:[],bonusmelee:[jaune,jaune],bonuscond:sisquelettes},
    {nom:"Squelettes",carac:"Iâcm",m1:[75,1,SQUELETTES,0,4],prenom:"Démoniaques",melee:[jaune],defense:[],modattaque:annule1recul,bonusmelee:[jaune,jaune],bonuscond: sisquelettes},
{nom:"Thomas Kyriel",carac:"I£GM22*1j4v",a3:[280,2,PERSONNAGE,1,2],melee:[noir_blanclegende,jaune_blanclegende],defense:[noir],pdv:2,desc:"1 %UNITE(Archers)%%HERE% %TIRCLOCHE%: %TOURCOND%, +1 %DEROUGE%"},
{nom:"Thomas Montagu",carac:"I£GMA3a",a3:[370,5,PERSONNAGE,1,2],melee:[rouge,rouge,blanc],defense:[noir],pdv:2,desc:"%MONTOUR% %XP%%LEGENDE% : %CARTERIVIERE%%BR%%MONTOUR% %XP%%XP%: +1 %JAUNE%"},
{nom:"Thomas de Scales",carac:"C£ge*1j3c",a3:[210,3,PERSONNAGE,1,2],melee:[rouge],defense:[noir],pdv:2,desc:"%PERSONNAGE%%HERE%: + %ESQUIVE%"},
{nom:"Tour de Siège",carac:"Ay",s1:[260,4,TOURDESIEGE,0,0,0,1],defense:[unbouclier,unbouclier],grand:true,pdv:8,desc:"Lorsque %THIS% est adjacent à une fortification,%THIS% rend sa zone et toutes les zones adjacentes à elle adjacentes à cette fortification,et annule le bonus de défense de celle-ci."},
{nom:"Trébuchet",carac:"Av",s1:[150,2,BOMBARDE,0,0,0,2],tir:[blanc_blanctue,blanc_blanctue],defense:[unbouclier,unbouclier],typetir:CLOCHE,grand:true,pdv:2,portee:3,desc:"%TIRCLOCHE%<span class='combat-cond batiment'></span>: 1+ %TUE% &rarr; 1 %DETRUIT%"},
    {nom:"Triomphe",carac:"CïDs2cM31R0",b1:[360,5,APOCALYPSE,0,0,0,1],b2:[360,5,APOCALYPSE,0,0,0,1],b3:[360,5,APOCALYPSE,0,0,0,1],melee:[rouge,,blanc,jaune],defense:[noir,blanc],grand:true,pdv:6,desc:"%MELEE% / %DEFENSE%: <span class='facerouge vierge'></span>/<span class='facejaune vierge'></span>/<span class='faceblanc vierge'></span>/<span class='facenoir vierge'></span> &rarr; %TUE% / %TOUCHE% / %BOUCLIER%"},
{nom:"Vlad Tepes",carac:"I!F1M11*1j4P1T1r2",melee:[rouge],defense:[rouge,noir],pdv:2,desc:"%MELEE%: un des %TOUCHE% ne peut être annulé par %BOUCLIER%"},
    {nom:"Vougiers",carac:"IR1h",a2:[115,2,HAST,2,6],a3:[120,1,HAST,0,5],f2:[115,2,HAST,0,5],f3:[120,1,HAST,2,6],bonusmelee:[blanc,blanc],bonuscond:sicavalerie,melee:[blanc],defense:[rouge,blanc]},
    {nom:"Wickerman",carac:"Cù*1Dr2T2i",pdv:6,melee:[blanc,blanc,jaune,jaune],defense:[blanc,blanc],pdv:6,desc:"%MELEE%: %RECUL%%RECUL%%RECUL% &rarr; %TUE% non défendable%BR%%MELEE%: <span class='facejaune vierge'></span>/<span class='faceblanc vierge'></span> &rarr; +2 %RECUL%"},
{nom:"William Glasdale",carac:"I£M12*1j3R1v",a3:[300,4,PERSONNAGE,1,2],melee:[rouge,rouge],defense:[jaune,blanc],pdv:2,modattaque:transformetoucherecul},
{nom:"William Wallace",carac:"IécxM13*2",subfaction:BIEN,melee:[blanc,blanc],defense:[blanc,jaune],pdv:2,desc:"%POURSUITE%: %ROUNDCOND%, +1 %MELEE%%BR%%DEFENSE%: %RECUL% &rarr; %CHOOSERECUL%"},
{nom:"William de la Pôle",carac:"C£cMA1*1j3",melee:[rouge,jaune],defense:[noir],modattaque:transformetoucherecul},
{nom:"Winrich von Kniprod",carac:"C€cM11*1j4",melee:[rouge,blanc,jaune],defense:[blanc],pdv:2,desc:"%MELEE%: si %THIS% obtient au moins 2 %TOUCHE%,l'attaque de %THIS% ne peut pas être bloquée par des résultats %BOUCLIER%"},
{nom:"Yerli Kulu",carac:"I?mq",o1:[70,1,INFANTERIEELITE,2,4],melee:[jaune_blancrecule],defense:[jaune]},
{nom:"Yildirim Bayezid",carac:"I?cMA3*1j6Ur2",o1:[415,4,PERSONNAGE,1,2],melee:[rouge_bouclierrecule,noir_bouclierrecule],defense:[noir,noir],pdv:3,desc:"%MONTOUR% %LEGENDE%%LEGENDE%: %MOVE% 1 %RALLIEMENT%"},
];
