var liste_decors=[
    {text:"chariot",i:"chariot",hh:20,ll:28,grand:true},
    {text:"oratoire",i:"oratoire",small:true,hh:30,ll:15},
    {text:"arbuste",i:"arbuste",hh:20,ll:20},
    {text:"arbre",i:"arbre",hh:35,ll:25,medium:true},
    {text:"feu",i:"feu",hh:20,ll:20},
    {text:"puits",i:"puits",hh:20,ll:20},
    {text:"moulin",i:"moulin",hh:58,ll:20,grand:true},
    {text:"pont de pierre",i:"pont_pierre",hh:30,ll:20,grand:true},
    {text:"ruine",i:"ruine",hh:30,ll:20,medium:true},
    {text:"tente",i:"tente",hh:20,ll:20},
    {text:"église",i:"eglise",hh:40,ll:20,medium:true},
    {text:"chaumiere",i:"chaumiere",hh:40,ll:20,medium:true},
    {text:"MAISON",i:"maison2",hh:30,ll:20,medium:true},
    {text:"maison",i:"house1",hh:20,ll:20,medium:true},
    {text:"rochers",i:"rochers",hh:20,ll:20},
    {text:"pieux",i:"pieux",hh:20,ll:20},
    {text:"pieux60",i:"pieux60",hh:30,ll:20},
    {text:"pieux120",i:"pieux120",hh:30,ll:20},
    {text:"muret",i:"muret",hh:10,ll:25},
    {text:"muret60",i:"muret60",hh:30,ll:20,small:true},
    {text:"muret120",i:"muret120",hh:30,ll:20,small:true},
    {text:"palissade",i:"palissade",hh:20,ll:20,medium:true},
    {text:"palissade60",i:"palissade60",hh:20,ll:20},
    {text:"palissade120",i:"palissade120",hh:40,ll:20},
    {text:"ruine d'église",i:"ruine2",hh:20,ll:20,medium:true},
    {text:"porte",i:"porte",hh:35,ll:30,grand:true},
    {text:"tour",i:"tour",hh:30,ll:20},
    {text:"donjon",i:"donjon",hh:50,ll:30,grand:true},
    {text:"muraille",i:"muraille",hh:40,ll:20,grand:true},
    {text:"ralliement",i:"rallie_francais",hh:20,ll:20},
    {text:"ralliement",i:"rallie_anglais",hh:20,ll:20},
    {text:"ralliement",i:"rallie_mal",hh:20,ll:20},
    {text:"ralliement",i:"rallie_bien",hh:20,ll:20},
    {text:"ralliement",i:"rallie_valaque",hh:20,ll:20},
    {text:"ralliement",i:"rallie_ottoman",hh:20,ll:20},
    {text:"surprise",i:"surprise",hh:20,ll:20},
    {text:"objecif",i:"objectif",hh:20,ll:20},
    {text:"civil",i:"civil",hh:20,ll:20},
    
]
